---
permalink: sm-storage/add-to-workload.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add workload, volume 
summary: È possibile aggiungere uno o più volumi a un carico di lavoro nuovo o esistente per i volumi attualmente non associati a un carico di lavoro. 
---
= Aggiungere volumi a un carico di lavoro in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere uno o più volumi a un carico di lavoro nuovo o esistente per i volumi attualmente non associati a un carico di lavoro.

.A proposito di questa attività
I volumi non sono associati a un carico di lavoro se sono stati creati utilizzando l'interfaccia della riga di comando (CLI) o se sono stati migrati (importati/esportati) da un array di storage diverso.

.Fasi
. Dal pannello di sinistra, selezionare il menu:Storage[Volumes].
. Selezionare l'icona del menu:ellipsis [Add volumes to workload].
+
Viene visualizzata la vista Applications and workloads.

. Selezionare *Aggiungi al carico di lavoro*.
+
Viene visualizzata la finestra di dialogo Select workload (Seleziona carico di lavoro).

. Eseguire le seguenti azioni:
+
** *Aggiungi volumi a un carico di lavoro esistente* -- selezionare questa opzione per aggiungere volumi a un carico di lavoro esistente.
+
Utilizzare l'elenco a discesa per selezionare un carico di lavoro. Il tipo di applicazione associato al carico di lavoro viene assegnato ai volumi aggiunti a questo carico di lavoro.



. Selezionare i volumi che si desidera aggiungere al carico di lavoro.
. Esaminare i volumi che si desidera aggiungere al carico di lavoro selezionato.
. Quando sei soddisfatto della configurazione del workload, fai clic su *Add*.

