---
permalink: sm-storage/automatic-versus-manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, host, 
summary: 'La creazione di un host è una delle operazioni necessarie per consentire all"array di storage di sapere quali host sono collegati e di consentire l"accesso i/o ai volumi. È possibile creare un host automaticamente o manualmente.' 
---
= Creazione automatica e manuale degli host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La creazione di un host è una delle operazioni necessarie per consentire all'array di storage di sapere quali host sono collegati e di consentire l'accesso i/o ai volumi. È possibile creare un host automaticamente o manualmente.



== Creazione automatica

La creazione automatica dell'host per gli host basati su SCSI (non NVMe-of) viene avviata dall'HCA (host Context Agent). HCA è un'utility che è possibile installare su ciascun host collegato allo storage array. Ogni host su cui è installato l'HCA invia le informazioni di configurazione ai controller degli array di storage attraverso il percorso i/O. In base alle informazioni sull'host, i controller creano automaticamente l'host e le porte host associate e impostano il tipo di host. Se necessario, è possibile apportare ulteriori modifiche alla configurazione dell'host utilizzando System Manager.

Una volta che l'HCA ha eseguito il rilevamento automatico, l'host viene visualizzato automaticamente nella pagina host con i seguenti attributi:

* Il nome host derivato dal nome di sistema dell'host.
* Le porte di identificazione host associate all'host.
* Il tipo di sistema operativo host dell'host.


Gli host vengono creati come host standalone; l'HCA non crea o aggiunge automaticamente ai cluster di host.



== Creazione manuale

È possibile creare manualmente un host per uno dei seguenti motivi:

. Si è scelto di non installare l'utility HCA sugli host.
. Assicurarsi che gli identificatori della porta host rilevati dai controller degli array di storage siano associati correttamente agli host.


Durante la creazione manuale degli host, è possibile associare gli identificatori delle porte host selezionandoli da un elenco o inserendoli manualmente. Dopo aver creato un host, è possibile assegnarvi dei volumi o aggiungerlo a un cluster host se si intende condividere l'accesso ai volumi.
