---
permalink: sm-storage/cancel-pending-snapshot-image.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cancel, pending, snapshot, image 
summary: 'È possibile annullare un"immagine snapshot in sospeso prima del completamento. Gli snapshot vengono eseguiti in modo asincrono e lo stato dello snapshot rimane in sospeso fino al completamento dello snapshot. L"immagine snapshot viene completata al termine dell"operazione di sincronizzazione.' 
---
= Annullare un'immagine snapshot in sospeso in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile annullare un'immagine snapshot in sospeso prima del completamento. Gli snapshot vengono eseguiti in modo asincrono e lo stato dello snapshot rimane in sospeso fino al completamento dello snapshot. L'immagine snapshot viene completata al termine dell'operazione di sincronizzazione.

.A proposito di questa attività
Un'immagine snapshot si trova in uno stato in sospeso a causa delle seguenti condizioni simultanee:

* Il volume di base per un gruppo di snapshot o uno o più volumi membri di un gruppo di coerenza che contiene questa immagine snapshot è membro di un gruppo di mirror asincrono.
* Il volume o i volumi sono attualmente in un'operazione di sincronizzazione del mirroring asincrono.


.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Fare clic sulla scheda *Reserved Capacity* (capacità riservata).
. Seleziona il gruppo di snapshot per cui desideri annullare un'immagine snapshot in sospeso, quindi fai clic sull'icona menu:ellipsis icon[Cancel pending snapshot image].
. Fare clic su *Sì* per confermare che si desidera annullare l'immagine istantanea in sospeso.

