---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 'È possibile modificare le impostazioni di un volume, ad esempio il nome, l"assegnazione dell"host, la dimensione del segmento, la priorità di modifica, la memorizzazione nella cache, e così via.' 
---
= Modificare le impostazioni per un volume in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un volume, ad esempio il nome, l'assegnazione dell'host, la dimensione del segmento, la priorità di modifica, la memorizzazione nella cache, e così via.

.Prima di iniziare
Il volume che si desidera modificare si trova nello stato ottimale.


NOTE: Alcune operazioni potrebbero non essere disponibili mentre sono in corso modifiche alle impostazioni del volume

.Fasi
. Dal pannello di sinistra, selezionare il menu:Storage[Volumes].
. Seleziona il volume che desideri modificare, quindi fai clic sull'icona menu:ellipsis icon[Edit Settings].
+
Viene visualizzata la finestra Edit Volume Settings, che mostra le impostazioni di configurazione per il volume selezionato.

. Configura le impostazioni del volume secondo necessità:
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Nome
 a| 
Visualizza il nome del volume. Modificare il nome di un volume quando il nome corrente non è più significativo o applicabile.



 a| 
Host
 a| 
Visualizza l'assegnazione del volume. Si assegna un volume a un cluster host o host in modo che sia possibile accedervi per le operazioni di i/O. Questa assegnazione consente a un host o a un cluster di host di accedere a un determinato volume o a una serie di volumi in un array di storage.

** *Assegnato a* -- identifica l'host o il cluster di host che ha accesso al volume selezionato.
** *LUN* -- Un numero di unità logica (LUN) è il numero assegnato allo spazio degli indirizzi utilizzato da un host per accedere a un volume. Il volume viene presentato all'host come capacità sotto forma di LUN. Ogni host dispone di un proprio spazio di indirizzi LUN. Pertanto, lo stesso LUN può essere utilizzato da host diversi per accedere a volumi diversi.
+

NOTE: Per le interfacce NVMe, questa colonna visualizza l'ID dello spazio dei nomi. Uno spazio dei nomi è uno storage NVM formattato per l'accesso a blocchi. È analogo a un'unità logica in SCSI, che si riferisce a un volume nell'array di storage. L'ID dello spazio dei nomi è l'identificatore univoco del controller NVMe per lo spazio dei nomi e può essere impostato su un valore compreso tra 1 e 255. È analogo a un numero di unità logica (LUN) in SCSI.





 a| 
Dimensionamento dei segmenti
 a| 
Mostra l'impostazione per il dimensionamento dei segmenti, che viene visualizzata solo per i volumi in un gruppo di volumi. È possibile modificare le dimensioni del segmento per ottimizzare le prestazioni.

*Transizioni consentite per le dimensioni dei segmenti* -- System Manager determina le transizioni consentite per le dimensioni dei segmenti. Le dimensioni dei segmenti che sono transizioni inappropriate dalla dimensione corrente dei segmenti non sono disponibili nell'elenco a discesa. Le transizioni consentite solitamente sono il doppio o la metà delle dimensioni correnti del segmento. Ad esempio, se la dimensione attuale del segmento di volume è 32 KiB, è consentita una nuova dimensione del segmento di volume di 16 KiB o 64 KiB.

*Volumi SSD abilitati per la cache* -- è possibile specificare una dimensione di segmento 4 KiB per i volumi SSD abilitati per la cache. Assicurarsi di selezionare le dimensioni dei segmenti 4 KiB solo per i volumi con funzionalità SSD cache che gestiscono operazioni i/o a piccoli blocchi (ad esempio, blocchi i/o di dimensioni pari o inferiori a 16 KiB). Le performance potrebbero risentire se si seleziona 4 KiB come dimensione del segmento per i volumi abilitati per la cache SSD che gestiscono grandi operazioni sequenziali a blocchi.

*Tempo necessario per modificare le dimensioni dei segmenti* -- il tempo necessario per modificare le dimensioni dei segmenti di un volume dipende dalle seguenti variabili:

** Il carico di i/o dall'host
** La priorità di modifica del volume
** Il numero di dischi nel gruppo di volumi
** Il numero di canali del disco
** La potenza di elaborazione dei controller degli array di storage quando si modifica la dimensione del segmento per un volume, le prestazioni di i/o ne risentono, ma i dati rimangono disponibili.




 a| 
Priorità di modifica
 a| 
Mostra l'impostazione della priorità di modifica, che viene visualizzata solo per i volumi in un gruppo di volumi.

La priorità di modifica definisce il tempo di elaborazione allocato per le operazioni di modifica del volume in relazione alle prestazioni del sistema. È possibile aumentare la priorità di modifica del volume, anche se ciò potrebbe influire sulle prestazioni del sistema.

Spostare le barre di scorrimento per selezionare un livello di priorità.

*Modifica dei tassi di priorità* -- il tasso di priorità più basso offre benefici alle prestazioni del sistema, ma l'operazione di modifica richiede più tempo. Il tasso di priorità più elevato è utile per l'operazione di modifica, ma le prestazioni del sistema potrebbero essere compromesse.

|===
====
. Fare clic su *Save* (Salva).
+
System Manager modifica le impostazioni del volume in base alle selezioni effettuate.



.Al termine
Selezionare menu:Storage[Operations in Progress] per visualizzare lo stato di avanzamento delle operazioni di modifica attualmente in esecuzione per il volume selezionato.
