---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, volume 
summary: È possibile modificare le impostazioni di un volume di snapshot per regolare il punto percentuale in cui il sistema invia una notifica di avviso quando la capacità riservata di un volume di snapshot è quasi piena. 
---
= Modificare le impostazioni della capacità riservata per un volume snapshot in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un volume di snapshot per regolare il punto percentuale in cui il sistema invia una notifica di avviso quando la capacità riservata di un volume di snapshot è quasi piena.

.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Fare clic sulla scheda *Reserved Capacity* (capacità riservata).
. Seleziona il volume Snapshot che desideri modificare, quindi fai clic sull'icona menu:ellipsis icon[Edit Settings].
+
Viene visualizzata la finestra Modifica impostazioni capacità riservata volume Snapshot.

. Modificare le impostazioni di capacità riservata per il volume di snapshot in base alle esigenze.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Avvisami quando...
 a| 
Utilizzare la casella di selezione per regolare il punto percentuale in cui il sistema invia una notifica di avviso quando la capacità riservata per un volume membro è quasi piena.

Quando la capacità riservata per il volume di snapshot supera la soglia specificata, il sistema invia un avviso, consentendo di aumentare la capacità riservata o di eliminare oggetti non necessari.

|===
====
. Fare clic su *Save* (Salva) per applicare le modifiche alle impostazioni della capacità riservata del volume di snapshot.

