---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: È possibile modificare le impostazioni di un gruppo di snapshot per modificarne il nome, le impostazioni di eliminazione automatica, il numero massimo di immagini snapshot consentite, il punto percentuale in cui System Manager invia una notifica di avviso di capacità riservata o il criterio da utilizzare quando la capacità riservata raggiunge la percentuale massima definita. 
---
= Modificare le impostazioni di capacità riservata per un gruppo di snapshot in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un gruppo di snapshot per modificarne il nome, eliminare automaticamente le impostazioni, il numero massimo di immagini snapshot consentite, il punto percentuale in cui Gestione sistema SANtricity invia una notifica di avviso sulla capacità riservata o il criterio da utilizzare quando la capacità riservata raggiunge la percentuale massima definita.

Durante la creazione di un gruppo di snapshot, viene creata una capacità riservata per memorizzare i dati di tutte le immagini di snapshot contenute nel gruppo.

.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Fare clic sulla scheda *Reserved Capacity* (capacità riservata).
. Seleziona il gruppo di snapshot che desideri modificare, quindi fai clic sull'icona menu:ellipsis icon[Edit Settings].
+
Viene visualizzata la finestra Edit snapshot group settings.

. Modificare le impostazioni del gruppo di snapshot in base alle esigenze.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
*Impostazioni gruppo Snapshot*



 a| 
Nome
 a| 
Il nome del gruppo di snapshot. Specificare un nome per il gruppo di snapshot è obbligatorio.



 a| 
Eliminazione automatica dell'immagine Snapshot
 a| 
Un'impostazione che mantiene il numero totale di immagini snapshot nel gruppo pari o inferiore a un massimo definito dall'utente. Quando questa opzione è attivata, System Manager elimina automaticamente l'immagine snapshot meno recente nel gruppo ogni volta che viene creata una nuova istantanea, in modo da rispettare il numero massimo di immagini snapshot consentito per il gruppo.



 a| 
Limite dell'immagine Snapshot
 a| 
Un valore configurabile che specifica il numero massimo di immagini snapshot consentite per un gruppo di snapshot.



 a| 
*Impostazioni di capacità riservate*



 a| 
Avvisami quando...
 a| 
Utilizzare la casella di selezione per regolare il punto percentuale in cui System Manager invia una notifica di avviso quando la capacità riservata per un gruppo di snapshot è quasi piena.

Quando la capacità riservata per il gruppo di snapshot supera la soglia specificata, System Manager invia un avviso, consentendo di aumentare la capacità riservata o di eliminare oggetti non necessari.



 a| 
Policy per la capacità massima riservata
 a| 
È possibile scegliere una delle seguenti policy:

** *Rimuovi l'immagine snapshot meno recente* -- System Manager rimuove automaticamente l'immagine snapshot meno recente nel gruppo di snapshot, che rilascia la capacità riservata dell'immagine snapshot per il riutilizzo all'interno del gruppo.
** *Rifiuta scritture nel volume di base* -- quando la capacità riservata raggiunge la massima percentuale definita, System Manager rifiuta qualsiasi richiesta di scrittura i/o nel volume di base che ha attivato l'accesso alla capacità riservata.


|===
====
. Fare clic su *Save* (Salva) per applicare le modifiche alle impostazioni del gruppo di snapshot.

