---
permalink: sm-storage/change-workload-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload, settings 
summary: È possibile modificare il nome di un workload e visualizzarne il tipo di applicazione associato. Modificare il nome di un workload quando il nome corrente non è più significativo o applicabile. 
---
= Modificare le impostazioni del carico di lavoro in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare il nome di un workload e visualizzarne il tipo di applicazione associato. Modificare il nome di un workload quando il nome corrente non è più significativo o applicabile.

.Fasi
. Dal pannello di sinistra, selezionare il menu:Storage[Volumes].
. Seleziona la scheda *Applications and workloads*.
+
Viene visualizzata la vista Applications and workloads.

. Seleziona il carico di lavoro che desideri modificare, quindi fai clic sull'icona menu:ellipsis [Edit Settings].
+
Viene visualizzata la finestra di dialogo Applications and workloads Settings.

. *Opzionale:* modificare il nome del carico di lavoro fornito dall'utente.
. Fare clic su *Save* (Salva).

