---
permalink: sm-storage/change-allocated-capacity-limit-for-a-thin-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, allocated capacity, thin volume 
summary: Per i thin volumi in grado di allocare lo spazio on-demand, è possibile modificare il limite che limita la capacità allocata alla quale un thin volume può espandersi automaticamente. 
---
= Modificare il limite di capacità allocata per un volume sottile
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per i thin volumi in grado di allocare lo spazio on-demand, è possibile modificare il limite che limita la capacità allocata alla quale un thin volume può espandersi automaticamente.

È inoltre possibile modificare il punto percentuale in cui un avviso (soglia di avviso superata) viene inviato all'area Notifiche della pagina iniziale quando un volume sottile si trova vicino al limite di capacità allocata. È possibile scegliere di attivare o disattivare questa notifica di avviso.

[NOTE]
====
Questa funzione non è disponibile sui sistemi storage EF600 o EF300.

====
Il sistema espande automaticamente la capacità allocata in base al limite di capacità allocata. Il limite di capacità allocata consente di limitare la crescita automatica del thin volume al di sotto della capacità riportata. Quando la quantità di dati scritti si avvicina alla capacità allocata, è possibile modificare il limite di capacità allocata.

Quando si modifica il limite di capacità allocata e la soglia di avviso di un volume sottile, è necessario tenere conto dello spazio che deve essere consumato dai dati utente e dai dati dei servizi di copia del volume.

.Fasi
. Selezionare menu:Storage[Volumes] (Storage[volumi]).
. Selezionare la scheda *Thin Volume Monitoring*.
+
Viene visualizzata la vista Thin Volume Monitoring (monitoraggio volume sottile).

. Selezionare il volume sottile che si desidera modificare, quindi selezionare *Modifica limite*.
+
Viene visualizzata la finestra di dialogo Change Limit (Modifica limite). In questa finestra di dialogo vengono visualizzati il limite di capacità allocata e la soglia di avviso per il volume sottile selezionato.

. Modificare il limite di capacità allocata e la soglia di avviso in base alle necessità.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Modifica limite di capacità allocata in...
 a| 
La soglia alla quale le operazioni di scrittura non vengono eseguite, impedendo al thin volume di consumare risorse aggiuntive. Questa soglia è una percentuale delle dimensioni della capacità del volume riportate.



 a| 
Avvisami quando... (soglia di avviso)
 a| 
Selezionare questa casella di controllo se si desidera che il sistema generi un avviso quando un volume sottile si trova vicino al limite di capacità allocata. L'avviso viene inviato all'area Notifiche della home page. Questa soglia è una percentuale delle dimensioni della capacità del volume riportate.

Deselezionare la casella di controllo per disattivare la notifica di avviso della soglia di avviso.

|===
====
. Fare clic su *Save* (Salva).

