---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 'Modificare gli identificatori della porta host quando si desidera modificare l"etichetta utente su un identificatore della porta host, aggiungere un nuovo identificatore della porta host all"host o eliminare un identificatore della porta host dall"host.' 
---
= Modificare gli identificatori di porta host per un host in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Modificare gli identificatori della porta host quando si desidera modificare l'etichetta utente su un identificatore della porta host, aggiungere un nuovo identificatore della porta host all'host o eliminare un identificatore della porta host dall'host.

.A proposito di questa attività
Quando si modificano gli identificatori delle porte host, tenere presenti le seguenti linee guida:

* *Add* -- quando si aggiunge una porta host, si associa l'identificatore della porta host all'host creato per connettersi allo storage array. È possibile inserire manualmente le informazioni sulla porta utilizzando un'utility HBA (host bus adapter).
* *Edit* -- è possibile modificare le porte host per spostare (associare) una porta host a un host diverso. È possibile che l'host bus adapter o l'iSCSI Initiator siano stati spostati in un host diverso, quindi è necessario spostare (associare) la porta host nel nuovo host.
* *Delete* -- è possibile eliminare le porte host per rimuovere (disassociare) le porte host da un host.


.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Hosts].
. Seleziona l'host a cui saranno associate le porte, quindi fai clic sull'icona menu:ellipsis [Edit Settings].
+
Se si desidera aggiungere porte a un host in un cluster di host, selezionare l'host desiderato. Non è possibile aggiungere porte a livello di cluster di host.

+
Viene visualizzata una schermata Edit host settings che mostra le impostazioni host correnti.

. Modificare le impostazioni dell'identificatore della porta host in base alle esigenze.
+
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Porta host
 a| 
È possibile scegliere una delle seguenti opzioni:

** *Aggiungi porta host* -- Fare clic su *Aggiungi porta host* per associare un nuovo identificatore di porta host all'host. La lunghezza del nome dell'identificatore di porta host è determinata dalla tecnologia dell'interfaccia verso gli host. I nomi degli identificatori di porta host Fibre Channel e Infiniband devono avere 16 caratteri. I nomi degli identificatori di porta host iSCSI hanno un massimo di 223 caratteri. La porta deve essere univoca. Non è consentito un numero di porta già configurato.
** *Elimina (icona X)* -- Fare clic sull'icona *X* per rimuovere (disassociare) un identificatore di porta host. L'opzione di eliminazione non rimuove fisicamente la porta host. Questa opzione rimuove l'associazione tra la porta host e l'host. A meno che non si rimuova l'adattatore bus host o l'iSCSI initiator, la porta host viene comunque riconosciuta dal controller.
+
[NOTE]
====
Se si elimina un identificatore di porta host, questo non viene più associato a questo host. Inoltre, l'host perde l'accesso a uno qualsiasi dei volumi assegnati tramite questo identificatore di porta host.

====




 a| 
Nome
 a| 
Se necessario, è possibile modificare il nome dell'etichetta della porta. Il nome dell'etichetta della porta deve essere univoco. Non è consentito utilizzare un nome di etichetta già configurato.



 a| 
Segreto CHAP
 a| 
Viene visualizzato solo per gli host iSCSI. È possibile impostare o modificare il segreto CHAP per gli iniziatori (host iSCSI).

System Manager utilizza il metodo Challenge Handshake Authentication Protocol (CHAP), che convalida l'identità di destinazioni e iniziatori durante il collegamento iniziale. L'autenticazione si basa su una chiave di sicurezza condivisa chiamata CHAP secret (segreto CHAP).

|===
. Fare clic su *Save* (Salva).

