---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume 
summary: È possibile modificare le impostazioni di un volume di coppia mirrorata per regolare il punto percentuale in cui System Manager invia una notifica di avviso quando la capacità riservata per un volume di coppia mirrorata è quasi piena. 
---
= Modificare le impostazioni di capacità riservata per un volume di coppia con mirroring in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un volume di coppia di mirroring per regolare il punto percentuale in cui SANtricity System Manager invia una notifica di avviso quando la capacità riservata per un volume di coppia di mirroring si sta avvicinando al completo.

.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Selezionare la scheda *capacità riservata*.
. Seleziona il volume della coppia speculare che desideri modificare, quindi fai clic sull'icona menu:ellipsis icon[Edit Settings].
+
Viene visualizzata la finestra Edit Mirrored Pair Volume Reserved Capacity Settings.

. Modificare le impostazioni di capacità riservata per il volume di coppia mirrorata in base alle esigenze.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Soglia di allarme capacità riservata piena
 a| 
Utilizzare la barra per regolare il punto percentuale al quale System Manager invia una notifica di avviso quando la capacità riservata per una coppia mirror si sta avvicinando al pieno.

Quando la capacità riservata per la coppia mirrorata supera la soglia specificata, System Manager invia un avviso, consentendo di aumentare la capacità riservata.


NOTE: La modifica dell'impostazione Avviso per una coppia mirrorata modifica l'impostazione Avviso per tutte le coppie mirrorate che appartengono allo stesso gruppo di coerenza mirror.

|===
====
. Fare clic su *Save* (Salva) per applicare le modifiche.

