---
permalink: sm-storage/consolidate-volume-group-free-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, consolidate, free capacity, volume group 
summary: 'Utilizzare l"opzione consolida capacità libera per consolidare le estensioni libere esistenti su un gruppo di volumi selezionato. Eseguendo questa azione, è possibile creare volumi aggiuntivi dalla quantità massima di capacità libera in un gruppo di volumi.' 
---
= Consolidare la capacità libera per un gruppo di volumi
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare l'opzione consolida capacità libera per consolidare le estensioni libere esistenti su un gruppo di volumi selezionato. Eseguendo questa azione, è possibile creare volumi aggiuntivi dalla quantità massima di capacità libera in un gruppo di volumi.

.Prima di iniziare
* Il gruppo di volumi deve contenere almeno un'area di capacità libera.
* Tutti i volumi nel gruppo di volumi devono essere online e in uno stato ottimale.
* Le operazioni di modifica del volume non devono essere in corso, ad esempio la modifica delle dimensioni del segmento di un volume.


.A proposito di questa attività
Non è possibile annullare l'operazione dopo l'inizio. I dati rimangono accessibili durante l'operazione di consolidamento.

È possibile avviare la finestra di dialogo consolida capacità libera utilizzando uno dei seguenti metodi:

* Quando viene rilevata almeno un'area di capacità libera per un gruppo di volumi, il suggerimento "consolidare la capacità libera" viene visualizzato nella home page dell'area di notifica. Fare clic sul collegamento *consolida capacità libera* per avviare la finestra di dialogo.
* È inoltre possibile avviare la finestra di dialogo Consolida capacità libera dalla pagina Pools & Volume Groups come descritto nella seguente attività.


.Ulteriori informazioni sulle aree di capacità libera
[%collapsible]
====
Un'area di capacità libera è la capacità libera che può derivare dall'eliminazione di un volume o dal mancato utilizzo di tutta la capacità disponibile durante la creazione del volume. Quando si crea un volume in un gruppo di volumi che dispone di una o più aree di capacità libera, la capacità del volume viene limitata alla maggiore area di capacità libera del gruppo di volumi. Ad esempio, se un gruppo di volumi ha una capacità libera totale di 15 GiB e l'area di capacità libera più grande è di 10 GiB, il volume più grande che è possibile creare è di 10 GiB.

È possibile consolidare la capacità libera su un gruppo di volumi per migliorare le prestazioni di scrittura. La capacità libera del gruppo di volumi si frammenterà nel tempo man mano che l'host scrive, modifica ed elimina i file. Infine, la capacità disponibile non verrà collocata in un singolo blocco contiguo, ma verrà distribuita in piccoli frammenti all'interno del gruppo di volumi. Ciò causa un'ulteriore frammentazione dei file, poiché l'host deve scrivere nuovi file come frammenti per inserirli negli intervalli disponibili dei cluster liberi.

Consolidando la capacità libera su un gruppo di volumi selezionato, si noteranno migliori performance del file system ogni volta che l'host scrive nuovi file. Il processo di consolidamento consentirà inoltre di evitare la frammentazione dei nuovi file in futuro.

====
.Fasi
. Selezionare menu:Storage[Pools & Volume Groups] (Storage[Pools & Volume Groups])
. Selezionare il gruppo di volumi con capacità libera che si desidera consolidare, quindi selezionare menu:Uncommon Tasks[consolida capacità libera del gruppo di volumi].
+
Viene visualizzata la finestra di dialogo consolida capacità libera.

. Tipo `consolidate` per confermare che si desidera eseguire questa operazione.
. Fare clic su *consolida*.
+
System Manager inizia a consolidare (deframmentare) le aree di capacità libera del gruppo di volumi in una quantità contigua per le successive attività di configurazione dello storage.



.Al termine
Selezionare menu:Home[View Operations in Progress] (Visualizza operazioni in corso) per visualizzare l'avanzamento dell'operazione di consolidamento della capacità libera. Questa operazione può essere lunga e può influire sulle prestazioni del sistema.
