---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: 'È possibile creare volumi per aggiungere capacità di storage a un carico di lavoro specifico dell"applicazione e rendere visibili i volumi creati a un host o a un cluster host specifico. Inoltre, la sequenza di creazione dei volumi offre opzioni per allocare quantità specifiche di capacità a ciascun volume che si desidera creare.' 
---
= Creare volumi
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare volumi per aggiungere capacità di storage a un carico di lavoro specifico dell'applicazione e rendere visibili i volumi creati a un host o a un cluster host specifico. Inoltre, la sequenza di creazione dei volumi offre opzioni per allocare quantità specifiche di capacità a ciascun volume che si desidera creare.

.A proposito di questa attività
La maggior parte dei tipi di applicazioni utilizza per impostazione predefinita una configurazione di volume definita dall'utente. Alcuni tipi di applicazioni hanno una configurazione smart applicata alla creazione del volume. Ad esempio, se si creano volumi per l'applicazione Microsoft Exchange, viene chiesto quante caselle di posta sono necessarie, quali sono i requisiti medi di capacità delle caselle di posta e quante copie del database si desidera. System Manager utilizza queste informazioni per creare una configurazione ottimale del volume, che può essere modificata in base alle esigenze.

Il processo di creazione di un volume è una procedura a più fasi.



== Fase 1: Selezionare l'host per un volume

È possibile creare volumi per aggiungere capacità di storage a un carico di lavoro specifico dell'applicazione e rendere visibili i volumi creati a un host o a un cluster host specifico. Inoltre, la sequenza di creazione dei volumi offre opzioni per allocare quantità specifiche di capacità a ciascun volume che si desidera creare.

.Prima di iniziare
* Nel riquadro host sono presenti host o cluster di host validi.
* Sono stati definiti gli identificatori delle porte host per l'host.
* Prima di creare un volume abilitato da, la connessione host che si intende utilizzare deve supportare da. Se una delle connessioni host sui controller dello storage array non supporta il da, gli host associati non possono accedere ai dati sui volumi abilitati da.


.A proposito di questa attività
Tenere presenti queste linee guida quando si assegnano i volumi:

* Il sistema operativo di un host può avere limiti specifici sul numero di volumi a cui l'host può accedere. Tenere presente questa limitazione quando si creano volumi per l'utilizzo da parte di un determinato host.
* È possibile definire un'assegnazione per ciascun volume nell'array di storage.
* I volumi assegnati vengono condivisi tra i controller dell'array di storage.
* Lo stesso numero di unità logica (LUN) non può essere utilizzato due volte da un host o da un cluster host per accedere a un volume. È necessario utilizzare un LUN univoco.
* Se si desidera accelerare il processo di creazione dei volumi, è possibile saltare la fase di assegnazione dell'host in modo che i volumi appena creati vengano inizializzati offline.


[NOTE]
====
L'assegnazione di un volume a un host non riesce se si tenta di assegnare un volume a un cluster di host che è in conflitto con un'assegnazione stabilita per un host nei cluster di host.

====
.Fasi
. Selezionare menu:Storage[Volumes] (Storage[volumi]).
. Selezionare menu:Create[Volume] (Crea[Volume]).
+
Viene visualizzata la finestra di dialogo Create Volumes (Crea volumi).

. Dall'elenco a discesa, selezionare un host o un cluster host specifico al quale assegnare i volumi oppure scegliere di assegnare l'host o il cluster host in un secondo momento.
. Per continuare la sequenza di creazione del volume per l'host o il cluster host selezionato, fare clic su *Avanti* e passare a. <<Fase 2: Selezionare un carico di lavoro per un volume>>.
+
Viene visualizzata la finestra di dialogo Select workload (Seleziona carico di lavoro).





== Fase 2: Selezionare un carico di lavoro per un volume

Selezionare un carico di lavoro per personalizzare la configurazione dell'array di storage per un'applicazione specifica, ad esempio Microsoft SQL Server, Microsoft Exchange, applicazioni di videosorveglianza o VMware. È possibile selezionare "Other application" (altra applicazione) se l'applicazione che si desidera utilizzare su questo array di storage non è elencata.

.A proposito di questa attività
Questa attività descrive come creare volumi per un carico di lavoro esistente.

* _Quando si creano volumi utilizzando un carico di lavoro specifico dell'applicazione_, il sistema potrebbe consigliare una configurazione del volume ottimizzata per ridurre al minimo i conflitti tra i/o del carico di lavoro dell'applicazione e altro traffico proveniente dall'istanza dell'applicazione. È possibile rivedere la configurazione del volume consigliata e modificare, aggiungere o eliminare i volumi e le caratteristiche consigliate dal sistema utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).
* _Quando si creano volumi utilizzando "altre"_ applicazioni (o applicazioni senza supporto specifico per la creazione di volumi), si specifica manualmente la configurazione del volume utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).


.Fasi
. Effettuare una delle seguenti operazioni:
+
** Selezionare l'opzione *Create Volumes for a existing workload* (Crea volumi per un carico di lavoro esistente) per creare volumi per un carico di lavoro esistente.
** Selezionare l'opzione *Create a new workload* (Crea nuovo carico di lavoro) per definire un nuovo carico di lavoro per un'applicazione supportata o per "altre" applicazioni.
+
*** Dall'elenco a discesa, selezionare il nome dell'applicazione per cui si desidera creare il nuovo workload.
+
Selezionare una delle "altre" voci se l'applicazione che si desidera utilizzare su questo array di storage non è elencata.

*** Immettere un nome per il carico di lavoro che si desidera creare.




. Fare clic su *Avanti*.
. Se il carico di lavoro è associato a un tipo di applicazione supportato, inserire le informazioni richieste; in caso contrario, visitare il sito <<Fase 3: Aggiunta o modifica di volumi>>.




== Fase 3: Aggiunta o modifica di volumi

System Manager potrebbe suggerire una configurazione del volume in base all'applicazione o al carico di lavoro selezionato. Questa configurazione del volume è ottimizzata in base al tipo di applicazione supportata dal carico di lavoro. È possibile accettare la configurazione del volume consigliata o modificarla in base alle esigenze. Se è stata selezionata una delle "altre" applicazioni, è necessario specificare manualmente i volumi e le caratteristiche che si desidera creare.

.Prima di iniziare
* I pool o i gruppi di volumi devono disporre di capacità libera sufficiente.
* Il numero massimo di volumi consentito in un gruppo di volumi è 256.
* Il numero massimo di volumi consentiti in un pool dipende dal modello di sistema di storage:
+
** 2.048 volumi (serie EF600, EF600C e E5700)
** 1.024 volumi (EF300 e EF300C)
** 512 volumi (serie E4000 ed E2800)


* Per creare un volume abilitato per Data Assurance (da), la connessione host che si intende utilizzare deve supportare da.
+
.Selezione di un pool o di un gruppo di volumi sicuri
[%collapsible]
====
Se si desidera creare un volume abilitato da, selezionare un pool o un gruppo di volumi che supporti da (cercare *Sì* accanto a "da" nella tabella dei candidati del pool e del gruppo di volumi).

Le funzionalità DA vengono presentate a livello di pool e gruppo di volumi in System Manager. LA protezione DA verifica e corregge gli errori che potrebbero verificarsi quando i dati vengono trasferiti attraverso i controller fino ai dischi. La selezione di un pool o di un gruppo di volumi da-capable per il nuovo volume garantisce il rilevamento e la correzione degli errori.

Se una delle connessioni host sui controller dello storage array non supporta il da, gli host associati non possono accedere ai dati sui volumi abilitati da.

====
* Per creare un volume abilitato alla protezione, è necessario creare una chiave di sicurezza per l'array di storage.
+
.Selezione di un pool o di un gruppo di volumi sicuri
[%collapsible]
====
Se si desidera creare un volume abilitato alla protezione, selezionare un pool o un gruppo di volumi che supporti la protezione (cercare *Sì* accanto a "abilitato alla protezione" nella tabella dei candidati del gruppo di volumi e del pool).

Le funzionalità di sicurezza dei dischi vengono presentate a livello di pool e gruppo di volumi in System Manager. I dischi con funzionalità di sicurezza impediscono l'accesso non autorizzato ai dati su un disco che viene fisicamente rimosso dall'array di storage. Un disco abilitato alla sicurezza crittografa i dati durante la scrittura e decrta i dati durante la lettura utilizzando una _chiave di crittografia_ univoca.

Un pool o un gruppo di volumi può contenere dischi sicuri e non sicuri, ma tutti i dischi devono essere sicuri per poter utilizzare le proprie funzionalità di crittografia.

====
* Per creare un volume con provisioning di risorse, tutti i dischi devono essere dischi NVMe con l'opzione Deallocated o Unwritten Logical Block Error (DULBE).


.A proposito di questa attività
I volumi vengono creati da pool o gruppi di volumi. La finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi) mostra tutti i pool e i gruppi di volumi idonei nell'array di storage. Per ciascun pool e gruppo di volumi idonei, vengono visualizzati il numero di dischi disponibili e la capacità libera totale.

Per alcuni carichi di lavoro specifici dell'applicazione, ciascun pool o gruppo di volumi idoneo mostra la capacità proposta in base alla configurazione del volume suggerita e la capacità libera rimanente in GiB. Per gli altri carichi di lavoro, la capacità proposta viene visualizzata quando si aggiungono volumi a un pool o a un gruppo di volumi e si specifica la capacità riportata.

.Fasi
. Scegliere una di queste azioni in base alla selezione di un altro carico di lavoro o di un carico di lavoro specifico dell'applicazione:
+
** *Altro* -- fare clic su *Aggiungi nuovo volume* in ogni pool o gruppo di volumi che si desidera utilizzare per creare uno o più volumi.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrizione 


 a| 
Volume Name (Nome volume)
 a| 
System Manager assegna un nome predefinito a un volume durante la sequenza di creazione del volume. È possibile accettare il nome predefinito o fornire un nome descrittivo che indichi il tipo di dati memorizzati nel volume.



 a| 
Capacità riportata
 a| 
Definire la capacità del nuovo volume e le unità di capacità da utilizzare (MiB, GiB o TIB). Per i volumi spessi, la capacità minima è di 1 MiB e la capacità massima è determinata dal numero e dalla capacità delle unità nel pool o nel gruppo di volumi.

Tenere presente che la capacità di storage è necessaria anche per i servizi di copia (immagini snapshot, volumi snapshot, copie di volumi e mirror remoti); pertanto, non allocare tutta la capacità ai volumi standard.

La capacità in un pool viene allocata in incrementi di 4 o 8 GiB, a seconda del tipo di disco. Qualsiasi capacità che non sia un multiplo di 4 o 8 GiB viene allocata ma non utilizzabile. Per assicurarsi che l'intera capacità sia utilizzabile, specificare la capacità in incrementi di 4-GiB o 8-GiB. Se esiste una capacità inutilizzabile, l'unico modo per recuperarla è aumentare la capacità del volume.



 a| 
Dimensione blocco volume (solo EF300 e EF600)
 a| 
Mostra le dimensioni del blocco che è possibile creare per il volume:

*** 512 -- 512 byte
*** 4K -- 4,096 byte




 a| 
Dimensione segmento
 a| 
Mostra l'impostazione per il dimensionamento dei segmenti, che viene visualizzata solo per i volumi in un gruppo di volumi. È possibile modificare le dimensioni del segmento per ottimizzare le prestazioni.

*Transizioni consentite per le dimensioni dei segmenti* -- System Manager determina le transizioni consentite per le dimensioni dei segmenti. Le dimensioni dei segmenti che sono transizioni inappropriate dalla dimensione corrente dei segmenti non sono disponibili nell'elenco a discesa. Le transizioni consentite solitamente sono il doppio o la metà delle dimensioni correnti del segmento. Ad esempio, se la dimensione attuale del segmento di volume è 32 KiB, è consentita una nuova dimensione del segmento di volume di 16 KiB o 64 KiB.

*Volumi SSD abilitati per la cache* -- è possibile specificare una dimensione di segmento 4 KiB per i volumi SSD abilitati per la cache. Assicurarsi di selezionare le dimensioni dei segmenti 4 KiB solo per i volumi con funzionalità SSD cache che gestiscono operazioni i/o a piccoli blocchi (ad esempio, blocchi i/o di dimensioni pari o inferiori a 16 KiB). Le performance potrebbero risentire se si seleziona 4 KiB come dimensione del segmento per i volumi abilitati per la cache SSD che gestiscono grandi operazioni sequenziali a blocchi.

*Tempo necessario per modificare le dimensioni dei segmenti* -- il tempo necessario per modificare le dimensioni dei segmenti di un volume dipende dalle seguenti variabili:

*** Il carico di i/o dall'host
*** La priorità di modifica del volume
*** Il numero di dischi nel gruppo di volumi
*** Il numero di canali del disco
*** La potenza di elaborazione dei controller degli array di storage


Quando si modificano le dimensioni dei segmenti di un volume, le prestazioni i/o vengono compromesse, ma i dati rimangono disponibili.



 a| 
Sicuro
 a| 
*Sì* viene visualizzato accanto a "Secure-capable" solo se i dischi nel pool o nel gruppo di volumi sono protetti.

Drive Security impedisce l'accesso non autorizzato ai dati su un disco che viene fisicamente rimosso dallo storage array. Questa opzione è disponibile solo se la funzione Drive Security è stata attivata e se è stata impostata una chiave di sicurezza per lo storage array.

Un pool o un gruppo di volumi può contenere dischi sicuri e non sicuri, ma tutti i dischi devono essere sicuri per poter utilizzare le proprie funzionalità di crittografia.



 a| 
DA
 a| 
*Sì* viene visualizzato accanto a "da" solo se i dischi del pool o del gruppo di volumi supportano Data Assurance (da).

DA aumenta l'integrità dei dati nell'intero sistema storage. DA consente allo storage array di controllare gli errori che potrebbero verificarsi quando i dati vengono trasferiti attraverso i controller fino ai dischi. L'utilizzo di da per il nuovo volume garantisce il rilevamento di eventuali errori.



 a| 
Provisioning delle risorse (solo EF300 e EF600)
 a| 
*Sì* viene visualizzato accanto a "risorse fornite" solo se i dischi supportano questa opzione. Il provisioning delle risorse è una funzionalità disponibile negli array di storage EF300 e EF600, che consente di utilizzare immediatamente i volumi senza alcun processo di inizializzazione in background.

|===
====
** *Carico di lavoro specifico dell'applicazione* -- fare clic su *Avanti* per accettare i volumi e le caratteristiche raccomandati dal sistema per il carico di lavoro selezionato oppure fare clic su *Modifica volumi* per modificare, aggiungere o eliminare i volumi e le caratteristiche raccomandati dal sistema per il carico di lavoro selezionato.
+
.Dettagli del campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Campo | Descrizione 


 a| 
Volume Name (Nome volume)
 a| 
System Manager assegna un nome predefinito a un volume durante la sequenza di creazione del volume. È possibile accettare il nome predefinito o fornire un nome descrittivo che indichi il tipo di dati memorizzati nel volume.



 a| 
Capacità riportata
 a| 
Definire la capacità del nuovo volume e le unità di capacità da utilizzare (MiB, GiB o TIB). Per i volumi spessi, la capacità minima è di 1 MiB e la capacità massima è determinata dal numero e dalla capacità delle unità nel pool o nel gruppo di volumi.

Tenere presente che la capacità di storage è necessaria anche per i servizi di copia (immagini snapshot, volumi snapshot, copie di volumi e mirror remoti); pertanto, non allocare tutta la capacità ai volumi standard.

La capacità in un pool viene allocata in incrementi di 4 o 8 GiB, a seconda del tipo di disco. Qualsiasi capacità che non sia un multiplo di 4 o 8 GiB viene allocata ma non utilizzabile. Per assicurarsi che l'intera capacità sia utilizzabile, specificare la capacità in incrementi di 4-GiB o 8-GiB. Se esiste una capacità inutilizzabile, l'unico modo per recuperarla è aumentare la capacità del volume.



 a| 
Tipo di volume
 a| 
Il tipo di volume indica il tipo di volume creato per un carico di lavoro specifico dell'applicazione.



 a| 
Dimensione blocco volume (solo EF300 e EF600)
 a| 
Mostra le dimensioni del blocco che è possibile creare per il volume:

*** 512 -- 512 byte
*** 4K -- 4,096 byte




 a| 
Dimensione segmento
 a| 
Mostra l'impostazione per il dimensionamento dei segmenti, che viene visualizzata solo per i volumi in un gruppo di volumi. È possibile modificare le dimensioni del segmento per ottimizzare le prestazioni.

*Transizioni consentite per le dimensioni dei segmenti* -- System Manager determina le transizioni consentite per le dimensioni dei segmenti. Le dimensioni dei segmenti che sono transizioni inappropriate dalla dimensione corrente dei segmenti non sono disponibili nell'elenco a discesa. Le transizioni consentite solitamente sono il doppio o la metà delle dimensioni correnti del segmento. Ad esempio, se la dimensione attuale del segmento di volume è 32 KiB, è consentita una nuova dimensione del segmento di volume di 16 KiB o 64 KiB.

*Volumi SSD abilitati per la cache* -- è possibile specificare una dimensione di segmento 4 KiB per i volumi SSD abilitati per la cache. Assicurarsi di selezionare le dimensioni dei segmenti 4 KiB solo per i volumi con funzionalità SSD cache che gestiscono operazioni i/o a piccoli blocchi (ad esempio, blocchi i/o di dimensioni pari o inferiori a 16 KiB). Le performance potrebbero risentire se si seleziona 4 KiB come dimensione del segmento per i volumi abilitati per la cache SSD che gestiscono grandi operazioni sequenziali a blocchi.

*Tempo necessario per modificare le dimensioni dei segmenti* -- il tempo necessario per modificare le dimensioni dei segmenti di un volume dipende dalle seguenti variabili:

*** Il carico di i/o dall'host
*** La priorità di modifica del volume
*** Il numero di dischi nel gruppo di volumi
*** Il numero di canali del disco
*** La potenza di elaborazione dei controller degli array di storage quando si modifica la dimensione del segmento per un volume, le prestazioni di i/o ne risentono, ma i dati rimangono disponibili.




 a| 
Sicuro
 a| 
*Sì* viene visualizzato accanto a "Secure-capable" solo se i dischi nel pool o nel gruppo di volumi sono protetti.

La sicurezza del disco impedisce l'accesso non autorizzato ai dati su un disco che viene fisicamente rimosso dallo storage array. Questa opzione è disponibile solo se la funzione di sicurezza del disco è stata attivata e se è stata impostata una chiave di sicurezza per lo storage array.

Un pool o un gruppo di volumi può contenere dischi sicuri e non sicuri, ma tutti i dischi devono essere sicuri per poter utilizzare le proprie funzionalità di crittografia.



 a| 
DA
 a| 
*Sì* viene visualizzato accanto a "da" solo se i dischi del pool o del gruppo di volumi supportano Data Assurance (da).

DA aumenta l'integrità dei dati nell'intero sistema storage. DA consente allo storage array di controllare gli errori che potrebbero verificarsi quando i dati vengono trasferiti attraverso i controller fino ai dischi. L'utilizzo di da per il nuovo volume garantisce il rilevamento di eventuali errori.



 a| 
Provisioning delle risorse (solo EF300 e EF600)
 a| 
*Sì* viene visualizzato accanto a "risorse fornite" solo se i dischi supportano questa opzione. Il provisioning delle risorse è una funzionalità disponibile negli array di storage EF300 e EF600, che consente di utilizzare immediatamente i volumi senza alcun processo di inizializzazione in background.

|===
====


. Per continuare la sequenza di creazione del volume per l'applicazione selezionata, fare clic su *Avanti* e passare a. <<Fase 4: Esaminare la configurazione del volume>>.




== Fase 4: Esaminare la configurazione del volume

Esaminare un riepilogo dei volumi che si intende creare e apportare le modifiche necessarie.

.Fasi
. Esaminare i volumi che si desidera creare. Fare clic su *Indietro* per apportare le modifiche desiderate.
. Quando si è soddisfatti della configurazione del volume, fare clic su *fine*.


.Risultati
System Manager crea i nuovi volumi nei pool e nei gruppi di volumi selezionati, quindi visualizza i nuovi volumi nella tabella All Volumes (tutti i volumi).

.Al termine
* Eseguire tutte le modifiche del sistema operativo necessarie sull'host dell'applicazione in modo che le applicazioni possano utilizzare il volume.
* Eseguire l'utilità specifica del sistema operativo (disponibile presso un fornitore di terze parti), quindi eseguire il comando SMcli `-identifyDevices` per correlare i nomi dei volumi con i nomi degli array di archiviazione host.
+
SMcli è disponibile direttamente tramite il Gestore di sistema di SANtricity. Questa versione scaricabile di SMcli è disponibile sui controller E4000, EF600, EF600C, EF300, EF300C, E5700, EF570, E2800 e EF280. Per scaricare SMcli in Gestione sistema di SANtricity, selezionare *Impostazioni* > *sistema* e *componenti aggiuntivi* > *interfaccia riga di comando* .


