---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: 'La creazione del pool viene avviata automaticamente quando System Manager rileva dischi non assegnati nell"array di storage. È possibile utilizzare la creazione automatica del pool per configurare facilmente tutte le unità non assegnate nell"array di storage in un unico pool e per aggiungere unità nei pool esistenti.' 
---
= Crea automaticamente un pool in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La creazione del pool viene avviata automaticamente quando SANtricity System Manager rileva unità non assegnate nell'array di storage. È possibile utilizzare la creazione automatica del pool per configurare facilmente tutte le unità non assegnate nell'array di storage in un unico pool e per aggiungere unità nei pool esistenti.

.Prima di iniziare
È possibile avviare la finestra di dialogo Configurazione automatica pool quando si verifica una delle seguenti condizioni:

* È stato rilevato almeno un disco non assegnato che può essere aggiunto a un pool esistente con tipi di disco simili.
* Sono stati rilevati undici (11) o più dischi non assegnati che possono essere utilizzati per creare un nuovo pool (se non possono essere aggiunti a un pool esistente a causa di tipi di dischi diversi).


.A proposito di questa attività
Tenere presente quanto segue:

* Quando si aggiungono dischi a un array di storage, System Manager rileva automaticamente i dischi e richiede di creare un singolo pool o più pool in base al tipo di disco e alla configurazione corrente.
* Se i pool sono stati precedentemente definiti, System Manager richiede automaticamente di aggiungere le unità compatibili a un pool esistente. Quando vengono aggiunte nuove unità a un pool esistente, System Manager ridistribuisce automaticamente i dati nella nuova capacità, che ora include le nuove unità aggiunte.
* Quando si configura uno storage array EF600 o EF300, assicurarsi che ciascun controller abbia accesso a un numero uguale di dischi nei primi 12 slot e a un numero uguale di dischi negli ultimi 12 slot. Questa configurazione aiuta i controller a utilizzare entrambi i bus PCIe lato disco in modo più efficace.


È possibile avviare la finestra di dialogo Configurazione automatica pool utilizzando uno dei seguenti metodi:

* Quando viene rilevata capacità non assegnata, il suggerimento Pool Auto-Configuration viene visualizzato nell'area Notifiche (icona a forma di campana nella parte superiore della finestra). Fare clic su *Visualizza Pool Auto-Configuration* per aprire la finestra di dialogo.
* È inoltre possibile avviare la finestra di dialogo Configurazione automatica pool dalla pagina Pools and Volume Groups come descritto nella seguente attività.


.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Fai clic sull'icona menu:ellipsis [Launch pool auto-configuration].
+
La tabella dei risultati elenca i nuovi pool, i pool esistenti con le unità aggiunte o entrambi. Per impostazione predefinita, un nuovo pool viene denominato con un numero sequenziale.

+
System Manager esegue le seguenti operazioni:

+
** Crea un singolo pool se il numero di dischi con lo stesso tipo di disco (HDD o SSD) è sufficiente e la capacità è simile.
** Crea più pool se la capacità non assegnata è costituita da diversi tipi di dischi.
** Aggiunge le unità a un pool esistente se un pool è già definito nell'array di storage e si aggiungono nuove unità dello stesso tipo di disco al pool.
** Aggiunge le unità dello stesso tipo di unità al pool esistente e utilizza gli altri tipi di unità per creare pool diversi se le nuove unità sono di tipi diversi di unità.


. Per visualizzare ulteriori caratteristiche del pool, fare clic sul nome del pool visualizzato.
+
Vengono visualizzate informazioni relative al tipo di disco, alla funzionalità di sicurezza, alla funzione di data assurance (da), alla protezione contro la perdita di shelf e alla protezione contro la perdita di cassetto.

+
Per gli array di storage EF600 e EF300, vengono visualizzate anche le impostazioni relative al provisioning delle risorse e alle dimensioni dei blocchi di volume.

. Fare clic su *Accept* (Accetta).

