---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: 'Per gli host che non possono essere rilevati automaticamente, è possibile creare manualmente un host. La creazione di un host è una delle operazioni necessarie per consentire all"array di storage di sapere quali host sono collegati e di consentire l"accesso i/o ai volumi.' 
---
= Creare l'host manualmente
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per gli host che non possono essere rilevati automaticamente, è possibile creare manualmente un host. La creazione di un host è una delle operazioni necessarie per consentire all'array di storage di sapere quali host sono collegati e di consentire l'accesso i/o ai volumi.

.A proposito di questa attività
Tenere presenti queste linee guida quando si crea un host:

* È necessario definire le porte di identificazione host associate all'host.
* Assicurarsi di fornire lo stesso nome del nome di sistema assegnato all'host.
* Questa operazione non riesce se il nome scelto è già in uso.
* La lunghezza del nome non può superare i 30 caratteri.


.Fasi
. Selezionare menu:Storage[Hosts] (Storage[host]).
. Fare clic sul menu:Create[host] (Crea[host]).
+
Viene visualizzata la finestra di dialogo Create host (Crea host).

. Selezionare le impostazioni per l'host in base alle esigenze.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Nome
 a| 
Digitare un nome per il nuovo host.



 a| 
Tipo di sistema operativo host
 a| 
Selezionare il sistema operativo in esecuzione sul nuovo host dall'elenco a discesa.



 a| 
Tipo di interfaccia host
 a| 
(Facoltativo) se si dispone di più tipi di interfaccia host supportati sull'array di storage, selezionare il tipo di interfaccia host che si desidera utilizzare.



 a| 
Porte host
 a| 
Effettuare una delle seguenti operazioni:

** *Selezionare interfaccia i/o*
+
In genere, le porte host devono essere state registrate ed essere disponibili dall'elenco a discesa. È possibile selezionare gli identificatori della porta host dall'elenco.

** *Aggiunta manuale*
+
Se nell'elenco non viene visualizzato un identificatore di porta host, significa che la porta host non ha effettuato l'accesso. È possibile utilizzare un'utility HBA o l'utility iSCSI Initiator per individuare gli identificatori delle porte host e associarli all'host.

+
È possibile inserire manualmente gli identificatori della porta host o copiarli/incollarli dall'utility (uno alla volta) nel campo *host ports* (Porte host).

+
È necessario selezionare un identificatore di porta host alla volta per associarlo all'host, ma è possibile continuare a selezionare tutti gli identificatori associati all'host. Ciascun identificatore viene visualizzato nel campo *host ports* (Porte host). Se necessario, è anche possibile rimuovere un identificatore selezionando la *X* accanto.





 a| 
Iniziatore CHAP
 a| 
(Facoltativo) se si seleziona o si immette manualmente una porta host con un IQN iSCSI e si desidera richiedere un host che tenta di accedere allo storage array per l'autenticazione mediante Challenge Handshake Authentication Protocol (CHAP), selezionare la casella di controllo *CHAP Initiator*. Per ogni porta host iSCSI selezionata o inserita manualmente, procedere come segue:

** Immettere lo stesso segreto CHAP impostato su ciascun iniziatore host iSCSI per l'autenticazione CHAP. Se si utilizza l'autenticazione CHAP reciproca (autenticazione bidirezionale che consente a un host di validarsi nell'array di storage e a un array di storage di validarsi nell'host), è necessario impostare anche il segreto CHAP per l'array di storage durante la configurazione iniziale o modificando le impostazioni.
** Lasciare vuoto il campo se non si richiede l'autenticazione dell'host.


Attualmente, l'unico metodo di autenticazione iSCSI utilizzato da System Manager è CHAP.

|===
====
. Fare clic su *Create* (Crea).


.Risultati
Una volta creato correttamente l'host, il sistema crea un nome predefinito per ciascuna porta host configurata per l'host (etichetta utente).

L'alias predefinito è <``Hostname_Port Number``>. Ad esempio, l'alias predefinito per la prima porta creata per `host IPT is IPT_1`.
