---
permalink: sm-storage/create-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, ssd, cache 
summary: 'Per accelerare dinamicamente le performance del sistema, puoi utilizzare la funzione SSD cache per memorizzare nella cache i dati più utilizzati (dati "hot") su unità a stato solido (SSD) a latenza inferiore. La cache SSD viene utilizzata esclusivamente per le letture host.' 
---
= Creazione della cache SSD
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per accelerare dinamicamente le performance del sistema, puoi utilizzare la funzione SSD cache per memorizzare nella cache i dati più utilizzati (dati "hot") su unità a stato solido (SSD) a latenza inferiore. La cache SSD viene utilizzata esclusivamente per le letture host.

.Prima di iniziare
L'array di storage deve contenere alcune unità SSD.

[NOTE]
====
La cache SSD non è disponibile sul sistema storage EF600 o EF300.

====
.A proposito di questa attività
Quando crei una cache SSD, puoi utilizzare una o più unità. Poiché la cache di lettura si trova nell'array di storage, il caching viene condiviso tra tutte le applicazioni che utilizzano l'array di storage. Selezionare i volumi che si desidera memorizzare nella cache, quindi il caching viene automaticamente e dinamico.

Per creare la cache SSD, seguire queste linee guida.

* È possibile attivare la sicurezza sulla cache SSD solo quando viene creata, non in un secondo momento.
* È supportata una sola cache SSD per array di storage.
* La capacità massima di cache SSD utilizzabile su un array di storage dipende dalla capacità della cache primaria del controller.
* La cache SSD non è supportata sulle immagini Snapshot.
* Se si importano o esportano volumi con cache SSD attivata o disattivata, i dati memorizzati nella cache non vengono importati o esportati.
* Qualsiasi volume assegnato per l'utilizzo della cache SSD di un controller non è idoneo per un trasferimento automatico del bilanciamento del carico.
* Se i volumi associati sono abilitati per la sicurezza, creare una cache SSD abilitata per la sicurezza.


.Fasi
. Selezionare menu:Storage[Pools & Volume Groups] (Storage[Pools & Volume Groups])
. Fare clic sul menu:Create[SSD cache] (Crea[cache SSD]).
+
Viene visualizzata la finestra di dialogo Create SSD cache (Crea cache SSD).

. Digitare un nome per la cache SSD.
. Selezionare l'SSD cache Candidate che si desidera utilizzare in base alle seguenti caratteristiche.
+
[cols="25h,~"]
|===
| Caratteristica | Utilizzare 


 a| 
Capacità
 a| 
Mostra la capacità disponibile in GiB. Seleziona la capacità per le esigenze di storage della tua applicazione.

La capacità massima per la cache SSD dipende dalla capacità della cache primaria del controller. Se si assegna una quantità superiore a quella massima alla cache SSD, la capacità aggiuntiva non è utilizzabile.

La capacità della cache SSD è importante per la capacità complessiva allocata.



 a| 
Dischi totali
 a| 
Mostra il numero di dischi disponibili per questa cache SSD. Selezionare l'SSD candidate con il numero di dischi desiderato.



 a| 
Sicuro
 a| 
Indica se SSD cache Candidate è composto interamente da dischi sicuri, che possono essere dischi con crittografia completa del disco (FDE) o dischi FIPS (Federal Information Processing Standard).

Se si desidera creare una cache SSD abilitata per la sicurezza, cercare *Sì - FDE* o *Sì - FIPS* nella colonna abilitato per la sicurezza.



 a| 
Abilitare la sicurezza?
 a| 
Fornisce l'opzione per attivare la funzione Drive Security con dischi sicuri. Se si desidera creare una cache SSD abilitata per la protezione, selezionare la casella di controllo Enable Security (attiva protezione).

[NOTE]
====
Una volta attivata, la sicurezza non può essere disattivata. È possibile attivare la sicurezza sulla cache SSD solo quando viene creata, non in un secondo momento.

====


 a| 
Compatibile CON DA
 a| 
Indica se Data Assurance (da) è disponibile per questo SSD cache Candidate. Data Assurance (da) verifica e corregge gli errori che potrebbero verificarsi quando i dati vengono trasferiti attraverso i controller fino ai dischi.

Se si desidera utilizzare il da, selezionare un SSD cache Candidate che sia compatibile con il da. Questa opzione è disponibile solo se la funzione da è stata attivata.

La cache SSD può contenere sia dischi da-capable che non da-capable, ma tutti i dischi devono essere da-capable per poter utilizzare da.

|===
. Associare la cache SSD ai volumi per i quali si desidera implementare il caching in lettura SSD. Per attivare immediatamente la cache SSD sui volumi compatibili, selezionare la casella di controllo *Enable SSD cache on existing compatible volumes that are mapped to hosts* (attiva cache SSD sui volumi compatibili esistenti mappati agli host).
+
I volumi sono compatibili se condividono le stesse funzionalità di Drive Security e da.

. Fare clic su *Create* (Crea).

