---
permalink: sm-storage/delete-host-or-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, host, host cluster 
summary: È possibile eliminare un host o un cluster di host. 
---
= Eliminare l'host o il cluster host
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare un host o un cluster di host.

.A proposito di questa attività
Tenere presenti queste linee guida quando si elimina un host o un cluster host:

* Tutte le assegnazioni di volume specifiche vengono eliminate e i volumi associati sono disponibili per una nuova assegnazione.
* Se l'host fa parte di un cluster host che dispone di assegnazioni specifiche, il cluster host non viene influenzato. Tuttavia, se l'host fa parte di un cluster di host che non ha altre assegnazioni, il cluster di host e qualsiasi altro host o identificativo di porta host associato ereditano eventuali assegnazioni predefinite.
* Tutti gli identificatori di porta host associati all'host diventano indefiniti.


.Fasi
. Selezionare menu:Storage[Hosts] (Storage[host]).
. Selezionare l'host o il cluster host che si desidera eliminare, quindi fare clic su *Delete* (Elimina).
+
Viene visualizzata la finestra di dialogo di conferma.

. Confermare che si desidera eseguire l'operazione, quindi fare clic su *Delete* (Elimina).


.Risultati
Se si elimina un host, il sistema esegue le seguenti operazioni:

* Elimina l'host e, se applicabile, lo rimuove dal cluster host.
* Rimuove l'accesso a tutti i volumi assegnati.
* Riporta i volumi associati a uno stato non assegnato.
* Restituisce gli identificatori di porta host associati all'host a uno stato non associato.


Se si elimina un cluster host, il sistema esegue le seguenti operazioni:

* Elimina il cluster host e gli host associati (se presenti).
* Rimuove l'accesso a tutti i volumi assegnati.
* Riporta i volumi associati a uno stato non assegnato.
* Restituisce gli identificatori di porta host associati agli host a uno stato non associato.

