---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sulle unità di archiviazione per SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



[[what-is-a-hot-spare-drive]]
== Che cos'è un disco hot spare?

Le hot spare fungono da unità di standby nei gruppi di volumi RAID 1, RAID 5 o RAID 6. Si tratta di dischi completamente funzionanti che non contengono dati. Se un disco si guasta nel gruppo di volumi, il controller ricostruisce automaticamente i dati dal disco guasto a un hot spare.

Se un disco si guasta nell'array di storage, il disco hot spare viene sostituito automaticamente per il disco guasto senza richiedere uno swap fisico. Se il disco hot spare è disponibile quando si verifica un guasto, il controller utilizza i dati di ridondanza per ricostruire i dati dal disco guasto al disco hot spare.

Un hot spare non è dedicato a uno specifico gruppo di volumi. Puoi usare un hot spare per qualsiasi unità guasta nell'array di storage con la stessa capacità o una capacità inferiore. Un hot spare deve essere dello stesso tipo di supporto (HDD o SSD) delle unità che protegge. Nei sistemi EF80 e EF50, gli hot spare devono anche corrispondere al tipo di unità Capacity.

[NOTE]
====
I dischi hot spare non sono supportati con i pool. Invece dei dischi hot spare, i pool utilizzano la capacità di conservazione all'interno di ogni disco che comprende il pool.

====


[[what-is-preservation-capacity]]
== Che cos'è la capacità di conservazione?

La capacità di conservazione è la quantità di capacità (numero di dischi) riservata in un pool per supportare potenziali guasti del disco.

Quando viene creato un pool, il sistema riserva automaticamente una quantità predefinita di capacità di conservazione in base al numero di dischi nel pool.

I pool utilizzano la capacità di conservazione durante la ricostruzione, mentre i gruppi di volumi utilizzano dischi hot spare per lo stesso scopo. Il metodo della capacità di conservazione è un miglioramento rispetto ai dischi hot spare perché consente una ricostruzione più rapida. La capacità di conservazione viene distribuita su un certo numero di dischi nel pool invece che su un disco nel caso di un disco hot spare, in modo da non essere limitati dalla velocità o dalla disponibilità di un disco.



[[why-would-i-logically-replace-a-drive]]
== Perché dovrei sostituire logicamente un disco?

Se un disco si guasta o si desidera sostituirlo per qualsiasi altro motivo e si dispone di un disco non assegnato nell'array di storage, è possibile sostituire logicamente il disco guasto con quello non assegnato. Se non si dispone di un disco non assegnato, è possibile sostituirlo fisicamente.

I dati dell'unità originale vengono copiati o ricostruiti sull'unità sostitutiva.



[[where-can-i-view-the-status-of-a-drive-undergoing-reconstruction]]
== Dove è possibile visualizzare lo stato di un disco in fase di ricostruzione?

Puoi visualizzare lo stato di ricostruzione dell'unità dalla dashboard Operazioni in corso.

Dal pannello di sinistra, seleziona menu:Monitoraggio[Operazioni in corso].

A seconda del disco, la ricostruzione completa potrebbe richiedere molto tempo. Se la proprietà di un volume è cambiata, potrebbe essere eseguita una ricostruzione completa invece della ricostruzione rapida.
