---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 'Quando si crea un volume, si seleziona un carico di lavoro per personalizzare la configurazione dell"array di storage per un"applicazione specifica.' 
---
= Come funzionano i carichi di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea un volume, si seleziona un carico di lavoro per personalizzare la configurazione dell'array di storage per un'applicazione specifica.

Un workload è un oggetto storage che supporta un'applicazione. È possibile definire uno o più carichi di lavoro o istanze per applicazione. Per alcune applicazioni, il sistema configura il carico di lavoro in modo che contenga volumi con caratteristiche di volume sottostanti simili. Queste caratteristiche dei volumi sono ottimizzate in base al tipo di applicazione supportata dal carico di lavoro. Ad esempio, se si crea un carico di lavoro che supporta un'applicazione Microsoft SQL Server e successivamente si creano volumi per tale carico di lavoro, le caratteristiche del volume sottostante sono ottimizzate per supportare Microsoft SQL Server.

Durante la creazione del volume, il sistema richiede di rispondere alle domande sull'utilizzo di un carico di lavoro. Ad esempio, se si creano volumi per Microsoft Exchange, viene chiesto quante cassette postali sono necessarie, quali sono i requisiti medi di capacità delle caselle postali e quante copie del database si desidera. Il sistema utilizza queste informazioni per creare una configurazione ottimale del volume, che può essere modificata in base alle esigenze. In alternativa, è possibile saltare questo passaggio nella sequenza di creazione del volume.



== Tipi di carichi di lavoro

È possibile creare due tipi di carichi di lavoro: Specifici dell'applicazione e altri.

* *Specifico dell'applicazione*. Quando si creano volumi utilizzando un carico di lavoro specifico dell'applicazione, il sistema consiglia una configurazione del volume ottimizzata per ridurre al minimo i conflitti tra i/o del carico di lavoro dell'applicazione e altro traffico proveniente dall'istanza dell'applicazione. Le caratteristiche del volume come il tipo di i/o, le dimensioni del segmento, la proprietà del controller e la cache di lettura e scrittura sono automaticamente consigliate e ottimizzate per i carichi di lavoro creati per i seguenti tipi di applicazioni.
+
** Microsoft® SQL Server™
** Microsoft® Exchange Server™
** Applicazioni di videosorveglianza
** VMware ESXi™ (per volumi da utilizzare con il file system della macchina virtuale)
+
È possibile rivedere la configurazione del volume consigliata e modificare, aggiungere o eliminare i volumi e le caratteristiche consigliate dal sistema utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).



* *Altro* (o applicazioni senza supporto per la creazione di volumi specifici). Altri carichi di lavoro utilizzano una configurazione del volume che è necessario specificare manualmente quando si desidera creare un carico di lavoro non associato a un'applicazione specifica o se il sistema non dispone di ottimizzazione integrata per l'applicazione che si intende utilizzare sull'array di storage. Specificare manualmente la configurazione del volume utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).




== Viste delle applicazioni e dei workload

Per visualizzare applicazioni e carichi di lavoro, avviare Gestore di sistema SANtricity. Da questa interfaccia è possibile visualizzare le informazioni associate a un carico di lavoro specifico dell'applicazione in due modi diversi:

* È possibile selezionare la scheda *applicazioni e carichi di lavoro* nella sezione volumi per visualizzare i volumi dell'array di storage raggruppati per carico di lavoro e il tipo di applicazione a cui è associato il carico di lavoro.
* È possibile selezionare la scheda *applicazioni e carichi di lavoro* nel riquadro Performance per visualizzare le metriche delle performance (latenza, IOPS e MB) per gli oggetti logici. Gli oggetti sono raggruppati in base all'applicazione e al carico di lavoro associato. Raccogliendo questi dati sulle performance a intervalli regolari, è possibile stabilire misurazioni di riferimento e analizzare i trend, che possono aiutare a indagare i problemi relativi alle performance di i/O.

