---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: 'La funzionalità SSD cache è una soluzione basata su controller che memorizza nella cache i dati più utilizzati (dati "hot") su unità a stato solido (SSD) a bassa latenza per accelerare dinamicamente le prestazioni del sistema. La cache SSD viene utilizzata esclusivamente per le letture host.' 
---
= Come funziona SSD cache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzionalità SSD cache è una soluzione basata su controller che memorizza nella cache i dati più utilizzati (dati "hot") su unità a stato solido (SSD) a bassa latenza per accelerare dinamicamente le prestazioni del sistema. La cache SSD viene utilizzata esclusivamente per le letture host.

[NOTE]
====
Questa funzione non è disponibile sui sistemi storage EF600 o EF300.

====


== Cache SSD rispetto alla cache primaria

La cache SSD è una cache secondaria da utilizzare con la cache primaria nella DRAM (Dynamic Random-Access Memory) del controller.

La cache SSD funziona in modo diverso dalla cache primaria:

* Per la cache primaria, ogni operazione di i/o deve eseguire lo stage dei dati nella cache per eseguire l'operazione.
+
Nella cache primaria, i dati vengono memorizzati nella DRAM dopo la lettura da parte di un host.

* La cache SSD viene utilizzata solo se è utile inserire i dati nella cache per migliorare le prestazioni generali del sistema.
+
Nella cache SSD, i dati vengono copiati dai volumi e memorizzati su due volumi RAID interni (uno per controller) che vengono creati automaticamente quando si crea una cache SSD.



I volumi RAID interni vengono utilizzati per l'elaborazione della cache interna. Questi volumi non sono accessibili o visualizzati nell'interfaccia utente. Tuttavia, questi due volumi vengono conteggiati rispetto al numero totale di volumi consentiti nell'array di storage.



== Come viene utilizzata la cache SSD

Il caching intelligente inserisce i dati in un'unità a latenza inferiore, in modo che le risposte alle richieste future di tali dati possano avvenire molto più velocemente. Se un programma richiede dati che si trovano nella cache (chiamata "`cache Hit`"), l'unità a latenza inferiore può servire quella transazione. In caso contrario, si verifica un "`cache miss`" (errore cache) e l'accesso ai dati deve essere effettuato dal disco originale più lento. Man mano che si verificano più accessi alla cache, le performance complessive migliorano.

Quando un programma host accede ai dischi dell'array di storage, i dati vengono memorizzati nella cache SSD. Quando il programma host accede nuovamente agli stessi dati, questi vengono letti dalla cache SSD invece che dai dischi rigidi. I dati ad accesso comune vengono memorizzati nella cache SSD. L'accesso ai dischi rigidi avviene solo quando i dati non possono essere letti dalla cache SSD.

La cache SSD viene utilizzata solo quando è utile inserire i dati nella cache per migliorare le prestazioni generali del sistema.

Quando la CPU deve elaborare i dati di lettura, segue la procedura riportata di seguito:

. Controllare la cache DRAM.
. Se non viene trovato nella cache DRAM, controllare la cache SSD.
. Se non viene trovato nella cache SSD, eseguire la configurazione dal disco rigido. Se i dati sono ritenuti utili per la cache, copiarli nella cache SSD.




== Performance migliorate

La copia dei dati più accessibili (hot spot) nella cache SSD consente un funzionamento più efficiente del disco rigido, una latenza ridotta e velocità di lettura e scrittura accelerate. L'utilizzo di SSD dalle performance elevate per la cache dei dati dai volumi HDD migliora le performance di i/o e i tempi di risposta.

Semplici meccanismi di i/o dei volumi vengono utilizzati per spostare i dati da e verso la cache SSD. Dopo che i dati sono stati memorizzati nella cache e memorizzati negli SSD, le successive letture di tali dati vengono eseguite sulla cache SSD, eliminando così la necessità di accedere al volume HDD.



== SSD cache e la funzione Drive Security

Per utilizzare la cache SSD su un volume che utilizza anche Drive Security (è abilitato per la protezione), le funzionalità di protezione del disco del volume e della cache SSD devono corrispondere. Se non corrispondono, il volume non sarà abilitato alla protezione.



== Implementare la cache SSD

Per implementare la cache SSD, procedere come segue:

. Creare la cache SSD.
. Associare la cache SSD ai volumi per i quali si desidera implementare il caching in lettura SSD.


[NOTE]
====
Qualsiasi volume assegnato per l'utilizzo della cache SSD di un controller non è idoneo per un trasferimento automatico del bilanciamento del carico.

====