---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 'Quando si crea un volume, si seleziona un carico di lavoro per personalizzare la configurazione dell"array di storage per un"applicazione specifica.' 
---
= Come funzionano i carichi di lavoro nel software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea un volume, si seleziona un carico di lavoro per personalizzare la configurazione dell'array di storage per un'applicazione specifica.

Un workload è un oggetto storage che supporta un'applicazione. È possibile definire uno o più carichi di lavoro o istanze per applicazione.



== Creazione di un carico di lavoro

È necessario specificare manualmente quando si desidera creare un carico di lavoro non associato a una specifica applicazione. È inoltre necessario specificare manualmente la configurazione del volume utilizzando la pagina Aggiungi volumi.



== Viste delle applicazioni e dei workload

Per visualizzare applicazioni e carichi di lavoro, avviare Gestore di sistema SANtricity. Da questa interfaccia è possibile visualizzare le informazioni associate a un carico di lavoro specifico dell'applicazione in due modi diversi:

* È possibile selezionare la scheda *Applicazioni e carichi di lavoro* nella pagina Volumi per visualizzare i volumi dell'array di storage raggruppati per carico di lavoro e per tipo di applicazione a cui il carico di lavoro è associato.
* È possibile selezionare la scheda *Applicazioni e carichi di lavoro* nella pagina Prestazioni per visualizzare le metriche delle prestazioni (latenza, IOPS e MB) per gli oggetti logici. Gli oggetti sono raggruppati per applicazione e carico di lavoro associato. Raccogliendo questi dati sulle prestazioni a intervalli regolari, è possibile stabilire parametri di riferimento e analizzare le tendenze, il che può essere utile durante l'indagine di problemi relativi alle prestazioni di I/O.

