---
permalink: sm-storage/remove-capacity-from-a-pool-or-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, capacity, pool, ssd cache 
summary: È possibile rimuovere i dischi per ridurre la capacità di un pool o di una cache SSD esistente. 
---
= Rimuovere la capacità da un pool o da una cache SSD
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere i dischi per ridurre la capacità di un pool o di una cache SSD esistente.

Dopo aver rimosso i dischi, i dati in ciascun volume del pool o della cache SSD vengono ridistribuiti nei dischi rimanenti. I dischi rimossi non vengono assegnati e la loro capacità diventa parte della capacità libera totale dell'array di storage.

.A proposito di questa attività
Quando si rimuove la capacità, attenersi alle seguenti linee guida:

* Non è possibile rimuovere l'ultimo disco in una cache SSD senza prima eliminare la cache SSD.
* Non è possibile ridurre il numero di dischi in un pool a meno di 11 dischi.
* È possibile rimuovere un massimo di 12 dischi alla volta. Se è necessario rimuovere più di 12 dischi, ripetere la procedura.
* Non è possibile rimuovere i dischi se la capacità libera nel pool o nella cache SSD non è sufficiente per contenere i dati, quando tali dati vengono ridistribuiti ai dischi rimanenti nel pool o nella cache SSD.


.Scopri i potenziali impatti sulle performance
[%collapsible]
====
* La rimozione dei dischi da un pool o da una cache SSD potrebbe ridurre le performance dei volumi.
* La capacità di conservazione non viene consumata quando si rimuove la capacità da un pool o da una cache SSD. Tuttavia, la capacità di conservazione potrebbe diminuire in base al numero di dischi rimasti nel pool o nella cache SSD.


====
.Scopri gli impatti sui dischi sicuri
[%collapsible]
====
* Se si rimuove l'ultimo disco che non supporta la protezione, il pool viene lasciato con tutti i dischi che supportano la protezione. In questa situazione, è possibile attivare la protezione per il pool.
* Se si rimuove l'ultimo disco non compatibile con Data Assurance (da), il pool viene lasciato con tutti i dischi compatibili con da.



NOTE: Tutti i nuovi volumi creati nel pool saranno compatibili con da. Se si desidera che i volumi esistenti siano compatibili con il da, è necessario eliminare e ricreare il volume.

====
.Fasi
. Selezionare menu:Storage[Pools & Volume Groups] (Storage[Pools & Volume Groups])
. Selezionare il pool o la cache SSD, quindi fare clic su menu:More[Remove Capacity].
+
Viene visualizzata la finestra di dialogo Remove Capacity (capacità di rimozione).

. Selezionare una o più unità nell'elenco.
+
Quando si selezionano o deselezionano i dischi nell'elenco, il campo *capacità totale selezionata* si aggiorna. Questo campo mostra la capacità totale del pool o della cache SSD risultante dopo la rimozione dei dischi selezionati.

. Fare clic su *Rimuovi*, quindi confermare la rimozione delle unità.
+
La nuova capacità ridotta del pool o della cache SSD viene riflessa nella vista Pools e Volume Groups.


