---
permalink: sm-storage/rtv-modify-connection-settings-for-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, modify, connection, settings, remote, storage 
summary: 'È possibile modificare, aggiungere o eliminare le impostazioni di connessione per qualsiasi configurazione di storage remoto tramite l"opzione View/Edit Settings (Visualizza/Modifica impostazioni).' 
---
= Modificare le impostazioni di connessione per lo storage remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare, aggiungere o eliminare le impostazioni di connessione per qualsiasi configurazione di storage remoto tramite l'opzione View/Edit Settings (Visualizza/Modifica impostazioni).

.A proposito di questa attività
Le modifiche apportate alle proprietà della connessione influiscono sulle importazioni in corso. Per evitare interruzioni, apportare modifiche alle proprietà della connessione solo quando le importazioni non sono in esecuzione.

.Fasi
. Selezionare menu:Storage[Remote storage] (archiviazione remota).
. Dall'elenco, selezionare l'oggetto di storage remoto che si desidera modificare.
. Fare clic su *View/Edit Settings* (Visualizza/Modifica impostazioni).
+
Viene visualizzata la finestra di dialogo Remote Storage Settings (Impostazioni storage remoto).

. Fare clic sulla scheda *Connection Properties* (Proprietà connessione).
+
Vengono visualizzati l'indirizzo IP configurato e le impostazioni della porta per l'importazione dello storage remoto.

. Eseguire una delle seguenti operazioni:
+
** *Edit* -- fare clic su *Edit* accanto alla voce corrispondente per l'oggetto storage remoto. Inserire l'indirizzo IP e/o le informazioni sulla porta modificati nei campi.
** *Aggiungi* -- fare clic su *Aggiungi*, quindi inserire il nuovo indirizzo IP e le informazioni sulla porta nei campi forniti. Fare clic su *Aggiungi* per confermare, quindi la nuova connessione viene visualizzata nell'elenco degli oggetti di storage remoto.
** *Delete* -- selezionare la connessione desiderata dall'elenco, quindi fare clic su *Delete* (Elimina). Confermare l'operazione digitando `delete` Nel campo fornito, quindi fare clic su *Delete* (Elimina). La connessione viene rimossa dall'elenco degli oggetti di storage remoto.


. Fare clic su *Save* (Salva).
+
Le impostazioni di connessione modificate vengono applicate all'oggetto storage remoto.


