---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: 'Per avviare un"importazione dello storage da un sistema remoto a un sistema storage e-Series locale, utilizzare la procedura guidata Importa storage remoto.' 
---
= Importa storage remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per avviare un'importazione dello storage da un sistema remoto a un sistema storage e-Series locale, utilizzare la procedura guidata Importa storage remoto.

.Prima di iniziare
* Il sistema storage e-Series deve essere configurato per comunicare con il sistema storage remoto.
+
[NOTE]
====
La configurazione dell'hardware è descritta nella guida dell'utente per la funzione di storage remoto, disponibile presso il centro di documentazione e-Series e SANtricity all'indirizzo https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["Configurare l'hardware"^]e in https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Report tecnico sullo storage remoto"^].

====
* Per il sistema di storage remoto, raccogliere le seguenti informazioni:
+
** IQN iSCSI
** Indirizzi IP iSCSI
** Numero LUN del dispositivo di storage remoto (volume di origine)


* Per il sistema storage e-Series locale, creare o selezionare un volume da utilizzare per l'importazione dei dati. Vedere link:create-volumes.html["Creare volumi"]. Il volume di destinazione deve soddisfare i seguenti requisiti:
+
** Corrisponde alle dimensioni del blocco del dispositivo di storage remoto (il volume di origine).
** Ha una capacità uguale o superiore al dispositivo di storage remoto.
** Ha uno stato di ottimale ed è disponibile.




Per un elenco completo dei requisiti, vedere link:rtv-remote-storage-volume-requirements.html["Requisiti dei volumi di storage remoto"].

* *Consigliato:* eseguire il backup dei volumi sul sistema di storage remoto prima di avviare il processo di importazione.


.A proposito di questa attività
In questa attività, viene creata una mappatura tra il dispositivo di storage remoto e un volume sul sistema di storage e-Series locale. Al termine della configurazione, viene avviata l'importazione.

[NOTE]
====
Poiché molte variabili possono influire sull'operazione di importazione e sui tempi di completamento, si consiglia di eseguire prima importazioni "`test`" più piccole. Utilizzare questi test per assicurarsi che tutte le connessioni funzionino come previsto e che l'operazione di importazione venga completata in un intervallo di tempo appropriato.

====
.Fasi
. Selezionare menu:Storage[Remote storage] (archiviazione remota).
. Fare clic su *Importa storage remoto*.
+
Viene visualizzata una procedura guidata per l'importazione dello storage remoto.

. Nel *Passo 1a* del pannello Configura origine, immettere le informazioni di connessione. Se si desidera aggiungere un'altra connessione iSCSI, fare clic su *Add another IP address* (Aggiungi un altro indirizzo IP) per includere un indirizzo IP aggiuntivo per lo storage remoto. Al termine, fare clic su *Avanti*.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione | Descrizione 


 a| 
Nome
 a| 
Immettere un nome per il dispositivo di storage remoto per identificarlo nell'interfaccia di System Manager.

Un nome può includere fino a 30 caratteri e può contenere solo lettere, numeri e i seguenti caratteri speciali: Trattino basso (_), trattino (-) e il segno hash ( n.). Un nome non può contenere spazi.



 a| 
Proprietà della connessione iSCSI
 a| 
Immettere le proprietà di connessione del dispositivo di storage remoto:

** *ISCSI Qualified Name (IQN)*: Immettere l'IQN iSCSI.
** *IP Address* (Indirizzo IP): Inserire l'indirizzo IPv4.
** *Port* (porta): Immettere il numero di porta da utilizzare per le comunicazioni tra i dispositivi di origine e di destinazione. Per impostazione predefinita, il numero della porta è 3260.


|===
====
+
Dopo aver fatto clic su *Avanti*, viene visualizzato il *Passo 1b* del pannello Configura origine.

. Nel campo *LUN*, selezionare il numero LUN del dispositivo di storage remoto da utilizzare come origine, quindi fare clic su *Avanti*.
+
Viene visualizzato il pannello Configure Target (Configura destinazione) che visualizza i volumi candidati da utilizzare come destinazione per l'importazione. Alcuni volumi non vengono visualizzati nell'elenco dei candidati a causa delle dimensioni dei blocchi, della capacità o della disponibilità dei volumi.

. Dalla tabella, selezionare un volume di destinazione nel sistema storage e-Series. Se necessario, utilizzare il dispositivo di scorrimento per modificare la priorità di importazione. Fare clic su *Avanti*. Confermare l'operazione nella finestra di dialogo successiva digitando `continue`, Quindi fare clic su *continua*.
+
Se il volume di destinazione ha una capacità superiore a quella del volume di origine, tale capacità aggiuntiva non viene segnalata all'host connesso al sistema e-Series. Per utilizzare la nuova capacità, è necessario eseguire un'operazione di espansione del file system sull'host dopo il completamento dell'operazione di importazione e la disconnessione.

+
Dopo aver confermato la configurazione nella finestra di dialogo, viene visualizzato il pannello Review (Revisione).

. Dal pannello Review (Revisione), verificare che le impostazioni siano corrette, quindi fare clic su *Finish* (fine) per avviare l'importazione.
+
Viene visualizzata un'altra finestra di dialogo che chiede se si desidera avviare un'altra importazione.

. Se necessario, fare clic su *Sì* per creare un'altra importazione di storage remoto. Facendo clic su *Yes* (Sì) si torna al *Step 1a* del pannello Configure Source (Configura origine), dove è possibile selezionare la configurazione esistente o aggiungerne una nuova. Se non si desidera creare un'altra importazione, fare clic su *No* per uscire dalla finestra di dialogo.
+
Una volta avviato il processo di importazione, l'intero volume di destinazione viene sovrascritto con i dati copiati. Se l'host scrive nuovi dati nel volume di destinazione durante questo processo, tali nuovi dati vengono propagati nuovamente al dispositivo remoto (volume di origine).

. Visualizzare l'avanzamento dell'operazione nella finestra di dialogo View Operations (Visualizza operazioni) sotto il pannello Remote Storage (archiviazione remota).


.Risultati
Il tempo necessario per completare l'operazione di importazione dipende dalle dimensioni del sistema di storage remoto, dall'impostazione della priorità per l'importazione e dalla quantità di carico i/o su entrambi i sistemi storage e sui volumi associati.

Una volta completata l'importazione, il volume locale è un duplicato del dispositivo di storage remoto.

.Al termine
Quando si è pronti a interrompere la relazione tra i due volumi, selezionare *Disconnect* nell'oggetto di importazione dalla vista Operations in Progress (operazioni in corso). Una volta disconnessa la relazione, le prestazioni del volume locale tornano alla normalità e non sono più influenzate dalla connessione remota.
