---
permalink: sm-storage/rtv-manage-progress-of-remote-volume-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, imports 
summary: Una volta avviato il processo di importazione, è possibile visualizzare e intraprendere azioni in merito. 
---
= Gestire l'avanzamento delle importazioni di storage remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta avviato il processo di importazione, è possibile visualizzare e intraprendere azioni in merito.

.A proposito di questa attività
Per ogni operazione di importazione, la finestra di dialogo Operations in Progress (operazioni in corso) visualizza una percentuale di completamento e il tempo rimanente stimato. Le azioni includono la modifica della priorità di importazione, l'interruzione e la ripresa delle operazioni e la disconnessione dall'operazione.

È inoltre possibile visualizzare le operazioni in corso dalla home page (menu:Home[Mostra operazioni in corso]).

.Fasi
. Dalla pagina Storage remoto, selezionare *View Operations* (Visualizza operazioni).
+
Viene visualizzata la finestra di dialogo Operations in Progress (operazioni in corso).

. Se lo si desidera, utilizzare i collegamenti nella colonna *azioni* per interrompere e riprendere, modificare la priorità o disconnettersi da un'operazione.
+
** *Cambia priorità* -- selezionare *Cambia priorità* per modificare la priorità di elaborazione di un'operazione in corso o in sospeso. Applicare una priorità all'operazione, quindi fare clic su *OK*.
** *Stop* -- selezionare *Stop* per sospendere la copia dei dati dal dispositivo di storage remoto. La relazione tra la coppia di importazione è ancora intatta ed è possibile selezionare *Riprendi* quando si è pronti per continuare l'operazione di importazione.
** *Riprendi* -- selezionare *Riprendi* per avviare un processo interrotto o non riuscito da dove è stato interrotto. Quindi, applicare una priorità all'operazione di ripresa, quindi fare clic su *OK*. Questa operazione _non_ riavvia l'importazione dall'inizio. Se si desidera riavviare il processo dall'inizio, selezionare *Disconnect* (Disconnetti), quindi ricreare l'importazione mediante la procedura guidata di importazione dello storage remoto.
** *Disconnect* -- selezionare *Disconnect* per interrompere la relazione tra i volumi di origine e di destinazione per un'operazione di importazione interrotta, completata o non riuscita.



