---
permalink: sm-storage/thin-volume-monitoring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, thin, volume, monitoring 
summary: È possibile monitorare lo spazio dei thin volumi e generare avvisi appropriati per evitare condizioni di capacità insufficiente. 
---
= Scopri di più sul monitoraggio dei volumi sottili nel software SANtricity
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile monitorare lo spazio dei thin volumi e generare avvisi appropriati per evitare condizioni di capacità insufficiente.

Gli ambienti thin provisioning possono allocare più spazio logico di quanto abbiano di storage fisico sottostante. Puoi selezionare menu:Storage[Monitoraggio volumi thin] per monitorare quanto possono crescere i tuoi volumi thin prima che raggiungano il limite massimo di capacità allocata.

È possibile utilizzare la vista monitoraggio thin per eseguire le seguenti operazioni:

* Definire il limite che limita la capacità allocata a cui un volume sottile può espandersi automaticamente.
* Imposta la percentuale oltre la quale viene inviato un avviso (soglia di allarme superata) all'area Notifiche, accessibile tramite l'icona a forma di campana nell'angolo in alto della finestra, quando un volume thin si avvicina al limite massimo di capacità allocata.


Per aumentare la capacità di un volume sottile, aumentare la capacità riportata.

[NOTE]
====
System Manager non offre un'opzione per creare volumi thin. Se si desidera creare volumi thin, utilizzare l'interfaccia della riga di comando (CLI).

====
[NOTE]
====
I volumi sottili non sono disponibili sui sistemi storage EF80, EF50, EF600/EF600C o EF300/EF300C.

====