---
permalink: sm-storage/turn-on-locator-lights-in-a-pool-volume-group-or-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, lights, LEDs 
summary: È possibile individuare le unità per identificare fisicamente tutte le unità che comprendono un pool, un gruppo di volumi o una cache SSD selezionata. Un indicatore LED si accende su ogni disco nel pool, gruppo di volumi o cache SSD selezionato. 
---
= Attivare le luci di localizzazione in un pool, gruppo di volumi o cache SSD in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile individuare le unità per identificare fisicamente tutte le unità che comprendono un pool, un gruppo di volumi o una cache SSD selezionata. Un indicatore LED si accende su ogni disco nel pool, gruppo di volumi o cache SSD selezionato.

.Fasi
. Dal pannello di sinistra, selezionare menu:Storage[Pool e gruppi di volumi].
. Seleziona il pool, il gruppo di volumi o la Cache SSD che desideri individuare, quindi fai clic sull'icona menu:ellipsis [Attiva le spie di localizzazione].
+
Viene visualizzata una finestra di dialogo che indica che le spie dei dischi che compongono il pool, il gruppo di volumi o la cache SSD selezionati sono accese.

. Una volta individuati correttamente i dischi, fare clic su *Spegni*.

