---
permalink: sm-storage/view-and-save-performance-data-tabular.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, save, tabular, performance, 
summary: È possibile visualizzare e salvare i dati dei grafici delle prestazioni in formato tabulare. In questo modo è possibile filtrare i dati che si desidera visualizzare. 
---
= Visualizza e salva i dati sulle prestazioni tabulari in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare e salvare i dati dei grafici delle prestazioni in formato tabulare. In questo modo è possibile filtrare i dati che si desidera visualizzare.

.Fasi
. Dalla pagina Performance, fai clic su *Vai alla visualizzazione tabella*.
+
Viene visualizzata una tabella che elenca tutti i dati relativi alle prestazioni per gli oggetti selezionati.

. Utilizza *Tipi di oggetto* e *Intervallo di tempo* per selezionare i dati che vuoi visualizzare, quindi fai clic su *Aggiorna*.
. Fare clic sul pulsante *Mostra/Nascondi colonne* per selezionare le colonne da includere nella tabella.
+
È possibile fare clic su ciascuna casella di controllo per selezionare o deselezionare un elemento.

. Seleziona *Esporta in CSV* dal menu della tabella per salvare la visualizzazione tabellare in un file di valori separati da virgole (CSV).
+
A seconda delle impostazioni del browser, il file viene salvato oppure viene richiesto di scegliere un nome e una posizione per il file.

+
Il formato predefinito del nome del file è  `performanceStatistics-<storage array name>-yyyy-mm-dd_hh-mm-ss.csv`, che include il nome dello storage array e la data e l'ora in cui il file è stato esportato.


