---
permalink: sm-storage/view-performance-data-graphical.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, graphical, performance, 
summary: È possibile visualizzare i dati delle performance grafiche per oggetti logici, oggetti fisici, applicazioni e carichi di lavoro. 
---
= Visualizza i dati grafici delle prestazioni in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i dati delle performance grafiche per oggetti logici, oggetti fisici, applicazioni e carichi di lavoro.

.A proposito di questa attività
I grafici delle performance mostrano i dati storici e i dati in tempo reale attualmente acquisiti. Una linea verticale sul grafico, denominata Live Updating, distingue i dati storici dai dati in tempo reale.

*Vista dashboard*

La dashboard contiene un grafico che mostra le prestazioni a livello di array di storage. Da questa visualizzazione puoi selezionare solo alcune metriche, oppure puoi fare clic su *Visualizza dettagli prestazioni* per accedere al menu:Monitoraggio[Prestazioni] e selezionare tutte le metriche disponibili.

*Vista dettagliata*

I grafici disponibili nella pagina Prestazioni si basano sulle tue selezioni:

* *Tipi di oggetto* -- Seleziona le categorie di oggetti da includere (ad esempio, storage array, controller, pool e gruppi di volumi, applicazioni, carichi di lavoro, volumi, canali e drive).
* *Oggetti* -- Seleziona fino a cinque oggetti specifici per i tipi di oggetto selezionati.


.Fasi
. Seleziona menu:Monitoraggio[Performance].
. Utilizza *Tipi di oggetto* e *Oggetti* per selezionare i dati che vuoi visualizzare. Puoi selezionare fino a cinque oggetti; usa il campo di ricerca nell'elenco *Oggetti* per trovare nomi di oggetti o parti di nomi.
+
Non tutte le metriche sono disponibili per ogni tipo di oggetto. Gli array di storage e i controller non segnalano la latenza, solo i controller segnalano l'utilizzo della CPU e solo i controller e i canali segnalano l'headroom.

. Utilizza *Intervallo di tempo* per selezionare il periodo che vuoi visualizzare.
. Fai clic su *Aggiorna*.
. *Opzionale:* Su un singolo grafico, usa *Confronta* per sovrapporre un altro tipo di metrica per gli stessi oggetti.
. Se necessario, utilizzare le opzioni aggiuntive per visualizzare i dati delle performance.
+
.Opzioni aggiuntive
[%collapsible]
====
[cols="25h,~"]
|===
| Opzione | Descrizione 


 a| 
Intervallo di tempo
 a| 
Selezionare il periodo di tempo che si desidera visualizzare (5 minuti, 1 ora, 8 ore, 1 giorno, 7 giorni, o 30 giorni). L'impostazione predefinita è 1 ora.


NOTE: Il caricamento dei dati sulle prestazioni relativi a un intervallo di 30 giorni può richiedere diversi minuti. Non abbandonare la pagina web, non aggiornarla e non chiudere il browser mentre i dati vengono caricati.



 a| 
Dettagli dei data point
 a| 
Posizionare il cursore del mouse sul grafico per visualizzare le metriche relative a un particolare punto dati.



 a| 
Barra di scorrimento
 a| 
Utilizzare la barra di scorrimento sotto il grafico per visualizzare un intervallo di tempo precedente o successivo.



 a| 
Barra di zoom
 a| 
Sotto il grafico, trascinare le maniglie della barra di zoom per ridurre l'intervallo di tempo. Più ampia è la barra di zoom, meno granulari sono i dettagli del grafico.

Per ripristinare il grafico, selezionare una delle opzioni relative all'intervallo di tempo.



 a| 
Trascinare e rilasciare
 a| 
Sul grafico, trascinare il cursore da un punto temporale all'altro per ingrandire un intervallo di tempo.

Per ripristinare il grafico, selezionare una delle opzioni relative all'intervallo di tempo.

|===
====

