---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: Scopri in che modo i termini relativi al volume si applicano al tuo storage array. 
---
= Terminologia relativa ai volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri in che modo i termini relativi al volume si applicano al tuo storage array.



== Tutti i tipi di volume

[cols="25h,~"]
|===
| Termine | Descrizione 


 a| 
Capacità allocata
 a| 
Si utilizza la capacità allocata per creare volumi e per le operazioni dei servizi di copia.

La capacità allocata e quella riportata sono le stesse per i volumi spessi, ma sono diverse per i volumi thin. Per un volume spesso, lo spazio fisicamente allocato è uguale allo spazio che viene segnalato all'host. Per un volume thin, la capacità riportata è la capacità che viene segnalata agli host, mentre la capacità allocata è la quantità di spazio su disco attualmente allocato per la scrittura dei dati.



 a| 
Applicazione
 a| 
Un'applicazione è un software come SQL Server o Exchange. È possibile definire uno o più workload per supportare ciascuna applicazione. Per alcune applicazioni, il sistema consiglia automaticamente una configurazione del volume che ottimizzi lo storage. Caratteristiche come il tipo di i/o, la dimensione del segmento, la proprietà del controller e la cache di lettura e scrittura sono incluse nella configurazione del volume.



 a| 
Capacità
 a| 
La capacità è la quantità di dati che è possibile memorizzare in un volume.



 a| 
Proprietà del controller
 a| 
Controller ownership (proprietà del controller): Definisce il controller designato come controller principale o proprietario del volume. Un volume può avere un controller preferito (A o B) che "`possiede`" il volume. La proprietà del volume viene regolata automaticamente utilizzando la funzione di bilanciamento automatico del carico per correggere eventuali problemi di bilanciamento del carico quando i carichi di lavoro si spostano tra i controller. Il bilanciamento automatico del carico fornisce il bilanciamento automatizzato del carico di lavoro i/o e garantisce che il traffico i/o in entrata dagli host sia gestito e bilanciato dinamicamente tra entrambi i controller.



 a| 
Prefetch di lettura della cache dinamica
 a| 
Il prefetch di lettura dinamico della cache consente al controller di copiare ulteriori blocchi di dati sequenziali nella cache mentre legge i blocchi di dati da un disco alla cache. Questo caching aumenta la possibilità che le future richieste di dati possano essere compilate dalla cache. Il prefetch dinamico della lettura della cache è importante per le applicazioni multimediali che utilizzano l'i/o sequenziale La velocità e la quantità di dati precaricati nella cache vengono regolate automaticamente in base alla velocità e alle dimensioni della richiesta dell'host. L'accesso casuale non fa sì che i dati vengano precaricati nella cache. Questa funzione non si applica quando il caching in lettura è disattivato.

Per un volume thin, il prefetch dinamico di lettura della cache è sempre disattivato e non può essere modificato.



 a| 
Area di capacità libera
 a| 
Un'area di capacità libera è la capacità libera che può derivare dall'eliminazione di un volume o dal mancato utilizzo di tutta la capacità disponibile durante la creazione del volume. Quando si crea un volume in un gruppo di volumi che dispone di una o più aree di capacità libera, la capacità del volume viene limitata alla maggiore area di capacità libera del gruppo di volumi. Ad esempio, se un gruppo di volumi ha una capacità libera totale di 15 GiB e l'area di capacità libera più grande è di 10 GiB, il volume più grande che è possibile creare è di 10 GiB.

Consolidando la capacità libera, è possibile creare volumi aggiuntivi dalla quantità massima di capacità libera in un gruppo di volumi.



 a| 
Host
 a| 
Un host è un server che invia i/o a un volume su un array di storage.



 a| 
Cluster host
 a| 
Un cluster host è un gruppo di host. È possibile creare un cluster host per semplificare l'assegnazione degli stessi volumi a più host.



 a| 
Disco hot spare
 a| 
Le unità hot spare sono supportate solo con i gruppi di volumi. Un disco hot spare non contiene dati e funge da standby in caso di guasto di un disco nei volumi RAID 1, RAID 3, RAID 5 o RAID 6 contenuti in un gruppo di volumi. L'unità hot spare aggiunge un altro livello di ridondanza allo storage array.



 a| 
LUN
 a| 
Un numero di unità logica (LUN) è il numero assegnato allo spazio di indirizzi utilizzato da un host per accedere a un volume. Il volume viene presentato all'host come capacità sotto forma di LUN.

Ogni host dispone di un proprio spazio di indirizzi LUN. Pertanto, lo stesso LUN può essere utilizzato da host diversi per accedere a volumi diversi.



 a| 
Scansione dei supporti
 a| 
Una scansione dei supporti consente di rilevare gli errori dei supporti prima che vengano rilevati durante una normale lettura o scrittura sui dischi. Una scansione dei supporti viene eseguita come operazione in background ed esegue la scansione di tutti i dati e le informazioni di ridondanza in volumi utente definiti.



 a| 
Namespace
 a| 
Uno spazio dei nomi è uno storage NVM formattato per l'accesso a blocchi. È analogo a un'unità logica in SCSI, che si riferisce a un volume nell'array di storage.



 a| 
Piscina
 a| 
Un pool è un insieme di dischi raggruppati in modo logico. È possibile utilizzare un pool per creare uno o più volumi accessibili a un host. I volumi vengono creati da un pool o da un gruppo di volumi.



 a| 
Capacità del pool o del gruppo di volumi
 a| 
La capacità di pool, volume o gruppo di volumi è la capacità di un array di storage assegnato a un pool o a un gruppo di volumi. Questa capacità viene utilizzata per creare volumi e soddisfare le diverse esigenze di capacità delle operazioni dei servizi di copia e degli oggetti di storage.



 a| 
Cache di lettura
 a| 
La cache di lettura è un buffer che memorizza i dati letti dai dischi. I dati di un'operazione di lettura potrebbero essere già presenti nella cache di un'operazione precedente, eliminando così la necessità di accedere ai dischi. I dati rimangono nella cache di lettura fino a quando non vengono scaricati.



 a| 
Capacità riportata
 a| 
La capacità riportata è la capacità che viene riportata all'host e a cui l'host può accedere.

La capacità riportata e la capacità allocata sono le stesse per i volumi spessi, ma sono diverse per i volumi thin. Per un volume spesso, lo spazio fisicamente allocato è uguale allo spazio che viene segnalato all'host. Per un volume thin, la capacità riportata è la capacità che viene segnalata agli host, mentre la capacità allocata è la quantità di spazio su disco attualmente allocato per la scrittura dei dati.



 a| 
Dimensione del segmento
 a| 
Un segmento è la quantità di dati in kilobyte (KiB) memorizzati su un disco prima che l'array di storage passi al disco successivo nello stripe (gruppo RAID). La dimensione del segmento è uguale o inferiore alla capacità del gruppo di volumi. La dimensione del segmento è fissa e non può essere modificata per i pool.



 a| 
Striping
 a| 
Lo striping è un modo per memorizzare i dati nell'array di storage. Lo striping suddivide il flusso di dati in blocchi di una certa dimensione (chiamati "dimensione del blocco") e quindi scrive questi blocchi uno per uno sui dischi. Questo metodo di storage dei dati viene utilizzato per distribuire e memorizzare i dati su più dischi fisici. Lo striping è sinonimo di RAID 0 e distribuisce i dati su tutti i dischi di un gruppo RAID senza parità.



 a| 
Volume
 a| 
Un volume è un container in cui applicazioni, database e file system memorizzano i dati. Si tratta del componente logico creato per consentire all'host di accedere allo storage sull'array di storage.



 a| 
Assegnazione del volume
 a| 
L'assegnazione del volume indica la modalità di assegnazione dei LUN host a un volume.



 a| 
Nome del volume
 a| 
Il nome di un volume è una stringa di caratteri assegnata al volume al momento della creazione. È possibile accettare il nome predefinito o fornire un nome più descrittivo che indichi il tipo di dati memorizzati nel volume.



 a| 
Gruppo di volumi
 a| 
Un gruppo di volumi è un contenitore per volumi con caratteristiche condivise. Un gruppo di volumi ha una capacità e un livello RAID definiti. È possibile utilizzare un gruppo di volumi per creare uno o più volumi accessibili a un host. I volumi vengono creati da un gruppo di volumi o da un pool.



 a| 
Carico di lavoro
 a| 
Un workload è un oggetto storage che supporta un'applicazione. È possibile definire uno o più carichi di lavoro o istanze per applicazione. Per alcune applicazioni, il sistema configura il carico di lavoro in modo che contenga volumi con caratteristiche di volume sottostanti simili. Queste caratteristiche dei volumi sono ottimizzate in base al tipo di applicazione supportata dal carico di lavoro. Ad esempio, se si crea un carico di lavoro che supporta un'applicazione Microsoft SQL Server e successivamente si creano volumi per tale carico di lavoro, le caratteristiche del volume sottostante sono ottimizzate per supportare Microsoft SQL Server.



 a| 
Cache di scrittura
 a| 
La cache di scrittura è un buffer che memorizza i dati dell'host che non sono ancora stati scritti sui dischi. I dati rimangono nella cache di scrittura fino a quando non vengono scritti sui dischi. Il caching in scrittura può aumentare le performance di i/O.



 a| 
Caching in scrittura con mirroring
 a| 
Il caching in scrittura con mirroring si verifica quando i dati scritti nella memoria cache di un controller vengono scritti anche nella memoria cache dell'altro controller. Pertanto, se un controller si guasta, l'altro può completare tutte le operazioni di scrittura in sospeso. Il mirroring della cache di scrittura è disponibile solo se il caching di scrittura è attivato e sono presenti due controller. Il caching in scrittura con mirroring è l'impostazione predefinita alla creazione del volume.



 a| 
Caching in scrittura senza batterie
 a| 
Il caching in scrittura senza batterie consente di continuare il caching in scrittura anche quando le batterie sono mancanti, guaste, completamente scariche o non completamente cariche. La scelta del caching in scrittura senza batterie non è generalmente consigliata, in quanto i dati potrebbero andare persi in caso di interruzione dell'alimentazione. In genere, il caching in scrittura viene disattivato temporaneamente dal controller fino a quando le batterie non vengono caricate o non viene sostituita una batteria guasta.

|===


== Specifico per i volumi thin

[NOTE]
====
System Manager non offre un'opzione per creare volumi thin. Se si desidera creare volumi thin, utilizzare l'interfaccia della riga di comando (CLI).

====
[NOTE]
====
I thin volumi non sono disponibili sul sistema storage EF600 o EF300.

====
[cols="25h,~"]
|===
| Termine | Descrizione 


 a| 
Limite di capacità allocata
 a| 
Il limite di capacità allocata è il limite massimo per quanto può crescere la capacità fisica allocata per un volume sottile.



 a| 
Capacità scritta
 a| 
La capacità scritta è la quantità di capacità che è stata scritta dalla capacità riservata allocata per i thin volumi.



 a| 
Soglia di avviso
 a| 
È possibile impostare un avviso di soglia da emettere quando la capacità allocata per un volume thin raggiunge la percentuale di pieno (soglia di avviso).

|===