---
permalink: sm-storage/what-does-the-iops-graph-show.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, iops, graph, show 
summary: 'Il grafico IOPS visualizza le statistiche per le operazioni di input/output al secondo. Nella pagina iniziale, questo grafico visualizza le statistiche per l"array di storage. Nelle schede Logical View (Vista logica), Physical View (Vista fisica) e Applications & workload View (Vista applicazioni e carichi di lavoro) del riquadro Performance (prestazioni), questo grafico visualizza le statistiche per array di storage, volumi, gruppi di volumi, pool, applicazioni, e carichi di lavoro.' 
---
= Cosa mostra il grafico IOPS?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il grafico IOPS visualizza le statistiche per le operazioni di input/output al secondo. Nella pagina iniziale, questo grafico visualizza le statistiche per l'array di storage. Nelle schede Logical View (Vista logica), Physical View (Vista fisica) e Applications & workload View (Vista applicazioni e carichi di lavoro) del riquadro Performance (prestazioni), questo grafico visualizza le statistiche per array di storage, volumi, gruppi di volumi, pool, applicazioni, e carichi di lavoro.

IOPS è l'abbreviazione di _operazioni di input/output (i/o) al secondo_. Spostare il cursore su un punto del grafico per visualizzare i seguenti valori per quel punto temporale:

* Numero di operazioni di lettura.
* Numero di operazioni di scrittura.
* Operazioni totali di lettura e scrittura combinate.

