---
permalink: sm-storage/what-is-fde-fips-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, fde, fips, security, drives, encrypt 
summary: 'La protezione FDE/FIPS si riferisce a dischi sicuri che crittografano i dati durante la scrittura e decrittare i dati durante la lettura utilizzando una chiave di crittografia univoca. Queste unità sicure impediscono l"accesso non autorizzato ai dati su un disco che viene fisicamente rimosso dall"array di storage.' 
---
= Che cos'è la sicurezza FDE/FIPS?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La protezione FDE/FIPS si riferisce a dischi sicuri che crittografano i dati durante la scrittura e decrittare i dati durante la lettura utilizzando una chiave di crittografia univoca. Queste unità sicure impediscono l'accesso non autorizzato ai dati su un disco che viene fisicamente rimosso dall'array di storage.

Le unità compatibili con la protezione possono essere dischi con crittografia completa del disco (FDE) o dischi FIPS (Federal Information Processing Standard). I dischi FIPS sono stati sottoposti a test di certificazione.

[NOTE]
====
Per i volumi che richiedono il supporto FIPS, utilizzare solo dischi FIPS. La combinazione di dischi FIPS e FDE in un gruppo di volumi o in un pool comporterà il trattamento di tutti i dischi come dischi FDE. Inoltre, un disco FDE non può essere aggiunto o utilizzato come spare in un gruppo di volumi o pool all-FIPS.

====