---
permalink: sm-storage/when-would-i-want-to-use-the-assign-host-later-selection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, offline, volumes, use, assign, host, 
summary: 'Se si desidera accelerare il processo di creazione dei volumi, è possibile saltare la fase di assegnazione dell"host in modo che i volumi appena creati vengano inizializzati offline.' 
---
= Quando si desidera utilizzare la selezione dell'host di assegnazione in un secondo momento?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera accelerare il processo di creazione dei volumi, è possibile saltare la fase di assegnazione dell'host in modo che i volumi appena creati vengano inizializzati offline.

I volumi appena creati devono essere inizializzati. Il sistema può inizializzarli utilizzando una delle due modalità, ovvero un processo di inizializzazione in background del formato IMMEDIATAMENTE disponibile (IAF) o un processo offline.

Quando si esegue il mapping di un volume a un host, tutti i volumi di inizializzazione del gruppo vengono forzati a passare all'inizializzazione in background. Questo processo di inizializzazione in background consente l'i/o host simultaneo, che a volte può richiedere molto tempo.

Quando nessuno dei volumi in un gruppo di volumi viene mappato, viene eseguita l'inizializzazione offline. Il processo offline è molto più veloce del processo in background.
