---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.90 
summary: Nuove funzionalità di SANtricity OS. 
---
= Novità di SANtricity OS 11.90
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La seguente tabella descrive le nuove funzionalità di Gestione di sistema di SANtricity 11.9.



== Nuove funzioni della versione 11.90R2

Questa versione contiene solo modifiche minori e nessuna nuova funzionalità. Per ulteriori informazioni sulle modifiche apportate a questa versione, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP3334464["Note sulla versione di e-Series 11,90"^] .



== Nuove funzioni della versione 11.90R1

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovi modelli di sistemi storage: EF300C e EF600C
 a| 
Questa release introduce i sistemi storage All Flash NVMe EF300C e EF600C. I sistemi EF300C e EF600C sono versioni flash a elevata capacità dei sistemi storage EF300 e EF600 esistenti. I dischi SSD NVMe a elevata capacità di 30TB o 60TB dimensioni sono supportati con EF300C e EF600C. EF300C/EF600C è compatibile solo per l'utilizzo con Dynamic Disk Pool, senza supporto RAID legacy.



 a| 
Supporto per interfacce SAS 12GB su EF4000
 a| 
Il controller E4000 ora supporta 12GB schede di interfaccia host SAS.

|===


== Nuove funzionalità della versione 11.90

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovo modello di sistema storage – E4000
 a| 
Questa release introduce il sistema di storage a basso costo E4000. E4000 supporta unità da 12 e 60 GB e una singola scheda di interfaccia host (HIC) per controller. Per la versione iniziale, le schede di interfaccia host supportate includono iSCSI e Fibre Channel. In Unified Manager è possibile visualizzare e gestire i sistemi storage E4000 e altri sistemi storage e-Series.



 a| 
Maggiore capacità per Dynamic Disk Pools
 a| 
La capacità dei Dynamic Disk Pools (DDP) è stata aumentata a 12 PB ogniqualvolta la capacità di ciascuno dei singoli dischi del pool è superiore a 23 TB. Se la capacità dei singoli dischi è inferiore a 23 TB, la capacità DDP è 6 PB.



 a| 
Impostazioni di scansione dei supporti predefinite aumentate
 a| 
La velocità di scansione predefinita dei supporti è stata aumentata a 120 giorni.



 a| 
Chiave privata ora accettata per la gestione esterna delle chiavi
 a| 
Il file CSR (Certificate Signing Request) generato esternamente tramite coppie di chiavi private e pubbliche può ora essere importato tramite System Manager.



 a| 
La funzione di blocco dell'accesso è ora disponibile per i servizi Web
 a| 
Configurabile solo tramite l'API REST, è ora disponibile una nuova impostazione di blocco dell'accesso per i servizi Web incorporati e proxy.

|===