---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.0 
summary: Nuove funzionalità di SANtricity OS. 
---
= Novità in SANtricity OS 12.0
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La tabella seguente descrive le nuove funzionalità in SANtricity System Manager 12.0.



== Nuove funzionalità in Version 12.0


NOTE: La release SANtricity OS 12.0 è compatibile solo con i nuovi sistemi storage all-flash EF80 e EF50. Se si utilizza SANtricity OS 11.9 o versioni precedenti, fare riferimento a link:known-issues.html["Problemi noti"] per un elenco delle nuove funzionalità delle release precedenti.

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovi modelli di sistema storage – sistemi di storage all-flash EF80 e EF50
 a| 
Questa release introduce i sistemi di storage all-NVMe-flash EF80 e EF50. EF80 e EF50 supportano 24 unità SSD NVMe e una singola scheda di interfaccia verso gli host (HIC) per controller. Le interfacce verso gli host NVMe over Fabrics supportate includono NVMe over RoCE, NVMe over IB per EF80 e NVMe over FC per EF50. Le interfacce SCSI supportate includono Fibre Channel.

Gli SSD NVMe ad alta capacità da 30TB o 60TB sono supportati anche con EF80 ed EF30. EF80 ed EF30 sono compatibili solo per l'uso con Dynamic Disk Pool, senza supporto RAID legacy.



 a| 
Nuova interfaccia utente per SANtricity System Manager
 a| 
Per i nuovi controller EF80 e EF50, l'interfaccia utente di SANtricity System Manager è stata riprogettata per offrire un aspetto e un'esperienza più moderni. La nuova interfaccia include una navigazione tramite pannello a sinistra e una maggiore facilità d'uso per semplificare le attività di gestione.


NOTE: La nuova interfaccia utente è attualmente disponibile solo per i sistemi storage EF80 e EF50 con la release SANtricity 12.0. Se si utilizza SANtricity 11.9 o versioni precedenti, fare riferimento a link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["Gestore di sistema di SANtricity 11.9"] per le istruzioni sull'utilizzo dell'interfaccia utente precedente.



 a| 
I nomi alternativi del soggetto (SAN) per il certificato server ora consentono solo lettere, cifre e trattini
 a| 
Quando si crea o si modifica un certificato server in SANtricity System Manager o Unified Manager, il campo Subject Alternative Names (SANs) ora consente solo lettere, cifre e trattini. Questa modifica migliora la sicurezza e garantisce la compatibilità con gli standard di settore per i certificati SSL/TLS.



 a| 
La dimensione dei segmenti dei Dynamic Disk Pools ora è impostata di default a 32K per i sistemi basati su SSD e NVMe
 a| 
Per i Dynamic Disk Pools su sistemi basati su SSD e NVMe, la dimensione predefinita del segmento è stata modificata a 32K. In precedenza, la dimensione predefinita del segmento dei Dynamic Disk Pools era fissata a 128K per questi sistemi. Questa modifica ottimizza le prestazioni per i carichi di lavoro che coinvolgono un mix di operazioni di I/O di piccole e grandi dimensioni.



 a| 
L'editor di script è ora disponibile in SANtricity System Manager
 a| 
È ora disponibile un nuovo editor di script all'interno di SANtricity System Manager. L'editor di script consente di creare o modificare un file di script, salvare un file di script sul disco locale della stazione di gestione dello storage o caricare un file di script dal disco. L'editor di script offre funzionalità di controllo della sintassi ed esecuzione dei comandi per la gestione del sistema storage. Per ulteriori informazioni, vedere link:sm-support/use-script-editor.html["Utilizzo dell'editor di script"^].

|===