---
permalink: sm-mirroring/asynchronous-mirroring-why-dont-i-see-all-my-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, volumes 
summary: Quando si seleziona un volume primario per una coppia mirrorata, un elenco mostra tutti i volumi idonei. 
---
= Mirroring asincrono - perché non vedo tutti i volumi?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si seleziona un volume primario per una coppia mirrorata, un elenco mostra tutti i volumi idonei.

I volumi non idonei all'utilizzo non vengono visualizzati nell'elenco. I volumi potrebbero non essere idonei per uno dei seguenti motivi:

* Il volume non è ottimale.
* Il volume sta già partecipando a una relazione di mirroring.
* Per i volumi thin, è necessario attivare l'espansione automatica.



NOTE: Per i controller EF600 e EF300, i volumi primari e secondari di una coppia asincrona con mirroring devono corrispondere allo stesso protocollo, livello di vassoio, dimensione del segmento, tipo di sicurezza e livello RAID. Le coppie mirrorate asincrone non idonee non vengono visualizzate nell'elenco dei volumi disponibili.
