---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: È necessario configurare lo storage array con una password di amministratore per proteggerlo da accessi non autorizzati. 
---
= Gestire la protezione tramite password in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare lo storage array con password per proteggerlo da accessi non autorizzati.



== Impostare e modificare le password

Quando si avvia System Manager per la prima volta, viene richiesto di impostare una password di amministratore. Qualsiasi utente in possesso della password admin può apportare modifiche alla configurazione dello storage array, ad esempio l'aggiunta, la modifica o la rimozione di oggetti o impostazioni. Per impostare la password admin durante l'avvio iniziale, vedere link:../san-getstarted/access-sam.html["Accedere a System Manager"].

Per motivi di sicurezza, è possibile tentare di inserire una password solo cinque volte prima che lo storage array entri in uno stato di "blocco". In questo stato, lo storage array rifiuterà i successivi tentativi di password. Prima di inserire nuovamente una password, attendere 10 minuti per ripristinare lo stato "normale" dello storage array.

Oltre alla password di amministratore, lo storage array include profili utente predefiniti con uno o più ruoli mappati. Per ulteriori informazioni, vedere link:../sm-settings/permissions-for-mapped-roles.html["Autorizzazioni per i ruoli mappati"]. I profili utente e le mappature non possono essere modificati. È possibile modificare solo le password. Se si desidera modificare la password admin o altre password utente, vedere link:../sm-settings/change-passwords.html["Modificare le password"].



== Immettere nuovamente le password dopo il timeout della sessione

Il sistema richiede la password una sola volta durante una singola sessione di gestione. Tuttavia, una sessione scade dopo 30 minuti di inattività, dopodiché è necessario immettere nuovamente la password. Se un altro utente che gestisce lo stesso array di storage da un altro client di gestione modifica la password durante la sessione, viene richiesta una password la volta successiva che si tenta di eseguire un'operazione di configurazione o un'operazione di visualizzazione.

È possibile regolare il timeout della sessione o disattivarlo del tutto. Vedere link:../sm-settings/manage-session-timeouts-sam.html["Gestire i timeout delle sessioni"].



== Rimuovere i dischi o la protezione tramite password

Se si rimuovono unità protette da password o si desidera disattivare la protezione tramite password, tenere presente quanto segue:

* *Se si rimuovono dischi con password di protezione*, la password viene memorizzata in un'area riservata di ciascun disco dell'array di storage. Se si rimuovono tutte le unità da un array di storage, la password non funzionerà più. Per correggere questa condizione, reinstallare uno dei dischi originali nell'array di storage.
* *Se si desidera rimuovere la protezione tramite password* -- se non si desidera più avere comandi protetti da password, inserire la password corrente dell'amministratore e lasciare vuote le caselle di testo della nuova password.


[CAUTION]
====
L'esecuzione di comandi di configurazione su un array di storage può causare gravi danni, inclusa la perdita di dati. Per questo motivo, è necessario impostare sempre una password di amministratore per lo storage array. Utilizzare una password di amministratore lunga con almeno 15 caratteri alfanumerici per aumentare la protezione.

====