---
permalink: sm-interface/home-page.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, home page 
summary: La Dashboard fornisce una panoramica riassuntiva per la gestione quotidiana del tuo array di storage. Quando accedi a System Manager, la Dashboard è la prima schermata visualizzata. 
---
= Scopri la dashboard di SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La Dashboard fornisce una panoramica riassuntiva per la gestione quotidiana del tuo array di storage. Quando accedi a SANtricity System Manager, la Dashboard è la prima schermata visualizzata.

La vista dalla dashboard comprende tre aree di riepilogo che contengono informazioni chiave sullo stato e l'integrità del tuo storage array. Puoi trovare ulteriori informazioni nell'area di riepilogo.

* *Prestazioni*
+
L'area Performance (prestazioni) consente di confrontare e confrontare l'utilizzo delle risorse nel tempo. È possibile visualizzare le metriche delle performance di uno storage array per i tempi di risposta (IOPS), le velocità di trasferimento (MiB/s) e la quantità di capacità di elaborazione utilizzata (CPU).

* *Capacità*
+
L'area Capacity (capacità) visualizza una vista a grafico della capacità allocata, della capacità di storage libera e della capacità di storage non assegnata nell'array di storage.

* *Gerarchia dello storage*
+
L'area Storage Hierarchy (gerarchia di storage) offre una vista organizzata dei vari componenti hardware e oggetti storage gestiti dallo storage array. Fare clic sulla freccia a discesa per eseguire una determinata azione sul componente hardware o sull'oggetto di storage.


