---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 'Si naviga nell"interfaccia principale per accedere alle funzioni e alle attività di System Manager.' 
---
= Scopri di più sull'interfaccia di SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager è un'interfaccia basata sul web che ti consente di gestire uno storage array in una singola vista.



[[dashboard]]
== Pannello di controllo

La Dashboard fornisce una panoramica riassuntiva per la gestione quotidiana del tuo array di storage. Quando accedi a System Manager, la Dashboard è la prima schermata visualizzata.

La vista dalla dashboard comprende tre aree di riepilogo che contengono informazioni chiave sullo stato e l'integrità del tuo storage array. Puoi trovare ulteriori informazioni nell'area di riepilogo.

[cols="25h,~"]
|===
| Area | Descrizione 


 a| 
Performance
 a| 
L'area Performance (prestazioni) consente di confrontare e confrontare l'utilizzo delle risorse nel tempo. È possibile visualizzare le metriche delle performance di uno storage array per i tempi di risposta (IOPS), le velocità di trasferimento (MiB/s) e la quantità di capacità di elaborazione utilizzata (CPU).



 a| 
Capacità
 a| 
L'area Capacity (capacità) visualizza una vista a grafico della capacità allocata, della capacità di storage libera e della capacità di storage non assegnata nell'array di storage.



 a| 
Gerarchia dello storage
 a| 
L'area Storage Hierarchy (gerarchia di storage) offre una vista organizzata dei vari componenti hardware e oggetti storage gestiti dallo storage array. Fare clic sulla freccia a discesa per eseguire una determinata azione sul componente hardware o sull'oggetto di storage.

|===


[[notifications-area]]
== Area notifiche

L'area Notifiche è accessibile tramite l'icona a forma di campana nell'angolo in alto della finestra. L'area Notifiche visualizza notifiche relative ai problemi che indicano lo stato dell'array di storage e dei suoi componenti. Inoltre, questa sezione visualizza avvisi automatici che possono aiutare a risolvere i problemi prima che influiscano su altre aree dell'ambiente di storage.



[[interface-settings]]
== Impostazioni dell'interfaccia

È possibile modificare le preferenze di visualizzazione e altre impostazioni dall'interfaccia principale.



[[user-logins-and-passwords]]
== Login e password degli utenti

L'utente attualmente connesso al sistema viene visualizzato nelle impostazioni utente.

Per ulteriori informazioni su utenti e password, consulta:

* link:administrator-password-protection.html["Impostare la protezione della password amministratore"]
* link:../sm-settings/change-passwords.html["Modificare le password"]

