---
permalink: sm-interface/set-default-time-frame-for-performance-graphs.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, time, graphs 
summary: 'È possibile modificare l"intervallo di tempo predefinito mostrato dai grafici delle prestazioni.' 
---
= Imposta l'intervallo di tempo predefinito per i grafici delle prestazioni in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare l'intervallo di tempo predefinito mostrato dai grafici delle prestazioni.

.A proposito di questa attività
I grafici delle prestazioni visualizzati nella Dashboard e nella pagina Prestazioni inizialmente mostrano un intervallo di tempo di 1 ora. Le preferenze vengono memorizzate nella memoria locale del browser, così ogni utente può avere le proprie impostazioni.

.Fasi
. Fai clic sull'icona *User Settings* nell'angolo in alto a destra della finestra.
. Nell'elenco a discesa Default performance graphs time range to show, seleziona *5 minuti*, *1 ora*, *8 ore*, *1 giorno* o *7 giorni* e conferma che desideri eseguire l'operazione.

