---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: 'L"accesso remoto consente agli utenti esterni alla rete locale di avviare una sessione SSH e modificare le impostazioni del controller.' 
---
= Configurare l'accesso remoto (SSH) in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Attivando l'accesso remoto, gli utenti esterni alla rete locale possono avviare una sessione SSH e accedere alle impostazioni del controller.

Per SANtricity versione 11.74 e successive, è anche possibile configurare l'autorizzazione multifattore (MFA) richiedendo agli utenti di inserire una chiave SSH e/o una password SSH. Per le versioni 11.73 e precedenti di SANtricity, questa funzione _non_ include un'opzione per l'autorizzazione a più fattori con chiavi SSH e password.

[CAUTION]
====
*Rischi per la sicurezza* -- per motivi di sicurezza, solo il personale di supporto tecnico deve utilizzare la funzione di accesso remoto.

====
.Fasi
. Dal pannello di sinistra, selezionare menu:Hardware[Controllers and components].
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller per il quale si desidera configurare l'accesso remoto.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configura accesso remoto (SSH)*. (Per SANtricity versione 11.73 e precedenti, questa voce di menu è *Modifica accesso remoto*.)
+
Si apre la pagina Configura accesso remoto (SSH).

. Selezionare la casella di controllo *Enable remote login* (attiva accesso remoto).
+
Questa impostazione fornisce l'accesso remoto con tre opzioni per l'autorizzazione:

+
** *Solo password*. Per questa opzione, fare clic su *Save* (Salva). Se si dispone di un sistema duplex, è possibile attivare l'accesso remoto sul secondo controller seguendo la procedura precedente.
** *Chiave SSH o password*. Per questa opzione, passare alla fase successiva.
** *Sia password che chiave SSH*. Per questa opzione, selezionare la casella di controllo *Richiedi chiave pubblica autorizzata e password per l'accesso remoto* e passare alla fase successiva.


. Compila il campo *Authorized public keys*. Questo campo contiene un elenco di chiavi pubbliche autorizzate, nel formato del file *authorized_keys* di OpenSSH.
+
Quando compili il campo *Chiavi pubbliche autorizzate*, tieni presente le seguenti linee guida:

+
** Il campo *Chiavi pubbliche autorizzate* si applica a entrambi i controller e devi configurarlo solo sul primo controller.
** Il file *authized_keys* deve contenere una sola chiave per riga. Le righe che iniziano con n. e vuote vengono ignorate. Per ulteriori informazioni sul formato del file, vedere link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["Configurazione delle chiavi autorizzate per OpenSSH"^].
** Un file *authized_keys* dovrebbe avere un aspetto simile al seguente esempio:
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. Al termine, fare clic su *Save* (Salva).
. Per i sistemi duplex, è possibile attivare l'accesso remoto sul secondo controller seguendo la procedura descritta in precedenza. Se si sta configurando l'opzione sia per una password che per una chiave SSH, assicurarsi di selezionare nuovamente la casella di controllo *Richiedi chiave pubblica autorizzata e password per l'accesso remoto*.
. Dopo che il supporto tecnico ha finito di risolvere i problemi, puoi disabilitare l'accesso remoto tornando alla pagina Configura accesso remoto (SSH) e deselezionando la casella di controllo *Abilita accesso remoto*. Se l'accesso remoto è abilitato su un secondo controller, si apre una finestra di dialogo di conferma che ti permette di disabilitare l'accesso remoto anche su quest'ultimo.
+
La disattivazione dell'accesso remoto termina tutte le sessioni SSH correnti e rifiuta le nuove richieste di accesso.


