---
permalink: sm-hardware/configure-iscsi-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, ports, 
summary: Se il controller include una connessione host iSCSI, è possibile configurare le impostazioni della porta iSCSI dalla pagina hardware. 
---
= Configurare le porte iSCSI in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una connessione host iSCSI, è possibile configurare le impostazioni della porta iSCSI dalla pagina hardware.

.Prima di iniziare
* Il controller deve includere porte iSCSI; in caso contrario, le impostazioni iSCSI non sono disponibili.
* È necessario conoscere la velocità di rete (la velocità di trasferimento dei dati tra le porte e l'host).


[NOTE]
====
Le impostazioni e le funzioni iSCSI vengono visualizzate solo se lo storage array supporta iSCSI.

====
.Fasi
. Selezionare *hardware*.
. Se l'immagine mostra le unità, fare clic sulla scheda *Controller e componenti*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con le porte iSCSI che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configure iSCSI ports* (Configura porte iSCSI).
+
[NOTE]
====
L'opzione *Configure iSCSI ports* (Configura porte iSCSI) viene visualizzata solo se System Manager rileva le porte iSCSI sul controller.

====
+
Viene visualizzata la finestra di dialogo Configure iSCSI Ports (Configura porte iSCSI).

. Nell'elenco a discesa, selezionare la porta che si desidera configurare, quindi fare clic su *Avanti*.
. Selezionare le impostazioni della porta di configurazione, quindi fare clic su *Avanti*.
+
Per visualizzare tutte le impostazioni della porta, fare clic sul collegamento *Mostra altre impostazioni della porta* a destra della finestra di dialogo.

+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione della porta | Descrizione 


 a| 
Velocità della porta ethernet configurata (visualizzata solo per alcuni tipi di schede di interfaccia host)
 a| 
Selezionare la velocità che corrisponde alla velocità del modulo SFP sulla porta.



 a| 
Modalità FEC (Forward Error Correction) (visualizzata solo per alcuni tipi di schede di interfaccia host)
 a| 
Se si desidera, selezionare una delle modalità FEC per la porta host specificata.


NOTE: La modalità Reed Solomon non supporta la velocità della porta di 25 Gbps.



 a| 
Attiva IPv4 / attiva IPv6
 a| 
Selezionare una o entrambe le opzioni per abilitare il supporto per le reti IPv4 e IPv6.


NOTE: Se si desidera disattivare l'accesso alla porta, deselezionare entrambe le caselle di controllo.



 a| 
Porta TCP in ascolto (disponibile facendo clic su *Mostra altre impostazioni della porta*).
 a| 
Se necessario, inserire un nuovo numero di porta.

La porta di ascolto è il numero di porta TCP utilizzato dal controller per rilevare gli accessi iSCSI dagli iniziatori iSCSI host. La porta di ascolto predefinita è 3260. Immettere 3260 o un valore compreso tra 49152 e 65535.



 a| 
Dimensione MTU (disponibile facendo clic su *Mostra altre impostazioni della porta*).
 a| 
Se necessario, inserire una nuova dimensione in byte per l'unità di trasmissione massima (MTU).

La dimensione massima predefinita dell'unità di trasmissione (MTU) è di 1500 byte per frame. Immettere un valore compreso tra 1500 e 9000.



 a| 
Abilitare le risposte PING ICMP
 a| 
Selezionare questa opzione per attivare il protocollo ICMP (Internet Control message Protocol). I sistemi operativi dei computer collegati in rete utilizzano questo protocollo per inviare messaggi. Questi messaggi ICMP determinano se un host è raggiungibile e quanto tempo occorre per ottenere i pacchetti da e verso tale host.

|===
====
+
Se si seleziona *Enable IPv4* (attiva IPv4), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv4. Se si seleziona *Enable IPv6* (attiva IPv6*), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv6. Se sono state selezionate entrambe le opzioni, viene visualizzata prima la finestra di dialogo per le impostazioni IPv4, quindi dopo aver fatto clic su *Avanti*, viene visualizzata la finestra di dialogo per le impostazioni IPv6.

. Configurare le impostazioni IPv4 e/o IPv6, automaticamente o manualmente. Per visualizzare tutte le impostazioni delle porte, fare clic sul collegamento *Mostra altre impostazioni* a destra della finestra di dialogo.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Impostazione della porta | Descrizione 


 a| 
Ottenere automaticamente la configurazione
 a| 
Selezionare questa opzione per ottenere la configurazione automaticamente.



 a| 
Specificare manualmente la configurazione statica
 a| 
Selezionare questa opzione, quindi inserire un indirizzo statico nei campi. (Se lo si desidera, è possibile tagliare e incollare gli indirizzi nei campi). Per IPv4, includere la subnet mask di rete e il gateway. Per IPv6, includere l'indirizzo IP instradabile e l'indirizzo IP del router.



 a| 
Abilitare il supporto VLAN (disponibile facendo clic su *Mostra altre impostazioni*).
 a| 
Selezionare questa opzione per attivare una VLAN e inserire il relativo ID. Una VLAN è una rete logica che si comporta come se fosse fisicamente separata da altre LAN (Local Area Network) fisiche e virtuali supportate dagli stessi switch, dagli stessi router o da entrambi.



 a| 
Abilitare la priorità ethernet (disponibile facendo clic su *Mostra altre impostazioni*).
 a| 
Selezionare questa opzione per attivare il parametro che determina la priorità di accesso alla rete. Utilizzare il dispositivo di scorrimento per selezionare una priorità compresa tra 1 (più bassa) e 7 (più alta).

In un ambiente LAN (Local Area Network) condiviso, ad esempio Ethernet, molte stazioni potrebbero entrare in contatto per l'accesso alla rete. L'accesso avviene in base all'ordine di arrivo e all'ordine di arrivo. Due stazioni potrebbero tentare di accedere alla rete contemporaneamente, causando la disattivazione di entrambe le stazioni e l'attesa prima di riprovare. Questo processo è ridotto al minimo per Ethernet commutata, in cui una sola stazione è collegata a una porta dello switch.

|===
====
. Fare clic su *fine*.

