---
permalink: sm-hardware/configure-iser-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iser, infiniband, ports, 
summary: 'Se il controller include una porta iSER su InfiniBand, è possibile configurare la connessione di rete all"host.' 
---
= Configurare iSER su porte InfiniBand
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una porta iSER su InfiniBand, è possibile configurare la connessione di rete all'host.

.Prima di iniziare
* Il controller deve includere una porta iSER su InfiniBand; in caso contrario, le impostazioni iSER su InfiniBand non sono disponibili in System Manager.
* È necessario conoscere l'indirizzo IP della connessione host.


.Fasi
. Selezionare *hardware*.
. Se la figura mostra i dischi, fare clic su *Mostra retro dello shelf*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con la porta iSER su InfiniBand che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configura iSER su porte InfiniBand*.
+
Viene visualizzata la finestra di dialogo Configura porte iSER su InfiniBand.

. Nell'elenco a discesa, selezionare la porta HIC che si desidera configurare, quindi immettere l'indirizzo IP dell'host.
. Fare clic su *Configura*.
. Completare la configurazione, quindi reimpostare iSER sulla porta InfiniBand facendo clic su *Sì*.

