---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: Il controller include una porta Ethernet utilizzata per la gestione del sistema. Se necessario, è possibile modificarne i parametri di trasmissione e gli indirizzi IP. 
---
= Configurare la porta di gestione
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il controller include una porta Ethernet utilizzata per la gestione del sistema. Se necessario, è possibile modificarne i parametri di trasmissione e gli indirizzi IP.

.A proposito di questa attività
Durante questa procedura, selezionare la porta 1, quindi determinare la velocità e il metodo di indirizzamento della porta. La porta 1 si connette alla rete in cui il client di gestione può accedere al controller e a System Manager.

[NOTE]
====
Non utilizzare la porta 2 su entrambi i controller. La porta 2 è riservata al supporto tecnico.

====
.Fasi
. Selezionare *hardware*.
. Se la figura mostra i dischi, fare clic su *Mostra retro dello shelf*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con la porta di gestione che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configura porte di gestione*.
+
Viene visualizzata la finestra di dialogo Configura porte di gestione.

. Verificare che sia visualizzata la porta 1, quindi fare clic su *Avanti*.
. Selezionare le impostazioni della porta di configurazione, quindi fare clic su *Avanti*.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrizione 


 a| 
Velocità e modalità duplex
 a| 
Mantenere l'impostazione negoziazione automatica se si desidera che System Manager determini i parametri di trasmissione tra lo storage array e la rete; in alternativa, se si conosce la velocità e la modalità della rete, selezionare i parametri dall'elenco a discesa. Nell'elenco vengono visualizzate solo le combinazioni valide di velocità e duplex.



 a| 
Attiva IPv4 / attiva IPv6
 a| 
Selezionare una o entrambe le opzioni per abilitare il supporto per le reti IPv4 e IPv6.

|===
====
+
Se si seleziona *Enable IPv4* (attiva IPv4), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv4. Se si seleziona *Enable IPv6* (attiva IPv6*), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv6. Se si selezionano entrambe le opzioni, viene visualizzata prima la finestra di dialogo per le impostazioni IPv4, quindi dopo aver fatto clic su *Avanti*, viene visualizzata la finestra di dialogo per le impostazioni IPv6.

. Configurare le impostazioni IPv4 e/o IPv6, automaticamente o manualmente.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrizione 


 a| 
Ottenere automaticamente la configurazione dal server DHCP
 a| 
Selezionare questa opzione per ottenere la configurazione automaticamente.



 a| 
Specificare manualmente la configurazione statica
 a| 
Selezionare questa opzione, quindi inserire l'indirizzo IP del controller. (Se lo si desidera, è possibile tagliare e incollare gli indirizzi nei campi). Per IPv4, includere la subnet mask di rete e il gateway. Per IPv6, includere l'indirizzo IP instradabile e l'indirizzo IP del router.


NOTE: Se si modifica la configurazione dell'indirizzo IP, si perde il percorso di gestione dello storage array. Se si utilizza Gestione unificata di SANtricity per gestire gli array in rete a livello globale, aprire l'interfaccia utente e accedere al menu:Gestisci[Scopri]. Se si utilizza Gestione storage SANtricity, è necessario rimuovere il dispositivo dalla finestra Gestione aziendale, aggiungerlo nuovamente all'EMW selezionando menu:Modifica[Aggiungi array storage], quindi inserire il nuovo indirizzo IP.

|===
====
. Fare clic su *fine*.


.Risultati
La configurazione della porta di gestione viene visualizzata nelle impostazioni del controller, scheda Management Ports (Porte di gestione).
