---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sugli scaffali di stoccaggio per SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Che cos'è la protezione contro la perdita di shelf e la perdita di cassetto?

La protezione contro le perdite di shelf e la protezione contro le perdite di cassetto sono attributi di pool e gruppi di volumi che consentono di mantenere l'accesso ai dati in caso di guasto di un singolo shelf o cassetto.



=== Protezione contro la perdita di shelf

Uno shelf è l'enclosure che contiene i dischi o i dischi e il controller. La protezione contro la perdita di shelf garantisce l'accessibilità ai dati sui volumi di un pool o di un gruppo di volumi se si verifica una perdita totale di comunicazione con un singolo shelf di dischi. Un esempio di perdita totale di comunicazione potrebbe essere la perdita di alimentazione dello shelf di dischi o il guasto di entrambi i moduli i/o (IOM).

[NOTE]
====
La protezione contro la perdita di shelf non è garantita se un disco si è già guastato nel pool o nel gruppo di volumi. In questa situazione, la perdita dell'accesso a uno shelf di dischi e, di conseguenza, a un altro disco nel pool o nel gruppo di volumi causa la perdita di dati.

====
I criteri per la protezione dalla perdita di shelf dipendono dal metodo di protezione, come descritto nella tabella seguente:

[cols="1a,1a,1a"]
|===
| Livello | Criteri per la protezione contro la perdita di shelf | Numero minimo di shelf richiesti 


 a| 
Piscina
 a| 
Il pool deve includere dischi di almeno cinque shelf e deve essere presente un numero uguale di dischi in ogni shelf. La protezione contro la perdita di shelf non è applicabile agli shelf ad alta capacità; se il sistema contiene shelf ad alta capacità, fare riferimento alla protezione contro la perdita di cassetto.
 a| 
5



 a| 
RAID 6
 a| 
Il gruppo di volumi non contiene più di due dischi in un singolo shelf.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Ogni disco del gruppo di volumi si trova in uno shelf separato.
 a| 
3



 a| 
RAID 1
 a| 
Ogni disco di una coppia RAID 1 deve essere collocato in uno shelf separato.
 a| 
2



 a| 
RAID 0
 a| 
Impossibile ottenere la protezione contro la perdita di shelf.
 a| 
Non applicabile

|===


=== Protezione in caso di perdita del cassetto

Un cassetto è uno dei compartimenti di uno shelf che si tira per accedere ai dischi. Solo gli scaffali ad alta capacità dispongono di cassetti. La protezione contro la perdita dei cassetti garantisce l'accessibilità ai dati sui volumi di un pool o di un gruppo di volumi se si verifica una perdita totale di comunicazione con un singolo cassetto. Un esempio di perdita totale di comunicazione potrebbe essere la perdita di alimentazione del cassetto o il guasto di un componente interno del cassetto.

[NOTE]
====
La protezione contro la perdita di cassetto non è garantita se un disco si è già guastato nel pool o nel gruppo di volumi. In questa situazione, la perdita dell'accesso a un cassetto (e di conseguenza a un altro disco nel pool o nel gruppo di volumi) causa la perdita di dati.

====
I criteri per la protezione dalle perdite di cassetto dipendono dal metodo di protezione, come descritto nella tabella seguente:

[cols="1a,1a,1a"]
|===
| Livello | Criteri per la protezione contro le perdite di cassetto | Numero minimo di cassetti richiesti 


 a| 
Piscina
 a| 
I candidati al pool devono includere unità di tutti i cassetti e deve essere presente un numero uguale di unità in ciascun cassetto.

Il pool deve includere dischi di almeno cinque cassetti e deve essere presente un numero uguale di dischi in ciascun cassetto.

Uno shelf da 60 dischi può ottenere la protezione contro la perdita di cassetto quando il pool contiene 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 dischi. È possibile aggiungere incrementi in multipli di 5 al pool dopo la creazione iniziale.
 a| 
5



 a| 
RAID 6
 a| 
Il gruppo di volumi non contiene più di due dischi in un singolo cassetto.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Ciascuna unità del gruppo di volumi si trova in un cassetto separato.
 a| 
3



 a| 
RAID 1
 a| 
Ogni disco di una coppia mirrorata deve essere collocato in un cassetto separato.
 a| 
2



 a| 
RAID 0
 a| 
Impossibile ottenere la protezione perdita cassetto.
 a| 
Non applicabile

|===


== Quali sono i cicli di apprendimento della batteria?

Un ciclo di apprendimento è un ciclo automatico per la calibrazione dell'indicatore della batteria Smart.

Un ciclo di apprendimento è costituito da queste fasi:

* Scaricamento controllato della batteria
* Periodo di riposo
* Caricare


Le batterie vengono scaricate a una soglia prestabilita. Durante questa fase, l'indicatore della batteria viene calibrato.

Un ciclo di apprendimento richiede questi parametri:

* Batterie completamente cariche
* Nessuna batteria surriscaldata


I cicli di apprendimento per i sistemi di controller duplex si verificano contemporaneamente. Per i controller con alimentazione di backup da più di una batteria o un set di celle della batteria, i cicli di apprendimento si verificano in sequenza.

I cicli di apprendimento sono programmati per l'avvio automatico a intervalli regolari, alla stessa ora e nello stesso giorno della settimana. L'intervallo tra i cicli viene descritto in settimane.

[NOTE]
====
Il completamento di un ciclo di apprendimento potrebbe richiedere diverse ore.

====