---
permalink: sm-hardware/show-or-hide-component-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, show, hide, component, status, 
summary: È possibile visualizzare le descrizioni dello stato di dischi, controller, ventole e alimentatori. 
---
= Mostra o nascondi lo stato del componente in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le descrizioni dello stato di dischi, controller, ventole e alimentatori.

.Fasi
. Nel pannello di sinistra, seleziona menu:Hardware[Drives] oppure menu:Hardware[Controllers and components], a seconda dei componenti che vuoi vedere.
. Per visualizzare o nascondere le descrizioni dello stato a comparsa:
+
** Se si desidera visualizzare una descrizione a comparsa delle icone di stato, fare clic su *Mostra dettagli icona di stato* in alto a destra nella vista dello shelf (selezionare la casella di controllo).
** Per nascondere le descrizioni a comparsa, fare nuovamente clic su *Mostra dettagli icona stato* (deselezionare la casella di controllo).


. Se si desidera visualizzare i dettagli completi dello stato, selezionare il componente nella vista shelf, quindi selezionare *View settings* (Visualizza impostazioni).

