---
permalink: sm-hardware/turn-on-drive-locator-light.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, turn, drive, locator, light, LEDs 
summary: 'Dalla pagina hardware, è possibile accendere la spia di localizzazione per individuare la posizione fisica di un"unità nell"array di storage.' 
---
= Accendere una spia di localizzazione dell'unità in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina hardware, è possibile accendere la spia di localizzazione per individuare la posizione fisica di un'unità nell'array di storage.

.A proposito di questa attività
È possibile individuare singoli dischi o più dischi visualizzati nella pagina hardware.

.Fasi
. Dal pannello di sinistra, seleziona menu:Hardware[Drives].
. Per individuare una o più unità, effettuare una delle seguenti operazioni:
+
** *Unità singola* -- Dalla rappresentazione grafica dello scaffale, individua l'unità che desideri posizionare fisicamente nell'array. Fai clic sull'unità per visualizzare il relativo menu contestuale, quindi seleziona *Attiva la spia di localizzazione*.
+
La spia di localizzazione del disco si accende. Una volta individuato il disco, tornare alla finestra di dialogo e selezionare *Spegni*.

** *Unità multiple* -- Nel campo filtro, seleziona un tipo di unità fisica e un tipo di unità logica. Il numero di unità che corrispondono ai tuoi criteri viene mostrato all'estrema destra del campo. Poi, fai clic su *attiva spie di localizzazione*. Quando hai individuato fisicamente le unità, torna alla finestra di dialogo e seleziona *Disattiva*.



