---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: 'Se si inseriscono una o più unità NVMe o FIPS bloccate in un array di storage, è possibile sbloccare i dati dell"unità aggiungendo il file della chiave di sicurezza associato alle unità. Se non si dispone di una chiave di sicurezza, è possibile eseguire un ripristino su ciascuna unità bloccata inserendo il proprio ID di sicurezza fisico (PSID) per ripristinare i propri attributi di sicurezza e cancellare i dati dell"unità.' 
---
= Sblocca o ripristina le unità NVMe o FIPS bloccate in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si inseriscono una o più unità NVMe o FIPS bloccate in un array di storage, è possibile sbloccare i dati dell'unità aggiungendo il file della chiave di sicurezza associato alle unità. Se non si dispone di una chiave di sicurezza, è possibile eseguire un ripristino su ciascuna unità bloccata inserendo il proprio ID di sicurezza fisico (PSID) per ripristinare i propri attributi di sicurezza e cancellare i dati dell'unità.

.Prima di iniziare
* Per l'opzione Sblocca, assicurati che il file della chiave di sicurezza (con estensione `.slk`) sia disponibile sul client di gestione (il sistema con un browser utilizzato per accedere a System Manager). Devi inoltre conoscere la passphrase associata alla chiave.
* Per l'opzione Reset (Ripristina), è necessario trovare il PSID su ciascun disco che si desidera reimpostare. Per individuare il PSID, rimuovere fisicamente l'unità e individuare la stringa PSID (massimo 32 caratteri) sull'etichetta dell'unità, quindi reinstallare l'unità.


.A proposito di questa attività
Questa attività descrive come sbloccare i dati nei dischi NVMe o FIPS importando un file di chiave di sicurezza nell'array di storage. Per le situazioni in cui la chiave di sicurezza non è disponibile, questa attività descrive anche come eseguire un ripristino su un disco bloccato.

[NOTE]
====
Se l'unità è stata bloccata tramite un server di gestione delle chiavi esterno, seleziona menu:System[Security key management] in System Manager per configurare la gestione delle chiavi esterne e sbloccare l'unità.

====
Puoi accedere alla funzione di sblocco dalla pagina Hardware oppure dal menu:System[Security key management]. La procedura seguente fornisce istruzioni dalla pagina Hardware.

.Fasi
. Dal pannello di sinistra, seleziona menu:Hardware[Drives].
. Selezionare l'unità NVMe o FIPS che si desidera sbloccare o ripristinare.
+
Viene visualizzato il menu di scelta rapida del disco.

. Selezionare *Unlock* (sblocco) per applicare il file della chiave di sicurezza o *Reset* (Ripristino) se non si dispone di un file della chiave di sicurezza.
+
Queste opzioni vengono visualizzate solo se si seleziona un disco NVMe o FIPS bloccato.

+
[CAUTION]
====
Durante un'operazione di ripristino, tutti i dati vengono cancellati. Eseguire un ripristino solo se non si dispone di una chiave di sicurezza. La reimpostazione di un disco bloccato rimuove in modo permanente tutti i dati presenti sul disco e ripristina i relativi attributi di sicurezza su "sicuro", ma non abilitato. *Questa operazione non è reversibile.*

====
. Effettuare una delle seguenti operazioni:
+
.. *Sblocca*: Nella pagina *Sblocca unità protette*, seleziona il file della chiave di sicurezza corrispondente all'unità che desideri sbloccare. Quindi, inserisci la passphrase e fai clic su *Sblocca*.
.. *Ripristina*: Nella finestra di dialogo *Ripristina unità bloccata*, inserisci la stringa PSID nel campo e poi digita  `RESET` per confermare. Fai clic su *Ripristina*.
+
Per un'operazione di sblocco, è necessario eseguire questa operazione una sola volta per sbloccare tutti i dischi NVMe o FIPS. Per eseguire un'operazione di ripristino, è necessario selezionare singolarmente ogni disco che si desidera ripristinare.





.Risultati
L'unità è ora disponibile per l'utilizzo in un altro gruppo di volumi o pool di dischi o in un altro array di storage.
