---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: È possibile visualizzare informazioni su un controller, ad esempio lo stato delle interfacce host, delle interfacce disco e delle porte di gestione. 
---
= Visualizza le impostazioni del controller in SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni su un controller, ad esempio lo stato delle interfacce host, delle interfacce disco e delle porte di gestione.

.Fasi
. Dal pannello di sinistra, selezionare menu:Hardware[Controllers and components].
. Per visualizzare le impostazioni del controller, eseguire una delle seguenti operazioni:
+
** Fare clic sul controller per visualizzare il menu di scelta rapida, quindi selezionare *View settings* (Visualizza impostazioni).
** Selezionare l'icona del controller (accanto all'elenco a discesa *Shelf*). Per le configurazioni duplex, selezionare *Controller A* o *Controller B* dalla finestra di dialogo, quindi fare clic su *Avanti*.
+
Si apre il menu a scorrimento delle impostazioni del controller.



. Esamina le sezioni per passare da un'impostazione all'altra delle proprietà del controller.
+
.Dettagli del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Sezione | Descrizione 


 a| 
Dettagli
 a| 
Mostra lo stato del controller, la data/ora, il nome del modello e il codice del pezzo di ricambio.



 a| 
Configurazione attuale
 a| 
Mostra la versione corrente del firmware e la versione della NVRAM.



 a| 
cache dei dati
 a| 
Mostra i totali della cache dei dati.



 a| 
Moduli di cache dati
 a| 
Mostra la posizione, lo stato e la capacità del modulo cache.



 a| 
cache del processore
 a| 
Mostra i totali della cache del processore.



 a| 
Dispositivi di backup della cache
 a| 
Mostra la posizione, lo stato e la capacità del dispositivo di backup della cache.



 a| 
Interfacce verso gli host
 a| 
Mostra le informazioni sull'interfaccia verso gli host e lo stato del collegamento per ciascuna porta.



 a| 
Interfacce dei dischi
 a| 
Mostra le informazioni sull'interfaccia dell'unità e lo stato del collegamento per ciascuna porta.



 a| 
Impostazioni della porta di gestione
 a| 
Mostra i dettagli della porta di gestione, inclusi il nome host del controller, l'accesso remoto e le impostazioni di rete IP.



 a| 
Impostazioni del server DNS (Domain Name System)
 a| 
Mostra la configurazione DNS, il DNS server primario e il DNS server di backup.



 a| 
Impostazioni del server network time protocol (NTP)
 a| 
Mostra i dettagli di configurazione del servizio NTP e del server NTP.

|===
====
. Fare clic su *Chiudi*.

