---
permalink: sm-hardware/why-is-the-storage-system-in-non-optimal-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, non-optimal, mode, 
summary: Un sistema storage in modalità non ottimale è dovuto a uno stato di configurazione del sistema non valido. Nonostante questo stato, il normale accesso i/o ai volumi esistenti è completamente supportato; tuttavia, System Manager proibirà alcune operazioni. 
---
= Perché il sistema storage non è in modalità ottimale?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un sistema storage in modalità non ottimale è dovuto a uno stato di configurazione del sistema non valido. Nonostante questo stato, il normale accesso i/o ai volumi esistenti è completamente supportato; tuttavia, Gestione di sistema di SANtricity proibirà alcune operazioni.

Un sistema storage potrebbe passare a una configurazione di sistema non valida per uno dei seguenti motivi:

* Il controller è fuori conformità, probabilmente perché ha un codice SMID (Submodel ID) errato o ha superato il limite delle funzionalità premium.
* È in corso un'operazione di servizio interna, ad esempio il download del firmware del disco.
* Il controller ha superato la soglia di errore di parità ed è entrato in blocco.
* Si è verificata una condizione generale di blocco.

