---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: È possibile configurare il mirroring asincrono o sincrono in Unified Manager, quindi utilizzare System Manager per gestire le sincronizzazioni. 
---
= Flusso di lavoro di configurazione del mirroring
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare il mirroring asincrono o sincrono in SANtricity Unified Manager e utilizzare SANtricity System Manager per gestire le sincronizzazioni.



== Workflow di mirroring asincrono

Il mirroring asincrono coinvolge il seguente flusso di lavoro:

. Eseguire la configurazione iniziale in Unified Manager:
+
.. Selezionare lo storage array locale come origine per il trasferimento dei dati.
.. Creare o selezionare un gruppo di coerenza mirror esistente, che è un contenitore per il volume primario sull'array locale e il volume secondario sull'array remoto. I volumi primario e secondario sono denominati "coppia mirrorata". Se si crea il gruppo di coerenza mirror per la prima volta, specificare se si desidera eseguire sincronizzazioni manuali o pianificate.
.. Selezionare un volume primario dall'array di storage locale, quindi determinarne la capacità riservata. La capacità riservata è la capacità fisica allocata da utilizzare per l'operazione di copia.
.. Selezionare un array di storage remoto come destinazione del trasferimento, un volume secondario, quindi determinarne la capacità riservata.
.. Avviare il trasferimento iniziale dei dati dal volume primario al volume secondario. A seconda delle dimensioni del volume, il trasferimento iniziale potrebbe richiedere diverse ore.


. Verificare l'avanzamento della sincronizzazione iniziale:
+
.. In Unified Manager, avviare System Manager per l'array locale.
.. In System Manager, visualizzare lo stato dell'operazione di mirroring. Una volta completato il mirroring, lo stato della coppia mirrorata è "ottimale".


. In alternativa, è possibile riprogrammare o eseguire manualmente i trasferimenti di dati successivi in System Manager. Solo i blocchi nuovi e modificati vengono trasferiti dal volume primario al volume secondario.
+
[NOTE]
====
Poiché la replica asincrona è periodica, il sistema può consolidare i blocchi modificati e conservare la larghezza di banda della rete. L'impatto sul throughput di scrittura e sulla latenza di scrittura è minimo.

====




== Workflow di mirroring sincrono

Il mirroring sincrono include il seguente flusso di lavoro:

. Eseguire la configurazione iniziale in Unified Manager:
+
.. Selezionare un array di storage locale come origine per il trasferimento dei dati.
.. Selezionare un volume primario dall'array di storage locale.
.. Selezionare un array di storage remoto come destinazione per il trasferimento dei dati, quindi selezionare un volume secondario.
.. Selezionare le priorità di sincronizzazione e risincronizzazione.
.. Avviare il trasferimento iniziale dei dati dal volume primario al volume secondario. A seconda delle dimensioni del volume, il trasferimento iniziale potrebbe richiedere diverse ore.


. Verificare l'avanzamento della sincronizzazione iniziale:
+
.. In Unified Manager, avviare System Manager per l'array locale.
.. In System Manager, visualizzare lo stato dell'operazione di mirroring. Una volta completato il mirroring, lo stato della coppia mirrorata è "ottimale". I due array tentano di rimanere sincronizzati con le normali operazioni. Solo i blocchi nuovi e modificati vengono trasferiti dal volume primario al volume secondario.


. In alternativa, è possibile modificare le impostazioni di sincronizzazione in System Manager.
+
[NOTE]
====
Poiché la replica sincrona è continua, il collegamento di replica tra i due siti deve fornire funzionalità di larghezza di banda sufficienti.

====

