---
permalink: um-manage/remove-storage-array.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, remove, storage, arrays, 
summary: È possibile rimuovere uno o più array di storage se non si desidera più gestirli da Gestione unificata di SANtricity. 
---
= Rimuovere gli array di storage da Gestione unificata di SANtricity
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere uno o più array di storage se non si desidera più gestirli da Unified Manager.

.A proposito di questa attività
Non è possibile accedere a nessuno degli array di storage rimossi. Tuttavia, è possibile stabilire una connessione a uno degli array di storage rimossi puntando direttamente un browser all'indirizzo IP o al nome host.

La rimozione di uno storage array non influisce in alcun modo sullo storage array o sui relativi dati. Se uno storage array viene rimosso accidentalmente, può essere aggiunto di nuovo.

.Fasi
. Selezionare la pagina *Gestisci*.
. Selezionare uno o più array di storage che si desidera rimuovere.
. Selezionare menu:Uncommon Tasks[Remove storage array].
+
Lo storage array viene rimosso da tutte le viste in Gestione unificata di SANtricity.


