---
permalink: sm-settings/access-management-tokens-create.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, create tokens 
summary: 'È possibile creare token di accesso, che vengono utilizzati per l"autenticazione con l"API REST o l"interfaccia della riga di comando al posto di un nome utente e di una password.' 
---
= Creare token di accesso
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un token di accesso per l'autenticazione con l'API REST o l'interfaccia della riga di comando (CLI) al posto di un nome utente e di una password.


NOTE: I token non dispongono di password, pertanto è necessario gestirle con attenzione.

.Fasi
. Selezionare menu:Impostazioni[Gestione accessi].
. Selezionare la scheda *Access Token*.
. Selezionare *View/Edit Access Token Settings* (Visualizza/Modifica impostazioni token di accesso). Nella finestra di dialogo, assicurarsi che la casella di controllo *Enable access token* (attiva token di accesso) sia selezionata. Fare clic su *Save* (Salva) per chiudere la finestra di dialogo.
. Selezionare *Create Access Token* (Crea token di accesso).
. Nella finestra di dialogo, selezionare la durata della validità del token.
+

NOTE: Una volta scaduto il token, i tentativi di autenticazione dell'utente non avranno esito positivo.

. Fare clic su *Crea.*
. Nella finestra di dialogo, selezionare una delle seguenti opzioni:
+
** *Copy* (Copia) per salvare il testo del token negli Appunti.
** *Download* per salvare il testo del token in un file.
+

NOTE: Assicurarsi di salvare il testo del token. Questa è l'unica opportunità per visualizzare il testo prima di chiudere la finestra di dialogo.



. Fare clic su *Chiudi*.
. Utilizzare il token come segue:
+
** *REST API*: Per utilizzare un token in una richiesta API REST, aggiungere un'intestazione HTTP alle richieste. Ad esempio:
`Authorization: Bearer _<access-token-value>_`
** *Secure CLI*: Per utilizzare un token nella CLI, aggiungere il valore del token nella riga di comando o utilizzare il percorso di un file contenente il valore del token. Ad esempio:
+
*** Valore del token sulla riga di comando: `-t _access-token-value_`
*** Percorso di un file contenente il valore del token: `-T _access-token-file_`
+

NOTE: Se non vengono specificati nome utente, password o token, l'interfaccia CLI richiede all'utente un valore del token di accesso sulla riga di comando.






