---
permalink: sm-settings/access-management-with-local-user-roles.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, local, user, roles, 
summary: 'Per la gestione degli accessi, gli amministratori possono utilizzare le funzionalità RBAC (role-based access control) applicate nell"array di storage. Queste funzionalità sono definite ruoli utente locali.' 
---
= Gestione degli accessi con ruoli utente locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la gestione degli accessi, gli amministratori possono utilizzare le funzionalità RBAC (role-based access control) applicate nell'array di storage. Queste funzionalità sono denominate "ruoli utente locali".



== Workflow di configurazione

I ruoli utente locali sono preconfigurati per lo storage array. Per utilizzare i ruoli utente locali per l'autenticazione, gli amministratori possono:

. Un amministratore accede a System Manager con un profilo utente che include le autorizzazioni di amministratore della sicurezza.
+
[NOTE]
====
Il `admin` l'utente ha accesso completo a tutte le funzioni del sistema.

====
. Un amministratore esamina i profili utente predefiniti e non modificabili.
. Facoltativamente, l'amministratore assegna nuove password per ogni profilo utente.
. Gli utenti accedono al sistema con le credenziali assegnate.




== Gestione

Quando si utilizzano solo ruoli utente locali per l'autenticazione, gli amministratori possono eseguire le seguenti attività di gestione:

* Modificare le password.
* Impostare una lunghezza minima per le password.
* Consentire agli utenti di effettuare l'accesso senza password.

