---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, trap, destinations, SNMP, alerts, 
summary: 'È possibile aggiungere fino a 10 server per l"invio di trap SNMP.' 
---
= Aggiungere destinazioni trap per gli avvisi SNMP in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere fino a 10 server per l'invio di trap SNMP.

.Prima di iniziare
* Il server di rete che si desidera aggiungere deve essere configurato con un'applicazione di servizio SNMP. È necessario l'indirizzo di rete di questo server (un indirizzo IPv4 o IPv6), in modo che il monitor eventi possa inviare messaggi trap a tale indirizzo. È possibile utilizzare più di un server (sono consentiti fino a 10 server).
* Il file MIB (Management Information base) è stato copiato e compilato sul server con l'applicazione del servizio SNMP. Questo file MIB definisce i dati monitorati e gestiti.
+
Se non si dispone del file MIB, è possibile ottenerlo dal sito NetApp Support:

+
** Passare a. https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^].
** Fare clic su *Downloads*, quindi selezionare *Downloads*.
** Fare clic su *Software controller OS SANtricity e-Series*.
** Selezionare *Scarica ultima release*.
** Effettuare l'accesso.
** Accettare la dichiarazione di attenzione e il contratto di licenza.
** Scorrere verso il basso fino a visualizzare il file MIB per il tipo di controller in uso, quindi fare clic sul collegamento per scaricare il file.




.Fasi
. Selezionare menu:Impostazioni[Avvisi].
. Selezionare la scheda *SNMP*.
+
Le destinazioni trap attualmente definite vengono visualizzate nella tabella.

. Selezionare *Add Trap Desinations* (Aggiungi Desination trap).
+
Viene visualizzata la finestra di dialogo Add Trap Destinations (Aggiungi destinazioni trap).

. Immettere una o più destinazioni trap, selezionare i nomi di comunità o utenti associati, quindi fare clic su *Aggiungi*.
+
** *Destinazione trap* -- immettere un indirizzo IPv4 o IPv6 del server che esegue un servizio SNMP.
** *Nome di comunità o Nome utente* -- dal menu a discesa, selezionare il nome di comunità (SNMPv2c) o il nome utente (SNMPv3) per questa destinazione trap. (Se ne è stata definita una sola, il nome viene già visualizzato in questo campo).
** *Send Authentication Failure Trap* -- selezionare questa opzione (la casella di controllo) se si desidera avvisare la destinazione trap ogni volta che una richiesta SNMP viene rifiutata a causa di un nome di comunità o di un nome utente non riconosciuto. Dopo aver fatto clic su *Aggiungi*, nella tabella vengono visualizzate le destinazioni trap e i nomi di comunità o utenti associati.


. Per assicurarsi che un trap sia valido, selezionare una destinazione trap dalla tabella, quindi fare clic su *Test Trap Destination* (destinazione trap test) per inviare un trap di test all'indirizzo configurato.


.Risultati
Il monitor degli eventi invia trap SNMP ai server ogni volta che si verifica un evento verificabile.
