---
permalink: sm-settings/add-user-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, users, snmpv3, traps, 
summary: È possibile aggiungere fino a 256 utenti per i trap SNMPv3. 
---
= Aggiungere utenti per le trap SNMPv3
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere fino a 256 utenti per i trap SNMPv3.

.Fasi
. Selezionare menu:Impostazioni[Avvisi].
. Selezionare la scheda *SNMP*.
+
Le destinazioni trap e i nomi utente vengono visualizzati nella tabella.

. Selezionare *Configure Users* (Configura utenti).
+
Viene visualizzata la finestra di dialogo Configure SNMPv3 Users (Configura utenti SNMPv3).

. Selezionare *Aggiungi*.
. Inserire le seguenti informazioni, quindi fare clic su *Aggiungi*.
+
** *Nome utente* -- immettere un nome per identificare l'utente, che può contenere fino a 31 caratteri.
** *ID motore* -- selezionare l'ID motore, utilizzato per generare chiavi di autenticazione e crittografia per i messaggi, che deve essere univoco nel dominio amministrativo. Nella maggior parte dei casi, selezionare *locale*. Se si dispone di una configurazione non standard, selezionare *Custom*; viene visualizzato un altro campo in cui inserire l'ID del motore autorevole come stringa esadecimale, con un numero pari di caratteri compreso tra 10 e 32 caratteri.
** *Authentication credentials* -- selezionare un protocollo di autenticazione che garantisca l'identità degli utenti. Quindi, inserire una password di autenticazione, necessaria quando si imposta o si modifica il protocollo di autenticazione. La password deve contenere da 8 a 128 caratteri.
** *Privacy credentials* -- selezionare un protocollo per la privacy utilizzato per crittografare il contenuto dei messaggi. Quindi, inserire una password per la privacy, necessaria quando il protocollo per la privacy viene impostato o modificato. La password deve contenere da 8 a 128 caratteri.



