---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: 'È possibile impostare la lunghezza minima richiesta per tutte le password utente locali nuove o aggiornate sull"array di storage. È inoltre possibile consentire agli utenti locali di accedere allo storage array senza inserire una password.' 
---
= Modificare le impostazioni della password utente locale
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile impostare la lunghezza minima richiesta per tutte le password utente locali nuove o aggiornate sull'array di storage. È inoltre possibile consentire agli utenti locali di accedere allo storage array senza inserire una password.

.Prima di iniziare
Devi essere connesso come amministratore locale, che include le autorizzazioni di amministratore root.

.A proposito di questa attività
Tenere presenti queste linee guida quando si imposta la lunghezza minima per le password utente locali:

* Le modifiche apportate non influiscono sulle password utente locali esistenti.
* La lunghezza minima richiesta per le password utente locali deve essere compresa tra 0 e 30 caratteri.
* Le nuove password utente locali devono soddisfare o superare l'impostazione di lunghezza minima corrente.
* Non impostare una lunghezza minima per la password se si desidera che gli utenti locali accedano allo storage array senza immettere una password.


.Fasi
. Selezionare menu:Impostazioni[Gestione accessi].
. Selezionare la scheda *ruoli utente locali*.
. Selezionare il pulsante *Visualizza/Modifica impostazioni*.
+
Viene visualizzata la finestra di dialogo Local User Password Settings (Impostazioni password utente locale).

. Effettuare una delle seguenti operazioni:
+
** Per consentire agli utenti locali di accedere allo storage array _senza_ inserire una password, deselezionare la casella di controllo "Richiedi almeno tutte le password utente locali".
** Per impostare una lunghezza minima della password per tutte le password utente locali, selezionare la casella di controllo "Richiedi almeno tutte le password utente locali", quindi utilizzare la casella di selezione per impostare la lunghezza minima richiesta per tutte le password utente locali.
+
Le nuove password utente locali devono soddisfare o superare l'impostazione corrente.



. Fare clic su *Save* (Salva).

