---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, security, key, 
summary: 'In qualsiasi momento, è possibile sostituire una chiave di sicurezza con una nuova. Potrebbe essere necessario modificare una chiave di sicurezza nei casi in cui si verifica una potenziale violazione della sicurezza presso l"azienda e si desidera assicurarsi che il personale non autorizzato non possa accedere ai dati dei dischi.' 
---
= Modificare la chiave di sicurezza
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In qualsiasi momento, è possibile sostituire una chiave di sicurezza con una nuova. Potrebbe essere necessario modificare una chiave di sicurezza nei casi in cui si verifica una potenziale violazione della sicurezza presso l'azienda e si desidera assicurarsi che il personale non autorizzato non possa accedere ai dati dei dischi.

.Fasi
. Selezionare menu:Impostazioni[sistema].
. In *Security key management*, selezionare *Change Key* (Cambia chiave).
+
Viene visualizzata la finestra di dialogo Change Security Key (Modifica chiave di protezione).

. Immettere le informazioni nei seguenti campi.
+
** *Definire un identificatore della chiave di sicurezza* -- (solo per le chiavi di sicurezza interne). Accettare il valore predefinito (nome dell'array di storage e data/ora, generato dal firmware del controller) o inserire un valore personalizzato. È possibile inserire fino a 189 caratteri alfanumerici senza spazi, punteggiatura o simboli.
+
[NOTE]
====
I caratteri aggiuntivi vengono generati automaticamente e aggiunti a entrambe le estremità della stringa immessa. I caratteri generati garantiscono che l'identificatore sia univoco.

====
** *Definire una passphrase/immettere nuovamente la passphrase* -- in ciascuno di questi campi, inserire la passphrase. Il valore può contenere da 8 a 32 caratteri e deve includere ciascuno dei seguenti elementi:
+
*** Una lettera maiuscola (una o più lettere). Tenere presente che la password distingue tra maiuscole e minuscole.
*** Un numero (uno o più).
*** Un carattere non alfanumerico, ad esempio !, *, @ (uno o più).




. Per le chiavi di sicurezza esterne, se si desidera eliminare la vecchia chiave di sicurezza quando viene creata la nuova, selezionare "Delete current Security key..." (Elimina chiave di sicurezza corrente...). casella di controllo nella parte inferiore della finestra di dialogo.
+
[CAUTION]
====
*Assicurarsi di registrare le voci per un utilizzo successivo* -- se è necessario spostare un disco abilitato alla sicurezza dall'array di storage, è necessario conoscere l'identificatore e la password per sbloccare i dati del disco.

====
. Fare clic su *Cambia*.
+
La nuova chiave di sicurezza sovrascrive la chiave precedente, che non è più valida.

+
[NOTE]
====
Il percorso del file scaricato potrebbe dipendere dalla posizione di download predefinita del browser.

====
. Registrare l'identificativo della chiave, la password e la posizione del file delle chiavi scaricato, quindi fare clic su *Chiudi*.


.Al termine
È necessario convalidare la chiave di sicurezza per assicurarsi che il file delle chiavi non sia corrotto.
