---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: È possibile modificare le password utente per ciascun profilo utente in Gestione accessi. 
---
= Modificare le password
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le password utente per ciascun profilo utente in Gestione accessi.

.Prima di iniziare
* Devi essere connesso come amministratore locale, che include le autorizzazioni di amministratore root.
* È necessario conoscere la password dell'amministratore locale.


.A proposito di questa attività
Quando si sceglie una password, tenere presenti le seguenti linee guida:

* Le nuove password utente locali devono soddisfare o superare l'impostazione corrente per una password minima (in Visualizza/Modifica impostazioni).
* Le password distinguono tra maiuscole e minuscole.
* Gli spazi finali non vengono rimossi dalle password quando vengono impostati. Fare attenzione a includere spazi se inclusi nella password.
* Per una maggiore sicurezza, utilizzare almeno 15 caratteri alfanumerici e modificare la password frequentemente.


[NOTE]
====
La modifica della password in System Manager viene modificata anche nell'interfaccia della riga di comando (CLI). Inoltre, le modifiche apportate alla password causano l'interruzione della sessione attiva dell'utente.

====
.Fasi
. Selezionare menu:Impostazioni[Gestione accessi].
. Selezionare la scheda *ruoli utente locali*.
. Selezionare un utente dalla tabella.
+
Il pulsante Change Password (Modifica password) diventa disponibile.

. Selezionare *Change Password* (Modifica password).
+
Viene visualizzata la finestra di dialogo Change Password (Modifica password).

. Se non è stata impostata alcuna lunghezza minima per le password utente locali, selezionare la casella per richiedere all'utente selezionato di immettere una password per accedere all'array di storage, quindi digitare la nuova password per l'utente selezionato.
. Immettere la password dell'amministratore locale, quindi fare clic su *Change* (Modifica).


.Risultati
Se l'utente è attualmente connesso, la modifica della password provoca l'interruzione della sessione attiva dell'utente.
