---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: 'Per una maggiore sicurezza in una rete iSCSI, è possibile impostare l"autenticazione tra controller (destinazioni) e host (iniziatori).' 
---
= Configurare l'autenticazione iSCSI in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per una maggiore sicurezza in una rete iSCSI, è possibile impostare l'autenticazione tra controller (destinazioni) e host (iniziatori).

System Manager utilizza il metodo Challenge Handshake Authentication Protocol (CHAP), che convalida l'identità di destinazioni e iniziatori durante il collegamento iniziale. L'autenticazione si basa su una chiave di sicurezza condivisa denominata _CHAP secret_.

.Prima di iniziare
È possibile impostare il segreto CHAP per gli iniziatori (host iSCSI) prima o dopo aver impostato il segreto CHAP per le destinazioni (controller). Prima di seguire le istruzioni di questa attività, è necessario attendere che gli host abbiano stabilito prima una connessione iSCSI, quindi impostare il segreto CHAP sui singoli host. Una volta effettuate le connessioni, i nomi IQN degli host e i relativi segreti CHAP vengono elencati nella finestra di dialogo per l'autenticazione iSCSI (descritta in questa attività) e non è necessario immetterli manualmente.

.A proposito di questa attività
Puoi abilitare l'autenticazione CHAP e poi specificare il segreto CHAP di destinazione per l'autenticazione unidirezionale, oppure puoi specificare sia il segreto CHAP dell'iniziatore per l'autenticazione bidirezionale tra il controller e gli host iSCSI.

L'autenticazione unidirezionale consente al controller di autenticare l'identità degli iSCSI host (autenticazione unidirezionale).

L'autenticazione bidirezionale consente sia al controller che agli iSCSI host di eseguire l'autenticazione (autenticazione bidirezionale). Questa opzione fornisce un secondo livello di sicurezza, permettendo al controller di autenticare l'identità degli iSCSI host e, a sua volta, agli iSCSI host di autenticare l'identità del controller.

.Fasi
. Dal pannello di sinistra, seleziona *Sistema*.
. In *impostazioni iSCSI*, fai clic su *Configura autenticazione iSCSI*.
+
Viene visualizzata la finestra Configura autenticazione.

. Seleziona la casella di controllo *Abilita autenticazione CHAP* per abilitare l'autenticazione.
+
Se non vuoi abilitare l'autenticazione CHAP, lascia la casella deselezionata.

. Se hai abilitato l'autenticazione unidirezionale, inserisci il *Target CHAP secret* per l'autenticazione degli iniziatori che si connettono al target. Il segreto CHAP deve essere compreso tra 12 e 57 caratteri ASCII stampabili.
+
Nel campo Conferma segreto CHAP di destinazione, reinserisci lo stesso segreto CHAP per confermarlo.

. Se vuoi abilitare l'autenticazione bidirezionale tra il controller e gli host iSCSI, inserisci il *segreto CHAP dell'iniziatore* per l'autenticazione del controller da parte degli iniziatori. Il segreto CHAP deve essere compreso tra 12 e 57 caratteri ASCII stampabili.
. Fare clic su *Save* (Salva).


.Risultati
L'autenticazione avviene durante la sequenza di login iSCSI tra i controller e gli host iSCSI, a meno che non sia stata specificata alcuna autenticazione.
