---
permalink: sm-settings/configure-syslog-server-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, syslog, server, alerts, 
summary: Per configurare gli avvisi syslog, è necessario immettere un indirizzo del server syslog e una porta UDP. Sono consentiti fino a cinque server syslog. 
---
= Configurare il server syslog per gli avvisi
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare gli avvisi syslog, è necessario immettere un indirizzo del server syslog e una porta UDP. Sono consentiti fino a cinque server syslog.

.Prima di iniziare
* L'indirizzo del server syslog deve essere disponibile. Questo indirizzo può essere un nome di dominio completo, un indirizzo IPv4 o un indirizzo IPv6.
* Il numero della porta UDP del server syslog deve essere disponibile. Questa porta è generalmente 514.


.A proposito di questa attività
Questa attività descrive come inserire l'indirizzo e la porta per il server syslog, quindi verificare l'indirizzo immesso.

.Fasi
. Selezionare menu:Impostazioni[Avvisi].
. Selezionare la scheda *Syslog*.
+
Se un server syslog non è ancora definito, nella pagina Avvisi viene visualizzato "Add Syslog Servers" (Aggiungi server Syslog).

. Fare clic su *Aggiungi server Syslog*.
+
Viene visualizzata la finestra di dialogo Add Syslog Server (Aggiungi server Syslog).

. Inserire le informazioni relative a uno o più server syslog (massimo cinque), quindi fare clic su *Aggiungi*.
+
** *Server Address* -- inserire un nome di dominio completo, un indirizzo IPv4 o un indirizzo IPv6.
** *UDP Port* -- in genere, la porta UDP per syslog è 514. Nella tabella vengono visualizzati i server syslog configurati.


. Per inviare un avviso di test agli indirizzi del server, selezionare *Test All Syslog Servers* (verifica tutti i server Syslog).


.Risultati
Il monitor degli eventi invia avvisi al server syslog ogni volta che si verifica un evento verificabile. Per configurare ulteriormente le impostazioni syslog per i registri di controllo, vedere https://docs.netapp.com/us-en/e-series-santricity/sm-settings/configure-syslog-server-for-audit-logs.html["Configurare il server syslog per i registri di controllo"].


NOTE: Se sono configurati più server syslog, tutti i server syslog configurati riceveranno un registro di controllo.
