---
permalink: sm-settings/configure-nvme-over-roce-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, roce, ports, 
summary: 'Se il controller include una connessione per NVMe su RoCE (RDMA over Converged Ethernet), è possibile configurare le impostazioni della porta NVMe dalla pagina System (sistema).' 
---
= Configurare NVMe sulle porte RoCE
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una connessione per NVMe su RoCE (RDMA over Converged Ethernet), è possibile configurare le impostazioni della porta NVMe dalla pagina System (sistema).

.Prima di iniziare
* Il controller deve includere un NVMe su una porta host RoCE; in caso contrario, le impostazioni NVMe su RoCE non sono disponibili in System Manager.
* È necessario conoscere l'indirizzo IP della connessione host.


.Fasi
. Selezionare menu:Impostazioni[sistema].
. In *NVMe over ROCE settings*, selezionare *Configure NVMe over ROCE ports* (Configura NVMe su porte ROCE).
. Selezionare il controller con la porta NVMe over RoCE che si desidera configurare. Fare clic su *Avanti*.
. Selezionare la porta HIC che si desidera configurare dall'elenco a discesa. Fare clic su *Avanti*.
. Configurare le impostazioni della porta.
+
Per visualizzare tutte le impostazioni della porta, fare clic sul collegamento *Mostra altre impostazioni della porta* a destra della finestra di dialogo.

+
.Dettagli campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Impostazione della porta | Descrizione 


 a| 
Velocità della porta ethernet configurata
 a| 
Selezionare la velocità che corrisponde alla velocità del modulo SFP sulla porta.



 a| 
Attiva IPv4 / attiva IPv6
 a| 
Selezionare una o entrambe le opzioni per abilitare il supporto per le reti IPv4 e IPv6.


NOTE: Se si desidera disattivare l'accesso alla porta, deselezionare entrambe le caselle di controllo.



 a| 
Dimensione MTU (disponibile facendo clic su *Mostra altre impostazioni della porta*).
 a| 
Se necessario, inserire una nuova dimensione in byte per l'unità di trasmissione massima (MTU).

La dimensione massima predefinita dell'unità di trasmissione (MTU) è di 1500 byte per frame. Immettere un valore compreso tra 1500 e 9000.

|===
====
+
Se si seleziona *Enable IPv4* (attiva IPv4), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv4. Se si seleziona *Enable IPv6* (attiva IPv6*), dopo aver fatto clic su *Next* (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv6. Se sono state selezionate entrambe le opzioni, viene visualizzata prima la finestra di dialogo per le impostazioni IPv4, quindi dopo aver fatto clic su *Avanti*, viene visualizzata la finestra di dialogo per le impostazioni IPv6.

. Configurare le impostazioni IPv4 e/o IPv6, automaticamente o manualmente.
+
.Dettagli campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Impostazione della porta | Descrizione 


 a| 
Ottenere automaticamente la configurazione
 a| 
Selezionare questa opzione per ottenere la configurazione automaticamente.



 a| 
Specificare manualmente la configurazione statica
 a| 
Selezionare questa opzione, quindi inserire un indirizzo statico nei campi. (Se lo si desidera, è possibile tagliare e incollare gli indirizzi nei campi). Per IPv4, includere la subnet mask di rete e il gateway. Per IPv6, includere l'indirizzo IP instradabile e l'indirizzo IP del router. Se si configura un array di storage EF600 con un HIC da 200 GB, questa finestra di dialogo visualizza due serie di campi per i parametri di rete, uno per una porta fisica (esterna) e uno per una porta virtuale (interna). È necessario assegnare parametri univoci per entrambe le porte. Queste impostazioni consentono all'host di stabilire un percorso tra ciascuna porta e di ottenere le massime prestazioni dall'HIC. Se non si assegna un indirizzo IP alla porta virtuale, l'HIC funziona a circa la metà della velocità.

|===
====
. Fare clic su *fine*.

