---
permalink: sm-settings/delete-trusted-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, trusted, certificates, 
summary: 'È possibile eliminare i certificati installati dall"utente precedentemente importati dalla scheda Trusted.' 
---
= Eliminare i certificati attendibili
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare i certificati installati dall'utente precedentemente importati dalla scheda Trusted.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* Se si sta aggiornando un certificato attendibile con una nuova versione, il certificato aggiornato deve essere importato prima di eliminare il vecchio certificato.


[CAUTION]
====
Prima di importare un certificato sostitutivo, si potrebbe perdere l'accesso a un sistema se si elimina un certificato utilizzato per autenticare i controller e un altro server, ad esempio un server LDAP.

====
.A proposito di questa attività
Questa attività descrive come eliminare i certificati installati dall'utente. I certificati autofirmati preinstallati non possono essere cancellati.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Selezionare la scheda *Trusted*.
+
La tabella mostra i certificati attendibili dell'array di storage.

. Nella tabella, selezionare il certificato che si desidera rimuovere.
. Fare clic sul menu:attività non comuni[Elimina].
+
Viene visualizzata la finestra di dialogo Conferma eliminazione certificato attendibile.

. Tipo `delete` Nel campo, quindi fare clic su *Delete* (Elimina).

