---
permalink: sm-settings/edit-alert-email-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, email, addresses, alerts, 
summary: È possibile modificare gli indirizzi e-mail dei destinatari che ricevono gli avvisi e-mail. 
---
= Modifica gli indirizzi email per gli avvisi in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare gli indirizzi e-mail dei destinatari che ricevono gli avvisi e-mail.

.Prima di iniziare
L'indirizzo email che vuoi modificare deve essere definito nella pagina Avvisi via email.

.Fasi
. Dal pannello di sinistra, seleziona menu:Alerts[Email alerts].
. Nella tabella *Indirizzo email*, selezionare l'indirizzo che si desidera modificare, quindi fare clic sull'icona *Modifica* (matita) all'estrema destra.
+
La riga diventa un campo modificabile.

. Inserire un nuovo indirizzo, quindi fare clic sull'icona *Salva* (segno di spunta).
+
[NOTE]
====
Per annullare le modifiche, selezionare l'icona *Annulla* (X).

====


.Risultati
La pagina degli avvisi email mostra gli indirizzi email aggiornati.
