---
permalink: sm-settings/edit-storage-array-name.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, storage array, name, 
summary: 'È possibile modificare il nome dell"array di storage visualizzato nella barra del titolo di Gestore di sistema di SANtricity.' 
---
= Modifica il nome dell'array di archiviazione in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare il nome dell'array di storage visualizzato nella barra del titolo di Gestore di sistema di SANtricity.

.Fasi
. Dal pannello di sinistra, seleziona *Sistema*.
. Nella sezione *Generale*, fai clic su *Modifica nome array di archiviazione*.
+
Viene visualizzata la finestra di dialogo Modifica nome array di archiviazione.

. Inserisci un nuovo nome nel campo *Nome*.
+
Un nome può contenere lettere, numeri e caratteri speciali sottolineatura (_), trattino (-) e cancelletto ( n.). Un nome non può contenere spazi. Un nome può avere una lunghezza massima di 30 caratteri. Il nome deve essere univoco.

. Fare clic su *Save* (Salva).


.Risultati
Il nuovo nome viene visualizzato nella barra del titolo di Gestore di sistema di SANtricity.
