---
permalink: sm-settings/export-key-management-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, export, key, management, server, certificates, 
summary: È possibile salvare un certificato per un server di gestione delle chiavi nel computer locale. 
---
= Esportare i certificati del server di gestione delle chiavi
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile salvare un certificato per un server di gestione delle chiavi nel computer locale.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* I certificati devono essere importati in precedenza.


.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Selezionare la scheda *Key Management* (Gestione chiavi).
. Dalla tabella, selezionare il certificato che si desidera esportare, quindi fare clic su *Esporta*.
+
Viene visualizzata la finestra di dialogo Save (Salva).

. Inserire un nome file e fare clic su *Save* (Salva).

