---
permalink: sm-settings/faq-storage-system-alerts.html 
sidebar: sidebar 
keywords:  
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sugli avvisi del sistema di archiviazione per SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Cosa fare se gli avvisi sono disattivati?

Se si desidera che gli amministratori ricevano notifiche su eventi importanti che si verificano nell'array di storage, è necessario configurare un metodo di avviso.

Per gli array di storage gestiti con Gestore di sistema di SANtricity, è possibile configurare gli avvisi dalla pagina Avvisi. Le notifiche di avviso possono essere inviate tramite e-mail, trap SNMP o messaggi syslog. Inoltre, gli avvisi e-mail possono essere configurati dall'installazione guidata iniziale.



== Come si configurano gli avvisi SNMP o syslog?

Oltre agli avvisi via email, è possibile configurare gli avvisi in modo che vengano inviati tramite trap SNMP (Simple Network Management Protocol) o messaggi syslog.

Per configurare gli avvisi SNMP o syslog, accedere al menu:Impostazioni[Avvisi].



== Perché i timestamp non sono coerenti tra l'array e gli avvisi?

Quando lo storage array invia avvisi, non corregge il fuso orario del server o dell'host di destinazione che riceve gli avvisi. Invece, l'array di storage utilizza l'ora locale (GMT) per creare l'indicazione dell'ora utilizzata per il record di avviso. Di conseguenza, potrebbero verificarsi delle incoerenze tra i timestamp per lo storage array e il server o l'host che riceve un avviso.

Poiché l'array di storage non corregge il fuso orario durante l'invio degli avvisi, l'indicazione dell'ora sugli avvisi è relativa al GMT, con un offset del fuso orario pari a zero. Per calcolare un indicatore data e ora appropriato al fuso orario locale, è necessario determinare l'offset dell'ora dal GMT, quindi aggiungere o sottrarre tale valore dai contrassegni data e ora.
