---
permalink: sm-settings/how-do-i-know-what-certificates-need-to-be-uploaded-to-system-manager.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, certificates, external, key, management, 
summary: 'Per la gestione esterna delle chiavi, vengono importati due tipi di certificati per l"autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l"una dell"altra.' 
---
= Come è possibile sapere quali certificati devono essere caricati in System Manager per la gestione esterna delle chiavi?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la gestione esterna delle chiavi, vengono importati due tipi di certificati per l'autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l'una dell'altra.

Un certificato client convalida i controller dello storage array, in modo che il server di gestione delle chiavi possa considerare attendibili le richieste del protocollo KMIP (Key Management Interoperability Protocol). Per ottenere un certificato client, utilizzare System Manager per completare una CSR per lo storage array. È quindi possibile caricare la CSR su un server di gestione delle chiavi e generare un certificato client da tale server. Una volta ottenuto un certificato client, copiare il file sull'host in cui si accede a System Manager.

Un certificato del server di gestione delle chiavi convalida il server di gestione delle chiavi, in modo che lo storage array possa fidarsi del proprio indirizzo IP. Recuperare il file di certificato del server dal server di gestione delle chiavi, quindi copiarlo sull'host in cui si accede a System Manager.
