---
permalink: sm-settings/how-do-i-interpret-nvme-over-fabrics-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, nvme, over, Fabrics, statistics, 
summary: 'La finestra di dialogo View NVMe over Fabrics Statistics (Visualizza statistiche NVMe su fabric) visualizza le statistiche per il sottosistema NVMe e l"interfaccia RDMA. Tutte le statistiche sono di sola lettura e non possono essere impostate.' 
---
= Come si interpretano le statistiche NVMe sulle fabric?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo View NVMe over Fabrics Statistics (Visualizza statistiche NVMe su fabric) visualizza le statistiche per il sottosistema NVMe e l'interfaccia RDMA. Tutte le statistiche sono di sola lettura e non possono essere impostate.

* *NVMe Subsystem statistics* -- Mostra le statistiche del controller NVMe e della relativa coda. Il controller NVMe fornisce un percorso di accesso tra un host e gli spazi dei nomi nell'array di storage. È possibile esaminare le statistiche del sottosistema NVMe per elementi quali errori di connessione, ripristini e arresti. Per ulteriori informazioni su queste statistiche, fare clic su *Visualizza legenda per le intestazioni delle tabelle*.
* *RDMA Interface statistics* -- fornisce statistiche per tutte le porte NVMe over Fabrics sull'interfaccia RDMA, che includono statistiche sulle performance e informazioni sugli errori di collegamento associate a ciascuna porta dello switch. Questa scheda viene visualizzata solo quando sono disponibili porte NVMe over Fabrics. Per ulteriori informazioni sulle statistiche, fare clic su *Visualizza legenda per le intestazioni delle tabelle*.


È possibile visualizzare ciascuna di queste statistiche come statistiche raw o come statistiche baseline. Le statistiche raw sono tutte le statistiche raccolte dall'avvio dei controller. Le statistiche di riferimento sono statistiche point-in-time raccolte dall'ora di riferimento impostata.
