---
permalink: sm-settings/import-trusted-certificates-for-controllers-acting-as-client.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, certificates, 
summary: 'Se il controller rifiuta una connessione perché non riesce a convalidare la catena di fiducia per un server di rete, puoi importare un certificato dalla pagina Certificati attendibili che permette al controller (agendo come client) di accettare comunicazioni da quel server.' 
---
= Importare certificati per i controller quando agiscono come client in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller rifiuta una connessione perché non riesce a convalidare la catena di fiducia per un server di rete, puoi importare un certificato dalla pagina Certificati attendibili che permette al controller (agendo come client) di accettare comunicazioni da quel server.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* I file dei certificati vengono installati nel sistema locale.


.A proposito di questa attività
L'importazione dei certificati dalla pagina Certificati attendibili potrebbe essere necessaria se vuoi consentire a un altro server di contattare i controller (ad esempio, un LDAP server o un syslog server che utilizza TLS).

.Fasi
. Dal pannello di sinistra, seleziona menu:Certificates[Trusted certificates] e poi seleziona *Import*.
+
Viene visualizzata una finestra di dialogo per l'importazione dei file di certificato attendibili.

. Fare clic su *Browse* (Sfoglia) per selezionare i file di certificato per i controller.
+
I nomi dei file vengono visualizzati nella finestra di dialogo.

. Fare clic su *Importa*.


.Risultati
I file vengono caricati e validati.
