---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, obtain, feature, key, file, 
summary: 'Per attivare una funzionalità o un Feature Pack premium sull"array di storage, è necessario prima ottenere un file delle chiavi delle funzioni. Una chiave è associata a un solo array di storage.' 
---
= Ottieni un file chiave di funzionalità in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per attivare una funzionalità o un Feature Pack premium sull'array di storage, è necessario prima ottenere un file delle chiavi delle funzioni. Una chiave è associata a un solo array di storage.

.A proposito di questa attività
Questa attività descrive come raccogliere le informazioni necessarie per la funzione e inviare una richiesta per un file delle chiavi di funzione. Le informazioni richieste includono:

* Numero di serie dello chassis
* Identificatore di abilitazione della funzione
* Codice di attivazione della funzione


.Fasi
. In System Manager, individua e annota il numero di serie dello chassis. Dal pannello di sinistra, vai su menu:Support[Support center] e scorri verso il basso fino a *View top storage array properties* per visualizzare il numero di serie dello chassis.
. In System Manager, individua l'identificativo di abilitazione della funzionalità. Dal pannello di sinistra, seleziona *Sistema* e scorri verso il basso fino a *Componenti aggiuntivi*. Cerca l'*identificativo di abilitazione della funzionalità*. Annota il numero dell'identificativo di abilitazione della funzionalità.
. Individuare e registrare il codice per l'attivazione della funzione. Per i pacchetti di funzionalità, questo codice viene fornito nelle istruzioni appropriate per l'esecuzione della conversione.
+
Per le funzioni Premium, è possibile accedere al codice di attivazione dal sito del supporto, come indicato di seguito:

+
.. Accedere a. https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^].
.. Accedere a *licenze software* per il prodotto in uso.
.. Inserire il numero di serie dello chassis dello storage array, quindi fare clic su *Go*.
.. Cercare i codici di attivazione delle funzioni nella colonna *chiave di licenza*.
.. Annotare il codice di attivazione della funzione desiderata.


. Richiedere un file delle chiavi hardware inviando un'e-mail o un documento di testo al fornitore dello storage con le seguenti informazioni: Numero di serie dello chassis, identificativo di abilitazione e codice per l'attivazione delle funzioni.
+
È inoltre possibile visitare il sito Web all'indirizzo http://partnerspfk.netapp.com["Attivazione della licenza NetApp: Attivazione della funzionalità Premium dello storage Array"^] e inserire le informazioni richieste per ottenere la funzionalità o il feature pack. (Le istruzioni su questo sito sono relative alle funzioni premium, non ai pacchetti di funzionalità).



.Al termine
Se si dispone di un file delle chiavi delle funzioni, è possibile attivare la funzionalità Premium o il Feature Pack.
