---
permalink: sm-settings/permissions-for-mapped-roles.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, permissions, mapped, roles, 
summary: 'Le funzionalità RBAC (role-based access control) applicate all"array di storage includono profili utente predefiniti con uno o più ruoli mappati. Ogni ruolo include le autorizzazioni per l"accesso alle attività in Gestore di sistema di SANtricity.' 
---
= Autorizzazioni per i ruoli mappati
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le funzionalità RBAC (role-based access control) applicate all'array di storage includono profili utente predefiniti con uno o più ruoli mappati. Ogni ruolo include le autorizzazioni per l'accesso alle attività in System Manager.

I profili utente e i ruoli mappati sono accessibili dal menu:Impostazioni[Gestione accessi > ruoli utente locali] nell'interfaccia utente di System Manager.

I ruoli forniscono agli utenti l'accesso alle attività, come segue:

* *Storage admin* -- accesso completo in lettura/scrittura agli oggetti di storage (ad esempio, volumi e pool di dischi), ma nessun accesso alla configurazione di sicurezza.
* *Security admin* -- accesso alla configurazione della sicurezza in Access Management, gestione dei certificati, gestione dei registri di controllo e possibilità di attivare o disattivare l'interfaccia di gestione legacy (Symbol).
* *Support admin* -- accesso a tutte le risorse hardware dello storage array, dati di guasto, eventi MEL e aggiornamenti del firmware del controller. Nessun accesso agli oggetti di storage o alla configurazione di sicurezza.
* *Monitor* -- accesso in sola lettura a tutti gli oggetti di storage, ma nessun accesso alla configurazione di sicurezza.


Se un utente non dispone delle autorizzazioni per una determinata attività, tale attività viene visualizzata in grigio o non viene visualizzata nell'interfaccia utente.
