---
permalink: sm-settings/remove-directory-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, directory, server, 
summary: 'Per interrompere la connessione tra un server di directory e l"array di storage, puoi rimuovere le informazioni del server dalla pagina Directory services. Potresti voler eseguire questa operazione se hai configurato un nuovo server e poi vuoi rimuovere quello vecchio.' 
---
= Rimuovere il server di directory in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per interrompere la connessione tra un server di directory e l'array di storage, puoi rimuovere le informazioni del server dalla pagina Directory services. Potresti voler eseguire questa operazione se hai configurato un nuovo server e poi vuoi rimuovere quello vecchio.

.Prima di iniziare
È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni di gestione degli accessi non vengono visualizzate.

.A proposito di questa attività
Una volta completata questa attività, tutte le sessioni utente attive vengono terminate. Viene conservata solo la sessione utente corrente.

.Fasi
. Dal pannello di sinistra, seleziona menu:Autenticazione[Directory services].
. Dall'elenco, selezionare il server di directory che si desidera eliminare.
. Fare clic su *Rimuovi*.
+
Viene visualizzata la finestra di dialogo Remove Directory Server (Rimuovi server di directory).

. Tipo `remove` Nel campo, quindi fare clic su *Rimuovi*.
+
Le impostazioni di configurazione del server di directory, le impostazioni dei privilegi e i mapping dei ruoli vengono rimossi. Gli utenti non possono più accedere con le credenziali da questo server.


