---
permalink: sm-settings/reset-management-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reset, management, certificates, 
summary: 'È possibile ripristinare i certificati sui controller dall"utilizzo dei certificati firmati dalla CA ai certificati autofirmati impostati in fabbrica.' 
---
= Reimpostare i certificati di gestione
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare i certificati sui controller dall'utilizzo dei certificati firmati dalla CA ai certificati autofirmati impostati in fabbrica.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* I certificati con FIRMA CA devono essere importati in precedenza.


.A proposito di questa attività
La funzione Reset elimina i file di certificato firmati dalla CA corrente da ciascun controller. I controller torneranno quindi a utilizzare certificati autofirmati.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Dalla scheda Array Management (Gestione array), selezionare *Reset* (Ripristina).
+
Viene visualizzata la finestra di dialogo Conferma ripristino certificati di gestione.

. Tipo `reset` Nel campo, quindi fare clic su *Reset*.
+
Dopo l'aggiornamento del browser, il browser potrebbe bloccare l'accesso al sito di destinazione e segnalare che il sito utilizza HTTP Strict Transport Security. Questa condizione si verifica quando si torna ai certificati autofirmati. Per eliminare la condizione che sta bloccando l'accesso alla destinazione, è necessario cancellare i dati di navigazione dal browser.



.Risultati
I controller tornano a utilizzare certificati autofirmati. Di conseguenza, il sistema richiede agli utenti di accettare manualmente il certificato autofirmato per le sessioni.
