---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, imported, certificate, information, 
summary: 'Dalla categoria Certificati, puoi visualizzare il tipo di certificato, l"autorità emittente e l"intervallo di date di validità dei certificati per l"array di storage.' 
---
= Visualizza le informazioni sul certificato importato in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla categoria Certificati, puoi visualizzare il tipo di certificato, l'autorità emittente e l'intervallo di date di validità dei certificati per l'array di storage.

.Prima di iniziare
È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.

.Fasi
. Dal pannello di sinistra, seleziona *Certificati*.
. Seleziona una delle pagine seguenti per visualizzare le informazioni sui certificati.
+
[cols="25h,~"]
|===
| Pagina | Descrizione 


 a| 
menu:Certificati[Certificati di gestione array]
 a| 
Visualizzare le informazioni sui certificati firmati dalla CA importati per ciascun controller, inclusi il file root, i file intermedi e i file server.



 a| 
menu:Certificati[Certificati attendibili]
 a| 
Visualizza le informazioni su tutti gli altri tipi di certificati importati per i controller. Utilizzare il campo del filtro sotto *Mostra certificati...* per visualizzare i certificati installati dall'utente o preinstallati.

** *Installato dall'utente* -- certificati caricati da un utente nell'array di storage, che possono includere certificati attendibili quando il controller agisce come client (anziché come server), certificati LDAPS e certificati Identity Federation.
** *Preinstallati* -- certificati autofirmati inclusi con lo storage array.




 a| 
menu:Certificati[Certificati di gestione delle chiavi]
 a| 
Consente di visualizzare informazioni sui certificati firmati dalla CA importati per un server di gestione delle chiavi esterno.

|===

