---
permalink: sm-settings/view-nvme-over-fabrics-statistics-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, nvme, fabrics, statistics, 
summary: È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array. 
---
= Visualizza le statistiche NVMe su Fabrics in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array.

.A proposito di questa attività
System Manager mostra questi tipi di statistiche NVMe over Fabrics. Tutte le statistiche sono di sola lettura e non possono essere impostate.

* *Sottosistema NVMe* -- Mostra le statistiche per il controller NVMe e la sua coda. Il controller NVMe fornisce un percorso di accesso tra un host e i namespace nell'array di storage. Puoi consultare le statistiche del sottosistema NVMe per elementi come errori di connessione, ripristini e arresti.
* *Statistiche RDMA* -- Fornisce statistiche per tutte le porte NVMe over Fabrics sull'interfaccia RDMA, incluse statistiche sulle prestazioni e informazioni sugli errori di collegamento associate a ciascuna porta dello switch. Questa scheda viene visualizzata solo quando sono disponibili porte NVMe over Fabrics.


È possibile visualizzare ciascuna di queste statistiche come statistiche raw o come statistiche baseline. Le statistiche raw sono tutte le statistiche raccolte dall'avvio dei controller. Le statistiche di riferimento sono statistiche point-in-time raccolte dall'ora di riferimento impostata.

.Fasi
. Dal pannello di sinistra, seleziona *Sistema*.
. Seleziona *Visualizza statistiche NVMe over Fabrics*.
. *Opzionale:* per impostare la linea di base, fare clic su *Imposta nuova linea di base*.
+
L'impostazione della linea di base consente di impostare un nuovo punto di partenza per la raccolta delle statistiche. La stessa linea di base viene utilizzata per tutte le statistiche NVMe.


