---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, imported, certificate, information, 
summary: 'Dalla pagina certificati, è possibile visualizzare il tipo di certificato, l"autorità di emissione e l"intervallo di date valido dei certificati per l"array di storage.' 
---
= Visualizzare le informazioni sul certificato importato
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina certificati, è possibile visualizzare il tipo di certificato, l'autorità di emissione e l'intervallo di date valido dei certificati per l'array di storage.

.Prima di iniziare
È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Selezionare una delle schede per visualizzare le informazioni relative ai certificati.
+
[cols="25h,~"]
|===
| Scheda | Descrizione 


 a| 
Gestione degli array
 a| 
Visualizzare le informazioni sui certificati firmati dalla CA importati per ciascun controller, inclusi il file root, i file intermedi e i file server.



 a| 
Affidabile
 a| 
Visualizza le informazioni su tutti gli altri tipi di certificati importati per i controller. Utilizzare il campo del filtro sotto *Mostra certificati...* per visualizzare i certificati installati dall'utente o preinstallati.

** *Installato dall'utente* -- certificati caricati da un utente nell'array di storage, che possono includere certificati attendibili quando il controller agisce come client (anziché come server), certificati LDAPS e certificati Identity Federation.
** *Preinstallati* -- certificati autofirmati inclusi con lo storage array.




 a| 
Gestione delle chiavi
 a| 
Consente di visualizzare informazioni sui certificati firmati dalla CA importati per un server di gestione delle chiavi esterno.

|===

