---
permalink: sm-settings/view-nvme-over-fabrics-statistics-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, nvme, fabrics, statistics, 
summary: È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array. 
---
= Visualizza le statistiche NVMe over Fabrics
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array.

.A proposito di questa attività
System Manager mostra questi tipi di statistiche NVMe over Fabrics. Tutte le statistiche sono di sola lettura e non possono essere impostate.

* *NVMe Subsystem statistics* -- Mostra le statistiche del controller NVMe e della relativa coda. Il controller NVMe fornisce un percorso di accesso tra un host e gli spazi dei nomi nell'array di storage. È possibile esaminare le statistiche del sottosistema NVMe per elementi quali errori di connessione, ripristini e arresti.
* *RDMA Interface statistics* -- fornisce statistiche per tutte le porte NVMe over Fabrics sull'interfaccia RDMA, che includono statistiche sulle performance e informazioni sugli errori di collegamento associate a ciascuna porta dello switch. Questa scheda viene visualizzata solo quando sono disponibili porte NVMe over Fabrics.


È possibile visualizzare ciascuna di queste statistiche come statistiche raw o come statistiche baseline. Le statistiche raw sono tutte le statistiche raccolte dall'avvio dei controller. Le statistiche di riferimento sono statistiche point-in-time raccolte dall'ora di riferimento impostata.

.Fasi
. Selezionare menu:Impostazioni[sistema].
. Selezionare *View NVMe over Fabrics Statistics* (Visualizza statistiche NVMe over Fabrics).
. *Opzionale:* per impostare la linea di base, fare clic su *Imposta nuova linea di base*.
+
L'impostazione della linea di base consente di impostare un nuovo punto di partenza per la raccolta delle statistiche. La stessa linea di base viene utilizzata per tutte le statistiche NVMe.


