---
permalink: sm-support/overview-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, support, center 
summary: Utilizzare il Support Center per eseguire operazioni di diagnostica, ripristino e raccolta di informazioni che potrebbero essere richieste dal supporto tecnico. 
---
= Panoramica del supporto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Support (Assistenza) fornisce l'accesso alle risorse di supporto tecnico.



== Quali attività di supporto sono disponibili?

In Assistenza, è possibile visualizzare i contatti del supporto tecnico, eseguire la diagnostica, configurare AutoSupport, visualizzare il registro eventi ed eseguire gli aggiornamenti del software.

Scopri di più:

* link:autosupport-feature-overview.html["Panoramica delle funzionalità di AutoSupport"]
* link:overview-event-log.html["Panoramica del registro eventi"]
* link:overview-upgrade-center.html["Panoramica di Upgrade Center"]




== Come posso contattare il supporto tecnico?

Dalla pagina principale, fare clic su menu:Support[Support Center > scheda Support Resources]. Le informazioni di contatto del supporto tecnico sono elencate nella parte superiore destra dell'interfaccia.
