---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: È possibile accedere a SANtricity da diversi tipi di browser e sistemi operativi. 
---
= Supporto del browser software SANtricity e del sistema operativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il software SANtricity supporta diversi tipi di browser e sistemi operativi.



== Browser

Sono supportati i seguenti browser e versioni.

[cols="1a,1a"]
|===
| Browser | Versione minima 


 a| 
Google Chrome
 a| 
120



 a| 
Mozilla Firefox
 a| 
120



 a| 
Safari
 a| 
16



 a| 
Microsoft Edge
 a| 
120

|===
[NOTE]
====
Per Unified Manager, il proxy dei servizi Web deve essere installato e disponibile nel browser. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["Panoramica dei proxy dei servizi web SANtricity"^]

====


== Sistemi operativi

Sono supportati i seguenti sistemi operativi e versioni.

[cols="1a,1a"]
|===
| Sistema operativo | Versione/architettura minima 


 a| 
Red Hat Enterprise Linux (RHEL)
 a| 
8.x (SP10), 9.x (SP6, SP7), 10.x (GA, SP1) / 64-bit



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
15.x (SP6, SP7), 16.x (GA) / 64-bit



 a| 
Oracle Linux (OL)
 a| 
8.x (U10), 9.x (U6, U7), 10.x (GA, SP1) / 64-bit



 a| 
Server Windows
 a| 
2019, 2022, 2025 / 64-bit



 a| 
Ubuntu
 a| 
20.04, 22.04 / 64-bit

|===