---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: È possibile modificare le password utente per ciascun utente in Gestione accessi. 
---
= Modificare le password per i profili utente locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le password utente per ciascun utente in Gestione accessi.

.Prima di iniziare
* Devi essere connesso come amministratore locale, che include le autorizzazioni di amministratore root.
* È necessario conoscere la password dell'amministratore locale.


.A proposito di questa attività
Quando si sceglie una password, tenere presenti le seguenti linee guida:

* Le nuove password utente locali devono soddisfare o superare l'impostazione corrente per una password minima (in Visualizza/Modifica impostazioni).
* Le password distinguono tra maiuscole e minuscole.
* Gli spazi finali non vengono rimossi dalle password quando vengono impostati. Fare attenzione a includere spazi se inclusi nella password.
* Per una maggiore sicurezza, utilizzare almeno 15 caratteri alfanumerici e modificare la password frequentemente.


.Fasi
. Selezionare *Access Management*.
. Selezionare la scheda *ruoli utente locali*.
. Selezionare un utente dalla tabella.
+
Il pulsante Change Password (Modifica password) diventa disponibile.

. Selezionare *Change Password* (Modifica password).
+
Viene visualizzata la finestra di dialogo Change Password (Modifica password).

. Se non è stata impostata alcuna lunghezza minima per le password utente locali, selezionare la casella di controllo per richiedere all'utente di immettere una password per accedere al sistema.
. Immettere la nuova password per l'utente selezionato nei due campi.
. Immettere la password dell'amministratore locale per confermare l'operazione, quindi fare clic su *Change* (Modifica).


.Risultati
Se l'utente è attualmente connesso, la modifica della password provoca l'interruzione della sessione attiva dell'utente.
