---
permalink: um-certificates/overview-access-management-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, authentication 
summary: 'La gestione degli accessi è un metodo per configurare l"autenticazione degli utenti in Gestione unificata di SANtricity.' 
---
= Panoramica sulla gestione degli accessi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Access Management è un metodo per configurare l'autenticazione dell'utente in Unified Manager.



== Quali metodi di autenticazione sono disponibili?

Sono disponibili i seguenti metodi di autenticazione:

* *Ruoli utente locali* -- l'autenticazione viene gestita tramite funzionalità RBAC (role-based access control). I ruoli utente locali includono profili utente predefiniti e ruoli con autorizzazioni di accesso specifiche.
* *Servizi di directory* -- l'autenticazione viene gestita tramite un server LDAP (Lightweight Directory Access Protocol) e un servizio di directory, ad esempio Active Directory di Microsoft.


Scopri di più:

* link:how-access-management-works-unified.html["Come funziona Access Management"]
* link:access-management-terminology-unified.html["Terminologia per la gestione degli accessi"]
* link:permissions-for-mapped-roles-unified.html["Autorizzazioni per i ruoli mappati"]




== Come si configura Access Management?

Il software SANtricity è preconfigurato per l'utilizzo dei ruoli utente locali. Se si desidera utilizzare LDAP, è possibile configurarlo nella pagina Gestione accessi.

Scopri di più:

* link:access-management-with-local-user-roles-unified.html["Gestione degli accessi con ruoli utente locali"]
* link:access-management-with-directory-services-unified.html["Gestione degli accessi con servizi di directory"]

