---
permalink: um-certificates/permissions-for-mapped-roles-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, permissions, mapped, roles 
summary: 'Le funzionalità RBAC (role-based access control) includono utenti predefiniti con uno o più ruoli mappati. Ogni ruolo include le autorizzazioni per l"accesso alle attività in Gestione unificata di SANtricity.' 
---
= Autorizzazioni per i ruoli mappati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le funzionalità RBAC (role-based access control) includono utenti predefiniti con uno o più ruoli mappati. Ogni ruolo include le autorizzazioni per l'accesso alle attività in Gestione unificata di SANtricity.

I ruoli forniscono agli utenti l'accesso alle attività, come segue:

* *Storage admin* -- accesso completo in lettura/scrittura agli oggetti storage sugli array, ma nessun accesso alla configurazione di sicurezza.
* *Security admin* -- accesso alla configurazione di sicurezza in Access Management e Certificate Management.
* *Support admin* -- accesso a tutte le risorse hardware su storage array, dati di guasto ed eventi MEL. Nessun accesso agli oggetti di storage o alla configurazione di sicurezza.
* *Monitor* -- accesso in sola lettura a tutti gli oggetti di storage, ma nessun accesso alla configurazione di sicurezza.


Se un utente non dispone delle autorizzazioni per una determinata funzione, tale funzione non è disponibile per la selezione o non viene visualizzata nell'interfaccia utente.
