---
permalink: um-certificates/reset-management-certificates-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, reset, management, certificates 
summary: È possibile ripristinare lo stato originale autofirmato del certificato di gestione. 
---
= Reimpostare i certificati di gestione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare lo stato originale autofirmato del certificato di gestione.

.Prima di iniziare
È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.

.A proposito di questa attività
Questa attività elimina il certificato di gestione corrente dal sistema host in cui sono installati Web Services Proxy e Unified Manager. Una volta ripristinato il certificato, il sistema host torna a utilizzare il certificato autofirmato.

.Fasi
. Selezionare *Certificate Management* (Gestione certificati).
. Dalla scheda Management (Gestione), selezionare *Reset* (Ripristina).
+
Viene visualizzata la finestra di dialogo Conferma ripristino certificato di gestione.

. Tipo `reset` Nel campo, quindi fare clic su *Reset*.
+
Dopo l'aggiornamento del browser, il browser potrebbe bloccare l'accesso al sito di destinazione e segnalare che il sito utilizza HTTP Strict Transport Security. Questa condizione si verifica quando si torna ai certificati autofirmati. Per eliminare la condizione che sta bloccando l'accesso alla destinazione, è necessario cancellare i dati di navigazione dal browser.



.Risultati
Il sistema torna a utilizzare il certificato autofirmato dal server. Di conseguenza, il sistema richiede agli utenti di accettare manualmente il certificato autofirmato per le sessioni.
