---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: È necessario configurare SANtricity Unified Manager con una password di amministratore per proteggerla da accessi non autorizzati. 
---
= Impostare la protezione della password amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare SANtricity Unified Manager con una password di amministratore per proteggerla da accessi non autorizzati.



== Password amministratore e profili utente

Quando si avvia Unified Manager per la prima volta, viene richiesto di impostare una password di amministratore. Qualsiasi utente che dispone della password di amministratore può apportare modifiche alla configurazione degli array di storage.

Oltre alla password di amministratore, l'interfaccia di Unified Manager include profili utente preconfigurati con uno o più ruoli mappati. Per ulteriori informazioni, vedere link:../um-certificates/how-access-management-works-unified.html["Come funziona Access Management"].

Gli utenti e le mappature non possono essere modificati. È possibile modificare solo le password. Per modificare le password, vedere:

* link:change-admin-password-unified.html["Modificare la password admin"]
* link:../um-certificates/change-passwords-unified.html["Modificare le password per i profili utente locali"]




== Timeout della sessione

Il software richiede la password una sola volta durante una singola sessione di gestione. Per impostazione predefinita, una sessione scade dopo 30 minuti di inattività. A questo punto, è necessario immettere nuovamente la password. Se un altro utente accede al software da un altro client di gestione e modifica la password mentre la sessione è in corso, viene richiesta una password la volta successiva che si tenta di eseguire un'operazione di configurazione o un'operazione di visualizzazione.

Per motivi di sicurezza, è possibile tentare di inserire una password solo cinque volte prima che il software entri in uno stato di "blocco". In questo stato, il software rifiuta i successivi tentativi di immissione della password. Attendere 10 minuti per ripristinare lo stato "normale" prima di inserire nuovamente la password.

È possibile regolare i timeout della sessione o disattivarli del tutto. Per ulteriori informazioni, vedere link:manage-session-timeouts-unified.html["Gestire i timeout delle sessioni"].
