---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: È possibile modificare la password admin utilizzata per accedere a Gestione unificata di SANtricity. 
---
= Modificare la password admin
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password admin utilizzata per accedere a Gestione unificata di SANtricity.

.Prima di iniziare
* Devi essere connesso come amministratore locale, che include le autorizzazioni di amministratore root.
* È necessario conoscere la password admin corrente.


.A proposito di questa attività
Quando si sceglie una password, tenere presenti le seguenti linee guida:

* Le password distinguono tra maiuscole e minuscole.
* Gli spazi finali non vengono rimossi dalle password quando vengono impostati. Fare attenzione a includere spazi se inclusi nella password.
* Per una maggiore sicurezza, utilizzare almeno 15 caratteri alfanumerici e modificare la password frequentemente.


.Fasi
. Selezionare menu:Impostazioni[Gestione accessi].
. Selezionare la scheda *ruoli utente locali*.
. Selezionare l'utente *admin* dalla tabella.
+
Il pulsante Change Password (Modifica password) diventa disponibile.

. Selezionare *Change Password* (Modifica password).
+
Viene visualizzata la finestra di dialogo Change Password (Modifica password).

. Se non è stata impostata alcuna lunghezza minima per le password utente locali, selezionare la casella di controllo per richiedere all'utente di immettere una password per accedere al sistema.
. Immettere la nuova password nei due campi.
. Immettere la password dell'amministratore locale per confermare l'operazione, quindi fare clic su *Change* (Modifica).

