---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: È possibile aggiornare le password utilizzate per visualizzare e accedere agli array di storage in Gestione unificata di SANtricity. 
---
= Modificare le password degli array di storage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare le password utilizzate per visualizzare e accedere agli array di storage in Unified Manager.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore dello storage.
* È necessario conoscere la password corrente per lo storage array, impostata in System Manager.


.A proposito di questa attività
In questa attività, immettere la password corrente per uno storage array in modo da potervi accedere in Unified Manager. Questo potrebbe essere necessario se la password dell'array è stata modificata in System Manager e ora deve essere modificata anche in Unified Manager.

.Fasi
. Dalla pagina Manage (Gestione), selezionare uno o più array di storage.
. Selezionare menu:operazioni non comuni[fornire password array di storage].
. Immettere la password o le password per ciascun array di storage, quindi fare clic su *Save* (Salva).

