---
permalink: um-admin/manage-session-timeouts-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, manage, session, timeouts 
summary: È possibile configurare i timeout per Gestione unificata di SANtricity, in modo che le sessioni inattive degli utenti vengano disconnesse dopo un determinato periodo di tempo. 
---
= Gestire i timeout delle sessioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare i timeout per Unified Manager, in modo che le sessioni inattive degli utenti vengano disconnesse dopo un determinato periodo di tempo.

.A proposito di questa attività
Per impostazione predefinita, il timeout della sessione di Unified Manager è di 30 minuti. È possibile regolare l'orario oppure disattivare completamente i timeout della sessione.

.Fasi
. Dalla barra dei menu, selezionare la freccia a discesa accanto al nome di accesso utente.
. Selezionare *Enable/Disable session timeout* (attiva/Disattiva timeout sessione).
+
Viene visualizzata la finestra di dialogo attiva/Disattiva timeout sessione.

. Utilizzare i comandi per aumentare o diminuire il tempo in minuti.
+
Il timeout minimo che è possibile impostare è di 15 minuti.

+
[NOTE]
====
Per disattivare i timeout della sessione, deselezionare la casella di controllo *Imposta la durata...*.

====
. Fare clic su *Save* (Salva).

